import Ajv2020 from 'ajv/dist/2020.js';
import { createHash } from 'node:crypto';
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync, statSync } from 'node:fs';
import { dirname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const PACKAGE_ID = 'gate-b0-execution-admission-contract-v1';
export const PACKAGE_LOCATOR = 'research-lanes/bch-shielded-pool-design/p2/gate-b/gate-b0-execution-admission-contract-v1';
export const DIGEST_PREFIX = 'shieldkit-labs/p2/gate-b/gate-b0-execution-admission-contract/v1';
export const SCHEMA_PREFIX = 'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1';
export const AUTHORED_FILES = Object.freeze(['COMMAND.txt','README.md','execution-admission-contract-root.v1.json','schemas/digest.v1.schema.json','schemas/endpoint-projection.v1.schema.json','schemas/external-requirement.v1.schema.json','schemas/future-result-admission.v1.schema.json','schemas/future-state-grammar.v1.schema.json','schemas/manifest.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/root.v1.schema.json','schemas/source-pin.v1.schema.json','test/digest.kat.json','test/future-boundary.test.mjs','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs','validate-static.mjs']);
export const SEALED_FILES = Object.freeze([...AUTHORED_FILES,'MANIFEST.json','SHA256SUMS']);
export const DIRECTORIES = Object.freeze(['.','schemas','test']);
export const ROOT_KEYS = Object.freeze(['schema','artifactId','packageId','status','executionAllowed','measurementAdmissionAllowed','parentBinding','sourcePins','historicalDisposition','endpointProjectionContract','externalRequirements','futureStateGrammar','futureArtifactMapContract','futureResultAdmissionContract','crashRecoveryContract','nonAuthorityBoundary','runtimeBoundary','schemaBindings','componentDigests','contentDigest']);
export const PARENT_BINDING = Object.freeze({packageId:'gate-b0-evidence-plan-v1',rootLocator:'p2/gate-b/gate-b0-evidence-plan-v1/evidence-plan-root.v1.json',rootBytes:60597,rootRawSha256:'78455f5faed663b73353bb87bd69c475b2a979d73ad2b5b78a0e6cbdc2c1a01b',rootSemanticDigest:'ffb555285bdd98de1be99d1f0526a69c76526321cc1fc45b5b4a6d19322bae63',manifestLocator:'p2/gate-b/gate-b0-evidence-plan-v1/MANIFEST.json',manifestBytes:6847,manifestRawSha256:'1406240ccabd976f3b066500a3b111ba3395ee3dce41c804153e2fddd72f57b7',manifestRosterDigest:'da54495f9ec98a44ec164187bfea06f25127bbdd4cb5c478c4bdcee202f49611',sumsLocator:'p2/gate-b/gate-b0-evidence-plan-v1/SHA256SUMS',sumsBytes:1468,sumsRawSha256:'5e02267005bdda74cbc681f9d0d0f5592a65294dc4f727d14556fb381e93625a',validatorLocator:'p2/gate-b/gate-b0-evidence-plan-v1/validate-static.mjs',validatorBytes:50253,validatorRawSha256:'739fd21bda2dab59bd18f0e0c641be6a9eccd1c0e7bd637a0b8163068c399893',reviewAnchorLocator:'p2/gate-b/gate-b0-evidence-plan-review-anchor.v1.json',reviewAnchorBytes:8541,reviewAnchorRawSha256:'920b52f253ca186c92d80c9b9b69aa8669c0109923b0b418df86f5b783d5d34f'});
export const REQUIREMENT_IDS = Object.freeze(['RECOVERY_CHAIN_OWNER_PROVIDER','REQUEST_OWNER_PROVIDER','ACTIVATION_OWNER_PROVIDER','PRIVATE_CAPTURE_OWNER_PROVIDER','PRIVATE_DESCRIPTOR_OWNER_PROVIDER','EXCLUSIVE_C_OWNER_PROVIDER','PRIVATE_DISPATCH_OWNER_PROVIDER','RETRY_ORDER_PROVIDER','LIVE_F_RECORD_ORDER_PROVIDER','FROZEN_SURFACE_ORDER_PROVIDER','ENDPOINT_CONTROL_ORDER_PROVIDER','WORKLOAD_ROOT_ORDER_PROVIDER','WORKLOAD_PROJECTION_PROVIDER','ENDPOINT_BYTE_AUTHORITY_PROVIDER','RETRY_PREDECESSOR_PROVIDER','LIVE_F_CAPTURE_PROVIDER','WORKER_ROWS_ROOT_PROVIDER','Q_INITIAL_PROVIDER','Q_RETRY_PROVIDER','Q_ABORT_PROVIDER','A_INITIAL_PROVIDER','A_RETRY_PROVIDER','A_ABORT_PROVIDER','LIVE_F_PROVIDER','B_SUBJECT_ROOT_TYPE','B_PROVIDER','C_PROVIDER','J_ROOT_TYPE','DISPATCH_PLAN_PROVIDER','D_PROVIDER']);
export const RETRY_EDGES = Object.freeze([['RECOVERY_CHAIN_OWNER_PROVIDER','RETRY_PREDECESSOR_PROVIDER'],['RETRY_ORDER_PROVIDER','RETRY_PREDECESSOR_PROVIDER'],['RETRY_PREDECESSOR_PROVIDER','Q_RETRY_PROVIDER'],['REQUEST_OWNER_PROVIDER','Q_RETRY_PROVIDER'],['Q_RETRY_PROVIDER','A_RETRY_PROVIDER'],['ACTIVATION_OWNER_PROVIDER','A_RETRY_PROVIDER'],['PRIVATE_CAPTURE_OWNER_PROVIDER','LIVE_F_CAPTURE_PROVIDER'],['LIVE_F_RECORD_ORDER_PROVIDER','LIVE_F_CAPTURE_PROVIDER'],['LIVE_F_CAPTURE_PROVIDER','LIVE_F_PROVIDER'],['PRIVATE_CAPTURE_OWNER_PROVIDER','LIVE_F_PROVIDER'],['A_RETRY_PROVIDER','B_SUBJECT_ROOT_TYPE'],['P','B_SUBJECT_ROOT_TYPE'],['R','B_SUBJECT_ROOT_TYPE'],['K','B_SUBJECT_ROOT_TYPE'],['B_SUBJECT_ROOT_TYPE','B_PROVIDER'],['LIVE_F_PROVIDER','B_PROVIDER'],['PRIVATE_DESCRIPTOR_OWNER_PROVIDER','B_PROVIDER'],['B_PROVIDER','C_PROVIDER'],['EXCLUSIVE_C_OWNER_PROVIDER','C_PROVIDER'],['B_PROVIDER','J_ROOT_TYPE'],['C_PROVIDER','J_ROOT_TYPE'],['FROZEN_SURFACE_ORDER_PROVIDER','WORKLOAD_PROJECTION_PROVIDER'],['ENDPOINT_CONTROL_ORDER_PROVIDER','WORKLOAD_PROJECTION_PROVIDER'],['WORKLOAD_ROOT_ORDER_PROVIDER','WORKLOAD_PROJECTION_PROVIDER'],['WORKLOAD_PROJECTION_PROVIDER','ENDPOINT_BYTE_AUTHORITY_PROVIDER'],['PRIVATE_DISPATCH_OWNER_PROVIDER','ENDPOINT_BYTE_AUTHORITY_PROVIDER'],['ENDPOINT_BYTE_AUTHORITY_PROVIDER','WORKER_ROWS_ROOT_PROVIDER'],['ENDPOINT_CONTROL_ORDER_PROVIDER','WORKER_ROWS_ROOT_PROVIDER'],['PRIVATE_DISPATCH_OWNER_PROVIDER','WORKER_ROWS_ROOT_PROVIDER'],['WORKER_ROWS_ROOT_PROVIDER','DISPATCH_PLAN_PROVIDER'],['PRIVATE_DISPATCH_OWNER_PROVIDER','DISPATCH_PLAN_PROVIDER'],['B_PROVIDER','D_PROVIDER'],['C_PROVIDER','D_PROVIDER'],['J_ROOT_TYPE','D_PROVIDER'],['WORKER_ROWS_ROOT_PROVIDER','D_PROVIDER'],['DISPATCH_PLAN_PROVIDER','D_PROVIDER'],['PRIVATE_DISPATCH_OWNER_PROVIDER','D_PROVIDER']]);
export const RESULT_EDGES = Object.freeze([['RAW_ARTIFACT_MAP_AUTHORITY','Q_RETRY_PROVIDER'],['RAW_ARTIFACT_MAP_AUTHORITY','WORKLOAD_PROJECTION_PROVIDER'],['D_PROVIDER','RAW_ARTIFACT_MAP_INSTANCE'],['RAW_ARTIFACT_MAP_AUTHORITY','RAW_ARTIFACT_MAP_INSTANCE'],['RAW_ARTIFACT_MAP_INSTANCE','RESULT_ADMISSION'],['D_PROVIDER','RESULT_ADMISSION'],['INDEPENDENT_RESULT_VALIDATOR','RESULT_ADMISSION']]);
const SOURCE_PIN_TABLE_DIGEST = '103cada63c1d0f9bac12525bb43f3e0165b8d2329aeb98f9a27e0dac5ea68e07';
const SCHEMA_LOCATORS = Object.freeze(['schemas/digest.v1.schema.json','schemas/endpoint-projection.v1.schema.json','schemas/external-requirement.v1.schema.json','schemas/future-result-admission.v1.schema.json','schemas/future-state-grammar.v1.schema.json','schemas/manifest.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/root.v1.schema.json','schemas/source-pin.v1.schema.json']);
const SCHEMA_PIN_TABLE = Object.freeze([{locator:'schemas/digest.v1.schema.json',rawSha256:'3a9523f6ed708b998dd96af5d38d7de9eabae2099aaf59d4c37c392703308403',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/digest.v1.schema.json'},{locator:'schemas/endpoint-projection.v1.schema.json',rawSha256:'5c6c833aa51693ea6dd6b83459f41c4610c34db6c5bab62046eec34e4d043c75',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/endpoint-projection.v1.schema.json'},{locator:'schemas/external-requirement.v1.schema.json',rawSha256:'7c33d3b0f7aea2990a022d728b28852bc39a48ed2734f0d023ab099331bb0dd6',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/external-requirement.v1.schema.json'},{locator:'schemas/future-result-admission.v1.schema.json',rawSha256:'95c6aef8b1200944562799584f845d2fa13a4bde87803862295a6b9a94b3aa32',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/future-result-admission.v1.schema.json'},{locator:'schemas/future-state-grammar.v1.schema.json',rawSha256:'f4b30a3f05c7d191a4c197dec77b60bdf51cc40d02e7788a1c8f3075526e7410',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/future-state-grammar.v1.schema.json'},{locator:'schemas/manifest.v1.schema.json',rawSha256:'1c889688e336ff63760d512f8c86acb7534516fb2127bc7b3176760603751ab4',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/manifest.v1.schema.json'},{locator:'schemas/non-authority-boundary.v1.schema.json',rawSha256:'07bfc6af00795ec438dc199046896cc25ba0192f18bc52e3e0974df83d53f949',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/non-authority-boundary.v1.schema.json'},{locator:'schemas/root.v1.schema.json',rawSha256:'08a9d6785ce506adf6b24361b6261479c48e0733a0e40ca82eff5c76fc52653c',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/root.v1.schema.json'},{locator:'schemas/source-pin.v1.schema.json',rawSha256:'8691d71aa84f14f548565c37118448283a240bfa92e0d0b02d4d826e8c16d9bb',schemaId:'https://shieldkit-labs.local/p2/gate-b/gate-b0-execution-admission-contract/v1/source-pin.v1.schema.json'}]);
const SOURCE_MODE_SET = new Set([0o444,0o600,0o644]);
const CANONICALIZATION = 'recursive-lexicographic-object-key-sort-arrays-preserve-order-json-utf8-lf-v1';
const P0_FREEZE_MANIFEST_PIN = Object.freeze({bytes:2587,rawSha256:'a55ebd49f117956dc3b0c8a94cf3a3e7b40c5d7477de2a99c53d58bef00012c2'});
const P0_FREEZE_MANIFEST_LOCATOR = 'research-lanes/bch-shielded-pool-design/spec/p0-freeze-manifest.json';
const P0_FREEZE_AGGREGATE = 'db057332197d7a48a90eb65e55884455ab1388e8a0a970f1cb9a9d3b3f17dc52';
const P0_FREEZE_LEAVES = Object.freeze([
  {path:'security/threat-model-fv1.json',bytes:21339,sha256:'9d7e5e811d1d44a9d656f8a3336ccc49036ba2939273484e95e42454ef4efaa8'},
  {path:'security/threat-model-fv1.schema.json',bytes:8226,sha256:'1023c04722dc807f51b741754b7b16ad2cb68d6563841f8b480db06bca5df842'},
  {path:'spec/pool-action-fv1.json',bytes:18848,sha256:'5011dc884f320c85d9dc39c2222289a4864645732a89056b036754ce0dd5d3b6'},
  {path:'spec/pool-action-fv1.schema.json',bytes:13577,sha256:'c6c7cd7576893ae2c30f749438ad36a368fef6865bf1a26f1e4432f7b3174871'},
  {path:'spec/pool-config-fv1.json',bytes:12715,sha256:'e4f60b348b74c064ba0cc7eb2978ffc54a560a7be22696fbc7139e70787e1e08'},
  {path:'spec/pool-state-fv1.md',bytes:3306,sha256:'670decb5e2a6fcb5f1e407eeec83a17e195cd26f3347837bcdae34f4a94b5b8c'},
  {path:'spec/pool-state-fv1.schema.json',bytes:1447,sha256:'79c1498eac1cbbdfa3e05df8d5482288e8f65ef9ab96f9595c7ffc1868a1592c'},
  {path:'spec/responsibility-map-fv1.json',bytes:11140,sha256:'a7702e863c49af099fcee251d550ad27921e35854de7bbce14d7892b10f8f139'},
  {path:'spec/tx-binding-fv1.md',bytes:13836,sha256:'ab133b175a9e2689e3925a48585a04382a195cca6f367e1345ddebb3af9bcbd8'},
  {path:'vectors/pool-action-fv1/index.json',bytes:24298,sha256:'a16450687f5e5c2e4d450df6c18c2b0ff1042ae2192881d5f29f35b8ef5a1dfa'},
  {path:'vectors/pool-action-fv1/index.schema.json',bytes:10427,sha256:'7fc741db6c9ed29b73223187adfff5b73b0bcdf078a60b7a5110c28435b5d647'},
]);
const SOURCE_PIN_ID_ROSTER = Object.freeze(['pin:parent:b0r-root','pin:parent:b0r-manifest','pin:parent:b0r-sums','pin:parent:b0r-validator','pin:parent:b0r-anchor','pin:foundation:p-root','pin:foundation:p-manifest','pin:foundation:p-sums','pin:foundation:r-root','pin:foundation:r-manifest','pin:foundation:r-sums','pin:foundation:k-root','pin:foundation:k-manifest','pin:foundation:k-sums','pin:foundation:f-root','pin:foundation:f-manifest','pin:foundation:f-sums','pin:origin:live-root','pin:origin:live-manifest','pin:origin:live-sums','pin:origin:cabm-root','pin:origin:cabm-manifest','pin:origin:cabm-sums','pin:origin:ecoc-root','pin:origin:ecoc-manifest','pin:origin:ecoc-sums','pin:origin:uopc-root','pin:origin:uopc-manifest','pin:origin:uopc-sums','pin:origin:source-map-root','pin:origin:source-map-manifest','pin:origin:source-map-sums','pin:history:attempt000-auth','pin:history:attempt000-schema','pin:history:accounting-root','pin:history:abort-receipt','pin:history:accounting-manifest','pin:history:accounting-sums','pin:history:retry-wrapper','pin:history:retry-manifest','pin:history:retry-sums','pin:history:v3-contract','pin:history:v3-manifest','pin:history:v3-sums','pin:history:v3-freeze','pin:history:v3-schema','pin:frozen:campaign','pin:frozen:corpus','pin:frozen:fixtures','pin:frozen:work-items','pin:frozen:epoch','pin:frozen:manifest','pin:frozen:sums','pin:frozen:construction','pin:frozen:schedule','pin:frozen:descriptor-m31d5','pin:frozen:descriptor-m31d6','pin:frozen:descriptor-m61d3','pin:frozen:descriptor-m89d2','pin:frozen:engine-native','pin:frozen:engine-libauth','pin:frozen:engine-bchn','pin:frozen:engine-leanbch','pin:frozen:engine-schema']);
const RAW_SEMANTIC_PIN_IDS = Object.freeze(['pin:parent:b0r-sums','pin:parent:b0r-validator','pin:parent:b0r-anchor','pin:foundation:p-sums','pin:foundation:r-sums','pin:foundation:k-root','pin:foundation:k-sums','pin:foundation:f-sums','pin:origin:live-sums','pin:origin:cabm-sums','pin:origin:ecoc-sums','pin:origin:uopc-sums','pin:origin:source-map-sums','pin:history:attempt000-schema','pin:history:accounting-sums','pin:history:retry-sums','pin:history:v3-sums','pin:history:v3-schema','pin:frozen:manifest','pin:frozen:sums','pin:frozen:engine-schema']);
const semanticRule = (type, domain=null, frame=null, bindingKinds=[]) => Object.freeze({type,domain,frame,bindingKinds:Object.freeze(bindingKinds)});
export const SEMANTIC_RULE_BY_PIN_ID = Object.freeze(Object.assign(Object.fromEntries(RAW_SEMANTIC_PIN_IDS.map(id=>[id,semanticRule('RAW')])),{
  'pin:parent:b0r-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/gate-b0-evidence-plan/v1/root','utf8(domain)||0x00||canonical-json-utf8||0x0a',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:parent:b0r-manifest':semanticRule('MANIFEST_ENTRIES_COMPACT_LF','shieldkit-labs/p2/gate-b/gate-b0-evidence-plan/v1/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:foundation:p-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-policy-authority/v1/root','utf8(domain)||0x00||canonical-json-utf8-with-top-level-contentDigest-omitted',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:foundation:p-manifest':semanticRule('MANIFEST_FILES_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-policy-authority/v1/manifest-roster','utf8(domain)||0x00||canonical-json-roster-v1',['MANIFEST_ROSTER_DIGEST']),
  'pin:foundation:r-root':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/root','utf8(domain)||0x00||canonical-json-utf8-with-contentDigest-omitted',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:foundation:r-manifest':semanticRule('MANIFEST_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/file-content','utf8(domain)||0x00||canonical-json-utf8-pretty2||0x0a',['MANIFEST_CONTENT_DIGEST']),
  'pin:foundation:k-manifest':semanticRule('K_MANIFEST',null,null,['K_MANIFEST_PACKAGE_ROOT','K_MANIFEST_ROOT','K_ENTRIES_ROOT']),
  'pin:foundation:f-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-frozen-inputs/v1/root','utf8(domain)||0x00||canonical-json-utf8-with-top-level-contentDigest-omitted',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:foundation:f-manifest':semanticRule('MANIFEST_F_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-frozen-inputs/v1/manifest','utf8(domain)||0x00||canonical-json-utf8-with-top-level-contentDigest-omitted',['MANIFEST_CONTENT_DIGEST','MANIFEST_ROSTER_DIGEST']),
  'pin:origin:live-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-live-executor/v2/root','utf8(domain)||0x00||canonical-json-utf8-lf-v1',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:origin:live-manifest':semanticRule('MANIFEST_PACKAGE_ENTRIES_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-live-executor/v2/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:origin:cabm-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-authority-binding-model/v1/root','utf8(domain)||0x00||canonical-json-utf8-lf-v1',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:origin:cabm-manifest':semanticRule('MANIFEST_PACKAGE_ENTRIES_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-authority-binding-model/v1/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:origin:ecoc-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-external-origin-contract/v1/root','utf8(domain)||0x00||canonical-json-utf8-lf-v1',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:origin:ecoc-manifest':semanticRule('MANIFEST_PACKAGE_ENTRIES_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-external-origin-contract/v1/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:origin:uopc-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-upstream-origin-provider-contract/v1/model-root','utf8(domain)||0x00||canonical-json-utf8-lf-v1',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:origin:uopc-manifest':semanticRule('MANIFEST_AUTHORED_LOCATORS_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-upstream-origin-provider-contract/v1/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:origin:source-map-root':semanticRule('FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-upstream-provider-source-map/v1/model-root','utf8(domain)||0x00||canonical-json-utf8-lf-v1',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:origin:source-map-manifest':semanticRule('MANIFEST_AUTHORED_LOCATORS_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-upstream-provider-source-map/v1/manifest-roster','utf8(domain)||0x00||canonical-json-utf8||0x0a',['MANIFEST_ROSTER_DIGEST']),
  'pin:history:attempt000-auth':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-executor-v2/authorization/v2/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:history:accounting-root':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-attempt-accounting/v1/root/attempt-000','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:history:abort-receipt':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-attempt-accounting/v1/receipt/attempt-000','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:history:accounting-manifest':semanticRule('MANIFEST_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-attempt-accounting-v1/package-manifest/root','utf8(domain)||0x00||canonical-json-utf8',['MANIFEST_CONTENT_DIGEST']),
  'pin:history:retry-wrapper':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-retry/v1/attempt-001','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:history:retry-manifest':semanticRule('MANIFEST_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-retry/v1/package-manifest/root','utf8(domain)||0x00||canonical-json-utf8',['MANIFEST_CONTENT_DIGEST']),
  'pin:history:v3-contract':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-contract/v3/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:history:v3-manifest':semanticRule('MANIFEST_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-execution-v3/package-manifest/root','utf8(domain)||0x00||canonical-json-utf8',['MANIFEST_CONTENT_DIGEST']),
  'pin:history:v3-freeze':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/cohort-v3-freeze/v1/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:campaign':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/campaign/v2/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:corpus':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/canonical-corpus/v2/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:fixtures':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/fixture-roster','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:work-items':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/work-item-roster','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:epoch':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/root','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:construction':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_STRING']),
  'pin:frozen:schedule':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:descriptor-m31d5':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:descriptor-m31d6':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:descriptor-m61d3':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:descriptor-m89d2':semanticRule('UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST',null,'sha256-jcs-omit-contentDigest',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:engine-native':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/engine/engine:native','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:engine-libauth':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/engine/engine:libauth','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:engine-bchn':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/engine/engine:bchn','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE']),
  'pin:frozen:engine-leanbch':semanticRule('FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST','shieldkit-labs/p2/gate-b/execution-epoch/v2/engine/engine:leanbch','utf8(domain)||0x00||canonical-json-utf8',['CONTENT_DIGEST_RECORD_VALUE'])
}));
const fail = code => { throw new Error(code); };
const assert = (ok, code) => { if (!ok) fail(code); };
const same = (a,b) => canonicalJson(a) === canonicalJson(b);
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
export const canonicalJson = value => Array.isArray(value) ? `[${value.map(canonicalJson).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}` : JSON.stringify(value);
export const componentDigest = (domain, value) => sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),Buffer.from(`${canonicalJson(value)}\n`)]));
export const rawFileDigest = (domain, bytes) => sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),bytes]));
const digestRecord = (domain,value) => ({algorithm:'sha256',canonicalization:'recursive-lexicographic-object-key-sort-arrays-preserve-order-json-utf8-lf-v1',domain,frame:'utf8(domain)||0x00||canonical-json-utf8||0x0a',value:componentDigest(domain,value)});
const fileDigestRecord = (locator,bytes) => { const domain=`${DIGEST_PREFIX}/file/${locator}`; return {algorithm:'sha256',canonicalization:'raw-file-bytes-v1',domain,frame:'utf8(domain)||0x00||raw-file-bytes',value:rawFileDigest(domain,bytes)}; };
const exactKeys = (value, keys, code) => assert(value && typeof value === 'object' && !Array.isArray(value) && same(Object.keys(value).sort(),[...keys].sort()),code);
export const safeLocator = (locator, code='LOCATOR') => { assert(typeof locator==='string' && locator.length>0 && !isAbsolute(locator) && !locator.includes('\\') && !locator.includes('\0') && locator.normalize('NFC')===locator,`${code}:FORMAT`); const parts=locator.split('/'); assert(parts.every(part=>part.length>0&&part!=='.'&&part!=='..'),`${code}:SEGMENT`); return parts; };
export const assertNoDuplicateJsonKeys = (bytes, code='JSON_DUPLICATE') => { const text=bytes.toString('utf8'); let i=0; const ws=()=>{while(/\s/.test(text[i]??''))i+=1;}; const str=()=>{assert(text[i++]==='"',`${code}:STRING`);let out='';for(;i<text.length;){const c=text[i++];if(c==='"')return out;if(c==='\\'){const e=text[i++];assert(e!==undefined,`${code}:ESCAPE`);out+=`\\${e}`;if(e==='u'){out+=text.slice(i,i+4);i+=4;}}else out+=c;}fail(`${code}:UNTERMINATED`);}; const val=()=>{ws();const c=text[i];if(c==='{'){i+=1;ws();const keys=new Set();if(text[i]==='}'){i+=1;return;}for(;;){ws();const key=str();assert(!keys.has(key),`${code}:${key}`);keys.add(key);ws();assert(text[i++] === ':',`${code}:COLON`);val();ws();if(text[i]==='}'){i+=1;return;}assert(text[i++]===',',`${code}:COMMA`);}}if(c==='['){i+=1;ws();if(text[i]===']'){i+=1;return;}for(;;){val();ws();if(text[i]===']'){i+=1;return;}assert(text[i++]===',',`${code}:ARRAY_COMMA`);}}if(c==='"'){str();return;}const m=/^(?:true|false|null|-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)/.exec(text.slice(i));assert(m,`${code}:TOKEN`);i+=m[0].length;}; val();ws();assert(i===text.length,`${code}:TRAILING`); };
const localPath = (root, locator, code) => { safeLocator(locator,code); const target=resolve(root,locator); const rel=relative(root,target); assert(rel===''||(!rel.startsWith('..')&&!isAbsolute(rel)),`${code}:CONTAINMENT`); return target; };
const localBytes = (root, locator, code) => { const target=localPath(root,locator,code); const st=lstatSync(target); assert(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1,`${code}:FILE`); return readFileSync(target); };
const collectTree = (root, relativePath='') => { const path=relativePath?resolve(root,relativePath):root; const st=lstatSync(path); assert(!st.isSymbolicLink(),`PACKAGE_LINK:${relativePath||'.'}`); if(st.isFile())return {directories:[],files:[relativePath]}; assert(st.isDirectory(),`PACKAGE_TYPE:${relativePath||'.'}`); const result={directories:[relativePath||'.'],files:[]}; for(const entry of readdirSync(path,{withFileTypes:true})){const nested=collectTree(root,relativePath?`${relativePath}/${entry.name}`:entry.name);result.directories.push(...nested.directories);result.files.push(...nested.files);} return result; };
export const checkPackage = (packageRoot, mode) => { assert(mode==='unsealed'||mode==='sealed','MODE'); const unresolved=resolve(packageRoot); const st=lstatSync(unresolved); assert(st.isDirectory()&&!st.isSymbolicLink(),'PACKAGE_ROOT'); const root=realpathSync(unresolved); const tree=collectTree(root); assert(same(tree.directories.sort(),[...DIRECTORIES].sort()),'PACKAGE_DIRECTORY_ROSTER'); for(const dir of DIRECTORIES){const target=dir==='.'?root:localPath(root,dir,'DIRECTORY');const ds=lstatSync(target);assert(ds.isDirectory()&&!ds.isSymbolicLink()&&(ds.mode&0o777)===0o755,`DIRECTORY:${dir}`);} const actual=tree.files.sort(); const expected=(mode==='sealed'?SEALED_FILES:AUTHORED_FILES).slice().sort(); assert(same(actual,expected),`PACKAGE_CLOSURE:${mode}`); for(const locator of expected){const fs=lstatSync(localPath(root,locator,'PACKAGE_FILE'));assert(fs.isFile()&&!fs.isSymbolicLink()&&fs.nlink===1&&(fs.mode&0o777)===0o644,`PACKAGE_FILE:${locator}`);} if(mode==='unsealed')assert(!existsSync(resolve(root,'MANIFEST.json'))&&!existsSync(resolve(root,'SHA256SUMS')),'UNSEALED_ENVELOPE_ABSENT'); return root; };
export const safeExternalRead = (repositoryRoot, locator, expected, code='EXTERNAL') => { const rootUnresolved=resolve(repositoryRoot); const rootStat=lstatSync(rootUnresolved); assert(rootStat.isDirectory()&&!rootStat.isSymbolicLink(),`${code}:ROOT_METADATA`); const root=realpathSync(rootUnresolved); const parts=safeLocator(locator,`${code}:LOCATOR`); let cursor=root; for(const [index,part] of parts.entries()){cursor=resolve(cursor,part);const st=lstatSync(cursor);assert(!st.isSymbolicLink(),`${code}:SYMLINK`);const real=realpathSync(cursor);const rel=relative(root,real);assert(rel===''||(!rel.startsWith('..')&&!isAbsolute(rel)),`${code}:ESCAPE`);if(index<parts.length-1)assert(st.isDirectory(),`${code}:DIRECTORY`);else{assert(st.isFile()&&st.nlink===1,`${code}:FILE`);assert(SOURCE_MODE_SET.has(st.mode&0o777),`${code}:MODE`);const bytes=readFileSync(real);assert(bytes.length===expected.bytes,`${code}:BYTES`);assert(sha256(bytes)===expected.rawSha256,`${code}:RAW`);return bytes;}} fail(`${code}:EMPTY`); };
const parseCanonical = (root, locator, code=locator) => { const bytes=localBytes(root,locator,code); assertNoDuplicateJsonKeys(bytes,`${code}:DUPLICATE`); let value;try{value=JSON.parse(bytes);}catch{fail(`${code}:PARSE`);} assert(bytes.toString('utf8')===`${canonicalJson(value)}\n`,`${code}:CANONICAL`); return value; };
const parseExternalJson = (bytes, code) => { assertNoDuplicateJsonKeys(bytes,`${code}:DUPLICATE`); try{return JSON.parse(bytes);}catch{fail(`${code}:PARSE`);} };
export const assertP0Freeze = repositoryRoot => {
  const manifest=parseExternalJson(safeExternalRead(repositoryRoot,P0_FREEZE_MANIFEST_LOCATOR,P0_FREEZE_MANIFEST_PIN,'P0_MANIFEST'),'P0_MANIFEST');
  assert(manifest.schema==='shieldkit-labs/poolactionfv1-p0-freeze-manifest/v1'&&manifest.aggregate?.algorithm==='sha256','P0_MANIFEST_SHAPE');
  assert(Array.isArray(manifest.artifacts)&&manifest.artifacts.length===P0_FREEZE_LEAVES.length,'P0_LEAF_COUNT');
  const seen=new Set();
  for(const row of manifest.artifacts){assert(row&&typeof row.path==='string'&&typeof row.sha256==='string','P0_LEAF_SHAPE');safeLocator(row.path,'P0_LEAF_PATH');assert(!seen.has(row.path),'P0_LEAF_DUPLICATE');seen.add(row.path);}
  assert(same(manifest.artifacts.map(row=>row.path),P0_FREEZE_LEAVES.map(row=>row.path)),'P0_LEAF_ORDER');
  assert(same(manifest.artifacts.map(({path,sha256})=>({path,sha256})),P0_FREEZE_LEAVES.map(({path,sha256})=>({path,sha256}))),'P0_LEAF_ROSTER');
  for(const row of P0_FREEZE_LEAVES)safeExternalRead(repositoryRoot,`research-lanes/bch-shielded-pool-design/${row.path}`,{bytes:row.bytes,rawSha256:row.sha256},`P0_LEAF:${row.path}`);
  const aggregate=sha256(Buffer.from(P0_FREEZE_LEAVES.map(row=>`${row.path}\0${row.sha256}\n`).join('')));
  assert(aggregate===P0_FREEZE_AGGREGATE&&manifest.aggregate.sha256===aggregate,'P0_AGGREGATE');
};
const sourceTableDigest = rows => componentDigest(`${DIGEST_PREFIX}/source-pins`,rows);
const domainHashNoLf = (domain,value) => sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),Buffer.from(canonicalJson(value))]));
const framedCompactLf = (domain,value) => componentDigest(domain,value);
const framedPrettyLf = (domain,value) => sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),Buffer.from(`${JSON.stringify(JSON.parse(canonicalJson(value)),null,2)}\n`)]));
const withoutContentDigest = value => { assert(value&&typeof value==='object'&&!Array.isArray(value),'SOURCE_SEMANTIC_DOCUMENT'); const copy={...value}; delete copy.contentDigest; return copy; };
const assertBindingValues = (row, rule, values) => { assert(same(row.semanticBindings.map(item=>item.kind),rule.bindingKinds),`SOURCE:${row.pinId}:SEMANTIC_KIND`); assert(same(row.semanticBindings,values.map(([kind,value])=>({kind,value}))),`SOURCE:${row.pinId}:SEMANTIC_BINDING`); };
const assertContentRecord = (value, rule, derived, code) => { const record=value?.contentDigest; exactKeys(record,['algorithm','canonicalization','domain','frame','value'],`${code}:DIGEST_SHAPE`); assert(record.algorithm==='sha256'&&record.canonicalization===CANONICALIZATION,`${code}:DIGEST_ALGORITHM`); assert(record.domain===rule.domain,`${code}:SEMANTIC_DOMAIN`); assert(record.frame===rule.frame,`${code}:SEMANTIC_FRAME`); assert(record.value===derived,`${code}:SEMANTIC_RECOMPUTE`); return record.value; };
const assertRosterRecord = (record, rule, derived, code) => { exactKeys(record,['algorithm','canonicalization','domain','frame','value'],`${code}:ROSTER_SHAPE`); assert(record.algorithm==='sha256'&&record.canonicalization===CANONICALIZATION,`${code}:ROSTER_ALGORITHM`); assert(record.domain===rule.domain,`${code}:SEMANTIC_DOMAIN`); assert(record.frame===rule.frame,`${code}:SEMANTIC_FRAME`); assert(record.value===derived,`${code}:SEMANTIC_RECOMPUTE`); return record.value; };
const UOPC_AUTHORED_LOCATORS = Object.freeze(['COMMAND.txt','README.md','schemas/dependency-catalog.v1.schema.json','schemas/digest.v1.schema.json','schemas/external-origin-provider-catalog.v1.schema.json','schemas/fact-provider-catalog.v1.schema.json','schemas/manifest.v1.schema.json','schemas/model-root.v1.schema.json','schemas/order-provider-catalog.v1.schema.json','schemas/owner-provider-catalog.v1.schema.json','schemas/projection-provider-catalog.v1.schema.json','schemas/provider-dag.v1.schema.json','schemas/root-provider-catalog.v1.schema.json','test/digest.kat.json','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs','upstream-origin-provider-contract-root.v1.json','validate-static.mjs']);
const SOURCE_MAP_AUTHORED_LOCATORS = Object.freeze(['COMMAND.txt','README.md','upstream-provider-source-map-root.v1.json','schemas/b1-reentry-boundary.v1.schema.json','schemas/dependency-catalog.v1.schema.json','schemas/digest.v1.schema.json','schemas/interface-source-map.v1.schema.json','schemas/manifest.v1.schema.json','schemas/mapping-dag.v1.schema.json','schemas/model-root.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/source-reference-catalog.v1.schema.json','schemas/uopc-contract-prefix.v1.schema.json','validate-static.mjs','test/digest.kat.json','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs']);
const MANIFEST_PACKAGE_BY_PIN_ID = Object.freeze({'pin:origin:live-manifest':'cohort-live-executor-v2','pin:origin:cabm-manifest':'cohort-authority-binding-model-v1','pin:origin:ecoc-manifest':'cohort-external-origin-contract-v1'});
export const assertSourceSemantic = (row, value) => {
  const rule=SEMANTIC_RULE_BY_PIN_ID[row?.pinId];
  const code=`SOURCE:${row?.pinId??'UNKNOWN'}`;
  assert(rule!==undefined,`${code}:SEMANTIC_RULE`);
  if(rule.type==='RAW'){assertBindingValues(row,rule,[]);return true;}
  let derived;
  if(rule.type==='FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST'||rule.type==='FRAMED_PRETTY2_LF_OMIT_CONTENT_DIGEST'){
    derived=rule.type==='FRAMED_COMPACT_LF_OMIT_CONTENT_DIGEST'?framedCompactLf(rule.domain,withoutContentDigest(value)):framedPrettyLf(rule.domain,withoutContentDigest(value));
    assertBindingValues(row,rule,[['CONTENT_DIGEST_RECORD_VALUE',assertContentRecord(value,rule,derived,code)]]);
    return true;
  }
  if(rule.type==='UNFRAMED_COMPACT_OMIT_CONTENT_DIGEST'){
    const record=value?.contentDigest;
    if(row.pinId==='pin:frozen:construction'){assert(typeof record==='string',`${code}:DIGEST_SHAPE`);derived=sha256(Buffer.from(canonicalJson(withoutContentDigest(value))));assertBindingValues(row,rule,[['CONTENT_DIGEST_STRING',record]]);assert(derived===record,`${code}:SEMANTIC_RECOMPUTE`);}else{exactKeys(record,['algorithm','value'],`${code}:DIGEST_SHAPE`);assert(record.algorithm===rule.frame,`${code}:SEMANTIC_FRAME`);derived=sha256(Buffer.from(canonicalJson(withoutContentDigest(value))));assertBindingValues(row,rule,[['CONTENT_DIGEST_RECORD_VALUE',record.value]]);assert(derived===record.value,`${code}:SEMANTIC_RECOMPUTE`);}return true;
  }
  if(rule.type==='MANIFEST_ENTRIES_COMPACT_LF'){
    assert(Array.isArray(value?.entries),`${code}:MANIFEST_ENTRIES`);derived=framedCompactLf(rule.domain,value.entries);assertBindingValues(row,rule,[['MANIFEST_ROSTER_DIGEST',assertRosterRecord(value.rosterDigest,rule,derived,code)]]);return true;
  }
  if(rule.type==='MANIFEST_FILES_COMPACT_LF'){
    assert(Array.isArray(value?.files),`${code}:MANIFEST_FILES`);derived=framedCompactLf(rule.domain,value.files);assertBindingValues(row,rule,[['MANIFEST_ROSTER_DIGEST',assertRosterRecord(value.manifestRosterDigest,rule,derived,code)]]);return true;
  }
  if(rule.type==='MANIFEST_PRETTY2_LF_OMIT_CONTENT_DIGEST'){
    derived=framedPrettyLf(rule.domain,withoutContentDigest(value));
    if(typeof value?.contentDigest==='string'){assertBindingValues(row,rule,[['MANIFEST_CONTENT_DIGEST',value.contentDigest]]);assert(value.contentDigest===derived,`${code}:SEMANTIC_RECOMPUTE`);}else assertBindingValues(row,rule,[['MANIFEST_CONTENT_DIGEST',assertContentRecord(value,rule,derived,code)]]);
    return true;
  }
  if(rule.type==='MANIFEST_F_COMPACT_LF'){
    derived=framedCompactLf(rule.domain,withoutContentDigest(value));const content=assertContentRecord(value,rule,derived,code);const rosterRule=semanticRule('MANIFEST_FILES_COMPACT_LF','shieldkit-labs/p2/gate-b/cohort-frozen-inputs/v1/manifest-roster','utf8(domain)||0x00||canonical-json-roster-v1');assert(Array.isArray(value.files),`${code}:MANIFEST_FILES`);const roster=assertRosterRecord(value.manifestRosterDigest,rosterRule,framedCompactLf(rosterRule.domain,value.files),code);assertBindingValues(row,rule,[['MANIFEST_CONTENT_DIGEST',content],['MANIFEST_ROSTER_DIGEST',roster]]);return true;
  }
  if(rule.type==='MANIFEST_PACKAGE_ENTRIES_COMPACT_LF'){
    const expectedPackage=MANIFEST_PACKAGE_BY_PIN_ID[row.pinId];assert(value?.package===expectedPackage&&Array.isArray(value?.entries),`${code}:MANIFEST_PACKAGE`);derived=framedCompactLf(rule.domain,{package:expectedPackage,entries:value.entries});assert(typeof value.rosterDigest==='string'&&value.rosterDigest===derived,`${code}:SEMANTIC_RECOMPUTE`);assertBindingValues(row,rule,[['MANIFEST_ROSTER_DIGEST',value.rosterDigest]]);return true;
  }
  if(rule.type==='MANIFEST_AUTHORED_LOCATORS_COMPACT_LF'){
    const expected=row.pinId==='pin:origin:uopc-manifest'?UOPC_AUTHORED_LOCATORS:SOURCE_MAP_AUTHORED_LOCATORS;assert(Array.isArray(value?.entries),`${code}:MANIFEST_ENTRIES`);const locators=value.entries.map(entry=>entry?.locator);assert(same(locators,expected),`${code}:MANIFEST_LOCATOR_ROSTER`);derived=framedCompactLf(rule.domain,expected);assert(typeof value.rosterDigest==='string'&&value.rosterDigest===derived,`${code}:SEMANTIC_RECOMPUTE`);assertBindingValues(row,rule,[['MANIFEST_ROSTER_DIGEST',value.rosterDigest]]);return true;
  }
  if(rule.type==='K_MANIFEST'){
    assert(Array.isArray(value?.entries),`${code}:K_ENTRIES`);const entriesRoot=domainHashNoLf('K/ENTRIES',value.entries);const body={...value};delete body.manifestRoot;delete body.packageRoot;const manifestRoot=domainHashNoLf('K/MANIFEST',body);const packageRoot=domainHashNoLf('K/PACKAGE',{manifestRoot,entriesRoot,executionAllowed:false});assert(value.entriesRoot===entriesRoot&&value.manifestRoot===manifestRoot&&value.packageRoot===packageRoot,`${code}:SEMANTIC_RECOMPUTE`);assertBindingValues(row,rule,[['K_MANIFEST_PACKAGE_ROOT',packageRoot],['K_MANIFEST_ROOT',manifestRoot],['K_ENTRIES_ROOT',entriesRoot]]);return true;
  }
  fail(`${code}:SEMANTIC_RULE`);
};
const assertSourcePins = (root, repositoryRoot) => { assert(root.sourcePins.length===64,'SOURCE_PIN_COUNT');const ids=new Set();const locators=new Set();for(const row of root.sourcePins){assert(!ids.has(row.pinId)&&!locators.has(row.locator),'SOURCE_PIN_DUPLICATE');ids.add(row.pinId);locators.add(row.locator);}assert(same(root.sourcePins.map(row=>row.pinId),SOURCE_PIN_ID_ROSTER),'SOURCE_PIN_ID_ROSTER');assert(same(Object.keys(SEMANTIC_RULE_BY_PIN_ID).sort(),[...SOURCE_PIN_ID_ROSTER].sort()),'SOURCE_SEMANTIC_RULE_ROSTER');assert(sourceTableDigest(root.sourcePins)===SOURCE_PIN_TABLE_DIGEST,'SOURCE_PIN_LITERAL_TABLE');const found=new Map();for(const row of root.sourcePins){const bytes=safeExternalRead(repositoryRoot,row.locator,row,`SOURCE:${row.pinId}`);let json=null;if(row.semanticBindings.length){json=parseExternalJson(bytes,`SOURCE:${row.pinId}`);assertSourceSemantic(row,json);}else assertSourceSemantic(row,null);found.set(row.pinId,{row,bytes,json});}return found; };
const assertParent = root => { assert(same(root.parentBinding,PARENT_BINDING),'PARENT_BINDING'); };
const HISTORICAL_DISPOSITION = Object.freeze({attempt000:'STALE_CONSUMED_ABORTED_AUTHORITY_NO_REUSE',attempt001Retry:'CURRENT_STATIC_RETRY_INTENT_TEMPLATE_NOT_AUTHORIZED_NOT_REQUESTED',v3:'CURRENT_STATIC_COMPONENT_SCRIPT_TEMPLATE_NO_POOL_AUTHORITY_NO_EXECUTION'});
const assertHistorical = root => { assert(same(root.historicalDisposition,HISTORICAL_DISPOSITION),'HISTORICAL_DISPOSITION'); };
const assertSchemaBindings = (root, packageRoot) => { assert(same(root.schemaBindings,SCHEMA_PIN_TABLE),'SCHEMA_PIN_TABLE');assert(same(root.schemaBindings.map(row=>row.locator),SCHEMA_LOCATORS),'SCHEMA_BINDING_ROSTER');for(const row of root.schemaBindings){const bytes=localBytes(packageRoot,row.locator,`SCHEMA:${row.locator}`);assert(sha256(bytes)===row.rawSha256,`SCHEMA:${row.locator}:RAW`);const schema=parseCanonical(packageRoot,row.locator,`SCHEMA:${row.locator}`);assert(schema.$id===row.schemaId,`SCHEMA:${row.locator}:ID`);} };
const assertSchemaRawPins = packageRoot => { for(const row of SCHEMA_PIN_TABLE){const bytes=localBytes(packageRoot,row.locator,`SCHEMA:${row.locator}`);assert(sha256(bytes)===row.rawSha256,`SCHEMA:${row.locator}:RAW`);} };
const pointerAt = (value, fragment, code) => { if(fragment===''||fragment==='#')return value;assert(fragment.startsWith('#/'),`${code}:FRAGMENT`);let current=value;for(const token of fragment.slice(2).split('/')){const key=token.replaceAll('~1','/').replaceAll('~0','~');assert(current&&typeof current==='object'&&Object.hasOwn(current,key),`${code}:POINTER`);current=current[key];}return current; };
const assertSchemaReachability = schemas => { const byId=new Map(schemas.map(schema=>[schema.$id,schema]));assert(byId.size===SCHEMA_LOCATORS.length,'SCHEMA_ID_ROSTER');const visited=new Set();const visit=(schemaId,node,marker)=>{const id=`${schemaId}${marker}`;if(visited.has(id))return;visited.add(id);if(!node||typeof node!=='object')return;assert(!Object.hasOwn(node,'$dynamicRef')&&!Object.hasOwn(node,'$recursiveRef')&&!Object.hasOwn(node,'$recursiveAnchor')&&!Object.hasOwn(node,'oneOf')&&!Object.hasOwn(node,'anyOf')&&!Object.hasOwn(node,'allOf'),'SCHEMA_FORBIDDEN_COMBINATOR');if(Object.hasOwn(node,'$ref')){const ref=node.$ref;assert(typeof ref==='string'&&!ref.includes('..')&&!ref.includes('\\'),'SCHEMA_REF_FORMAT');const hash=ref.indexOf('#');const targetId=hash<0?ref:ref.slice(0,hash);const fragment=hash<0?'':ref.slice(hash);const resolvedId=targetId||schemaId;const targetSchema=byId.get(resolvedId);assert(targetSchema,'SCHEMA_REF_TARGET');visit(resolvedId,pointerAt(targetSchema,fragment,`SCHEMA_REF:${ref}`),fragment||'#');return;}for(const [key,child] of Object.entries(node)){if(key==='$defs')continue;if(Array.isArray(child))child.forEach((item,index)=>visit(schemaId,item,`${marker}/${key}/${index}`));else visit(schemaId,child,`${marker}/${key}`);}};for(const schema of schemas)visit(schema.$id,schema,'#');for(const schema of schemas){for(const name of Object.keys(schema.$defs??{}))assert(visited.has(`${schema.$id}#/$defs/${name}`),'SCHEMA_UNUSED_DEF');} };
const STATIC_FORBIDDEN_IMPORTS = new Set(['node:'+'child_process','node:'+'vm','node:'+'worker_threads']);
const STATIC_FORBIDDEN_CALL = new RegExp(`\\b(?:${['sp'+'awn','spawn'+'Sync','ex'+'ecFile','exec'+'FileSync','fo'+'rk'].join('|')})\\s*\\(`,'u');
const assertStaticSourceBoundary = packageRoot => { for(const locator of AUTHORED_FILES.filter(name=>name.endsWith('.mjs'))){const source=localBytes(packageRoot,locator,`STATIC_SOURCE:${locator}`).toString('utf8');assert(!STATIC_FORBIDDEN_CALL.test(source),`STATIC_FORBIDDEN_ACTIVATION:${locator}`);for(const match of source.matchAll(/(?:from\s*|import\s*\()(['"])([^'"]+)\1/gu)){const specifier=match[2];assert(!STATIC_FORBIDDEN_IMPORTS.has(specifier),`STATIC_FORBIDDEN_ACTIVATION:${locator}`);assert(specifier.startsWith('node:')||specifier==='ajv/dist/2020.js'||specifier==='../validate-static.mjs',`STATIC_IMPORT:${locator}`);}} };
const expectedRequirement = id => ({requirementId:id,sourceContractRef:`uopc:dag:${id}`,disposition:['Q_INITIAL_PROVIDER','Q_ABORT_PROVIDER','A_INITIAL_PROVIDER','A_ABORT_PROVIDER'].includes(id)?'TYPE_ONLY_OUT_OF_SCOPE_ATTEMPT_001':['B_SUBJECT_ROOT_TYPE','J_ROOT_TYPE'].includes(id)?'DERIVED_TYPE_ONLY_NO_PROVIDER_NO_INSTANCE':'UNAVAILABLE_EXTERNAL_PROVIDER_NO_INSTANCE',instanceCount:0,authorityGranted:false,admissionGranted:false});
const assertRequirements = (root, found) => { const expected=REQUIREMENT_IDS.map(expectedRequirement);assert(same(root.externalRequirements,expected),'EXTERNAL_REQUIREMENT_ROSTER');if(found&&found.size){const uopc=[...found.values()].find(v=>v.row.role==='UOPC_ROOT')?.json;assert(uopc&&Array.isArray(uopc.providerCausalDag?.nodes),'UOPC_SOURCE');const nodes=new Set(uopc.providerCausalDag.nodes);for(const row of root.externalRequirements)assert(nodes.has(row.requirementId),`UOPC_REQUIREMENT:${row.requirementId}`);}};
const expectedProjection = {endpoints:[{endpointId:'native',alias:'engine:native',frozenRole:'engine:native'},{endpointId:'libauth',alias:'engine:libauth',frozenRole:'engine:libauth'},{endpointId:'bchn',alias:'engine:bchn',frozenRole:'engine:bchn'},{endpointId:'leanbch-primary',alias:'engine:leanbch:primary',frozenRole:'engine:leanbch'},{endpointId:'leanbch-secondary',alias:'engine:leanbch:secondary',frozenRole:'engine:leanbch'}],frozenFixtureRows:4732,rowsPerEndpoint:4608,preflightInvalidFixtureRows:124,legacyEngineRoles:4,legacyExecutableObligations:18432,legacyPreflightTerminalObligations:496,legacyTotalObligations:18928,totalEndpointRawRows:23040,launchAuthorityRows:5,leanPairComparisonRoles:1,projectionStatus:'STATIC_ONLY_NO_ENDPOINT_LAUNCH_AUTHORITY'};
const assertProjection = root => { assert(same(root.endpointProjectionContract,expectedProjection),'ENDPOINT_PROJECTION'); const p=root.endpointProjectionContract;assert(p.rowsPerEndpoint*4===p.legacyExecutableObligations&&p.preflightInvalidFixtureRows*4===p.legacyPreflightTerminalObligations&&p.legacyExecutableObligations+p.legacyPreflightTerminalObligations===p.legacyTotalObligations&&p.rowsPerEndpoint*5===p.totalEndpointRawRows,'ENDPOINT_PROJECTION_COUNTS'); };
const checkAcyclic = edges => { const nodes=new Set(edges.flat());const ins=new Map([...nodes].map(n=>[n,0]));for(const[,to]of edges)ins.set(to,ins.get(to)+1);const pending=[...nodes].filter(n=>ins.get(n)===0);let seen=0;while(pending.length){const n=pending.shift();seen+=1;for(const[from,to]of edges)if(from===n){const next=ins.get(to)-1;ins.set(to,next);if(next===0)pending.push(to);}}assert(seen===nodes.size,'FUTURE_DAG_CYCLE'); };
const EXPECTED_FUTURE_RETRY = Object.freeze({ordinal:1,predecessorAttemptOrdinal:0,fullCohortTarget:true,newNonce:true,newA:true,newC:true,endpointRestartOrdinal:0,partialReuseAllowed:false,resultReuseAllowed:false,streamReuseAllowed:false,activationAllowed:false,automaticRetryAllowed:false,evidenceReuseAllowed:false});
const EXPECTED_FUTURE_A = Object.freeze({immutable:true,contentAddressed:true,activationAllowed:false,consumptionStateKeyAllowed:false});
const EXPECTED_FUTURE_LIVE_F = Object.freeze({activationAllowed:false,openFlags:'O_NOFOLLOW',fileType:'REGULAR',singleLinkRequired:true,canonicalLogicalPath:'NFC_RELATIVE_NO_EMPTY_DOT_DOTDOT_BACKSLASH_NUL',recordOrder:'UNIQUE_STRICTLY_INCREASING_UTF8_BYTEWISE_LOGICAL_PATH',orderedRecordKeys:['logicalPath','preStat','postStat','byteCount','rawSha256','privateBytes'],statKeys:['dev','ino','mode','nlink','size','mtime','ctime'],prePostIdentityRequired:true,privateBytesRequired:true,rawSha256Required:true,descriptorRetention:'CAPTURE_OWNER_RETAINS_UNTIL_DISPATCH_COMPLETE',noReopenByWorkers:true,descriptorRetainedByK:false});
const EXPECTED_FUTURE_B = Object.freeze({activationAllowed:false,subjectDomain:'shieldkit-labs/p2/gate-b/cohort-policy-authority/v1/b/subject',subjectPreimageOrder:['aRoot','pRoot','rRoot','kPackageRoot'],envelopeDomain:'shieldkit-labs/p2/gate-b/cohort-policy-authority/v1/b/envelope',envelopePreimageOrder:['subjectRoot','liveFRoot'],canonicalization:CANONICALIZATION,frame:'utf8(domain)||0x00||canonical-json-utf8-with-top-level-contentDigest-omitted',privateDescriptorOwnerRequired:true,grantsAuthority:false});
const EXPECTED_FUTURE_C = Object.freeze({exclusiveCreateFlags:'O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC',fileMode:'0600',fsyncFileAndParent:true,crashOrphanConsumesA:true,activationAllowed:false});
const EXPECTED_FUTURE_J = Object.freeze({activationAllowed:false,predecessorOrder:['B','C'],ownerDisposition:'OWNERLESS',evidenceOnly:true,grantsAuthority:false,journalKeyDisposition:'DERIVED_FROM_B_C',dispatchPlanRootRequired:true,journalRootRequired:true});
const EXPECTED_FUTURE_D = Object.freeze({activationAllowed:false,admissionAllowed:false,predecessorOrder:['B','C','J','WORKER_ROWS_ROOT','DISPATCH_PLAN'],workerRowCount:5,kWorkerRowBounds:{minimum:1,maximum:4096,unit:'worker-rows-per-dispatch-plan'},endpointOrder:['native','libauth','bchn','leanbch-primary','leanbch-secondary'],workloadsPerEndpoint:4608,workerRowUniqueBy:['workerId','endpointId'],capturedInputBytesDisposition:'COMPLETE_POSITIVE_PRIVATE_EXTERNAL_VALUE_REQUIRED',abortPrivate:true,abortExecutable:false,crossActivationAllowed:false,recoveryReactivationAllowed:false,rerunPolicy:'NEW_RETRY_Q_A_NONCE_C_FULL_RESTART_NO_REUSE'});
const EXPECTED_ARTIFACT_MAP_CONTRACT = Object.freeze({authorityState:'RAW_ARTIFACT_MAP_AUTHORITY_UNAVAILABLE_EXTERNAL',authorityInstanceCount:0,authorityCreationAllowed:false,authorityExternalOwnerRequired:true,authorityMustPrecedeQRetry:true,authorityResultIndependent:true,authorityContentAddressed:true,instanceState:'RAW_ARTIFACT_MAP_INSTANCE_UNAVAILABLE_EXTERNAL',instanceCount:0,instanceCreationAllowed:false,instanceMustBindAuthorityRoot:true,instanceMustBindDRoot:true,canonicalLogicalPath:'NFC_RELATIVE_NO_EMPTY_DOT_DOTDOT_BACKSLASH_NUL',recordOrder:'UNIQUE_STRICTLY_INCREASING_UTF8_BYTEWISE_LOGICAL_PATH',requiredRecordKeys:['logicalPath','byteCount','rawSha256','artifactClass'],allDeclaredArtifactsRequired:true,exactRawByteCountsRequired:true,exactRawSha256Required:true,partialMapAccepted:false,selfAttestedMapAccepted:false,resultDerivedAuthorityAccepted:false});
const EXPECTED_RESULT_ADMISSION_CONTRACT = Object.freeze({admissionAllowed:false,admissionArtifactExternal:true,admissionArtifactInstanceCount:0,independentValidatorRequired:true,independentValidatorPinnedBeforeResults:true,completeArtifactMapRequired:true,allArtifactsRehashed:true,requiredRawEndpointRows:23040,requiredNormalizedEngineRoleRows:18432,requiredExecutableObligations:18432,requiredPreflightInvalidFixtures:124,requiredPreflightTerminalObligations:496,requiredLegacyTotalObligations:18928,requiredEndpointOrder:['native','libauth','bchn','leanbch-primary','leanbch-secondary'],leanPairJoinRequired:true,leanPairComparisonRoles:1,terminalFailureRateRequired:true,allRequiredMeasurementFieldsRequired:true,partialResultsAccepted:false,estimatedResultsAccepted:false,substitutionAccepted:false,fallbackAccepted:false,reorderedRowsAccepted:false,resultInstanceCount:0,qualificationAllowed:false,rankingAllowed:false,selectionAllowed:false,edges:RESULT_EDGES.map(([from,to])=>({from,to}))});
const assertGrammar = root => { const g=root.futureStateGrammar;assert(g.currentState==='CATALOG_ONLY','FUTURE_STATE');assert(same(g.edges,RETRY_EDGES.map(([from,to])=>({from,to}))),'RETRY_EDGE_ROSTER');assert(same(root.futureResultAdmissionContract.edges,RESULT_EDGES.map(([from,to])=>({from,to}))),'RESULT_EDGE_ROSTER');checkAcyclic([...RETRY_EDGES,...RESULT_EDGES]);assert(same(g.futureRetry,EXPECTED_FUTURE_RETRY),'RETRY_GRAMMAR');assert(same(g.futureA,EXPECTED_FUTURE_A),'A_GRAMMAR');assert(same(g.futureLiveF,EXPECTED_FUTURE_LIVE_F),'LIVE_F_GRAMMAR');assert(same(g.futureB,EXPECTED_FUTURE_B),'B_GRAMMAR');assert(same(g.futureC,EXPECTED_FUTURE_C),'C_GRAMMAR');assert(same(g.futureJ,EXPECTED_FUTURE_J),'J_GRAMMAR');assert(same(g.futureD,EXPECTED_FUTURE_D),'D_GRAMMAR'); };
const assertFutureContracts = root => { assert(same(root.futureArtifactMapContract,EXPECTED_ARTIFACT_MAP_CONTRACT),'ARTIFACT_MAP_CONTRACT');assert(same(root.futureResultAdmissionContract,EXPECTED_RESULT_ADMISSION_CONTRACT),'RESULT_ADMISSION_CONTRACT');assert(same(root.crashRecoveryContract,{beforeCConsumption:false,afterCReuseAllowed:false,partialOutputAdmissible:false,recoveryRequiresFreshRetry:true,activationAllowed:false}),'CRASH_RECOVERY_CONTRACT'); };
const ZERO_COUNTS = Object.freeze(['candidateCount','candidateTupleCount','roleAssignmentCount','parameterAssignmentCount','ownerInstanceCount','providerInstanceCount','factInstanceCount','nonceCount','privateByteCount','workloadRootCount','artifactMapInstanceCount','authorizationCount','claimCount','childProcessCount','runCount','resultCount','evidenceCount','measurementCount']);
const FALSE_GATES = Object.freeze(['executionAllowed','measurementAdmissionAllowed','qualificationAllowed','rankingAllowed','selectionAllowed','fallbackAuthorizationAllowed','attemptCreationAllowed','claimCreationAllowed','providerInstantiationAllowed','artifactMapCreationAllowed','runtimeImportAllowed','endpointImportAllowed']);
const assertBoundary = root => { const b=root.nonAuthorityBoundary;for(const key of ZERO_COUNTS)assert(b[key]===0,`BOUNDARY_ZERO:${key}`);for(const key of FALSE_GATES)assert(b[key]===false,`BOUNDARY_FALSE:${key}`);assert(b.status===root.status&&root.executionAllowed===false&&root.measurementAdmissionAllowed===false,'BOUNDARY_STATUS');assert(same(root.runtimeBoundary,{runtimeEntrypoint:null,runtimeModules:[],runtimeExports:[],activationCapability:null,importEvaluationAllowed:false,buildTimeOnlyLocators:['validate-static.mjs','test/future-boundary.test.mjs','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs']}),'RUNTIME_BOUNDARY'); };
const COMPONENTS = Object.freeze([['parentBinding','parent-binding'],['sourcePins','source-pins'],['historicalDisposition','historical-disposition'],['endpointProjectionContract','endpoint-projection-contract'],['externalRequirements','external-requirements'],['futureStateGrammar','future-state-grammar'],['futureArtifactMapContract','future-artifact-map-contract'],['futureResultAdmissionContract','future-result-admission-contract'],['crashRecoveryContract','crash-recovery-contract'],['nonAuthorityBoundary','nonauthority-boundary']]);
const assertDigests = root => { assert(same(root.componentDigests.map(row=>row.component),COMPONENTS.map(([name])=>name)),'COMPONENT_DIGEST_ROSTER');for(const [component,suffix] of COMPONENTS){const row=root.componentDigests.find(x=>x.component===component);const domain=`${DIGEST_PREFIX}/${suffix}`;assert(row&&same(row.digest,digestRecord(domain,root[component])),`COMPONENT_DIGEST:${component}`);}const copy=Object.fromEntries(Object.entries(root).filter(([key])=>key!=='contentDigest'));assert(same(root.contentDigest,digestRecord(`${DIGEST_PREFIX}/root`,copy)),'ROOT_DIGEST'); };
export const assertRootSemantics = (root, {repositoryRoot=null, sourceFound=null}={}) => { exactKeys(root,ROOT_KEYS,'ROOT_KEYS');assert(root.schema===`${SCHEMA_PREFIX}/root.v1.schema.json`&&root.artifactId==='artifact:gate-b:gate-b0-execution-admission-contract-v1'&&root.packageId===PACKAGE_ID&&root.status==='static-preexecution-prerequisite-catalog-no-authority-no-admission-no-instances'&&root.executionAllowed===false&&root.measurementAdmissionAllowed===false,'ROOT_IDENTITY');assert(root.sourcePins.length===64&&sourceTableDigest(root.sourcePins)===SOURCE_PIN_TABLE_DIGEST,'SOURCE_PIN_LITERAL_TABLE');assertParent(root);if(repositoryRoot)assertP0Freeze(repositoryRoot);assertHistorical(root);assertProjection(root);assertRequirements(root,sourceFound);assertGrammar(root);assertFutureContracts(root);assertBoundary(root);assertDigests(root);return true; };
export const deriveSealEnvelope = packageRoot => { const entries=AUTHORED_FILES.map(locator=>{const bytes=localBytes(packageRoot,locator,`SEAL:${locator}`);return {locator,bytes:bytes.length,rawSha256:sha256(bytes),fileDigest:fileDigestRecord(locator,bytes)};});assert(same(entries.map(x=>x.locator),[...entries.map(x=>x.locator)].sort()),'SEAL_ORDER');const rosterDigest=digestRecord(`${DIGEST_PREFIX}/manifest-roster`,entries);const manifest={schema:`${SCHEMA_PREFIX}/manifest.v1.schema.json`,format:'shieldkit-static-manifest-v1',packageId:PACKAGE_ID,entryCount:AUTHORED_FILES.length,entries,rosterDigest};const manifestBytes=Buffer.from(`${canonicalJson(manifest)}\n`);const rows=[...entries,{locator:'MANIFEST.json',rawSha256:sha256(manifestBytes)}].map(row=>`${row.rawSha256}  ${row.locator}`);return {manifest,manifestBytes,sumsBytes:Buffer.from(`${rows.join('\n')}\n`),entries}; };
const reviewAnchorKeys = Object.freeze(['schema','package','rootRawSha256','rootContentDigest','validatorRawSha256','manifestRawSha256','sha256SumsRawSha256','entryCount','orderedClosure','rosterDigest','parentBinding','sourcePinTableDigest','nonAuthorityBoundary']);
export const deriveReviewAnchor = (packageRoot, envelope, root) => ({schema:`${DIGEST_PREFIX}/external-review-anchor/v1`,package:PACKAGE_LOCATOR,rootRawSha256:sha256(localBytes(packageRoot,'execution-admission-contract-root.v1.json','ANCHOR_ROOT')),rootContentDigest:root.contentDigest,validatorRawSha256:sha256(localBytes(packageRoot,'validate-static.mjs','ANCHOR_VALIDATOR')),manifestRawSha256:sha256(envelope.manifestBytes),sha256SumsRawSha256:sha256(envelope.sumsBytes),entryCount:AUTHORED_FILES.length,orderedClosure:envelope.entries,rosterDigest:envelope.manifest.rosterDigest,parentBinding:root.parentBinding,sourcePinTableDigest:sourceTableDigest(root.sourcePins),nonAuthorityBoundary:root.nonAuthorityBoundary});
const assertAnchor = (anchor, packageRoot, envelope, root) => { exactKeys(anchor,reviewAnchorKeys,'SEALED_ANCHOR_SHAPE');assert(anchor.schema===`${DIGEST_PREFIX}/external-review-anchor/v1`&&anchor.package===PACKAGE_LOCATOR,'SEALED_ANCHOR_IDENTITY');assert(same(anchor.rootContentDigest,root.contentDigest),'SEALED_ANCHOR_ROOT_SEMANTIC');assert(same(anchor.orderedClosure,envelope.entries),'SEALED_ANCHOR_ORDERED_CLOSURE');assert(same(anchor.rosterDigest,envelope.manifest.rosterDigest),'SEALED_ANCHOR_ROSTER');assert(same(anchor,deriveReviewAnchor(packageRoot,envelope,root)),'SEALED_ANCHOR_BINDING'); };
const readReviewAnchor = (pin, packageRoot) => { assert(pin&&typeof pin==='object','SEALED_ANCHOR_REQUIRED');exactKeys(pin,['reviewAnchorRoot','reviewAnchorLocator','reviewAnchorBytes','reviewAnchorRawSha256'],'SEALED_ANCHOR_PIN_SHAPE');assert(isAbsolute(pin.reviewAnchorRoot),'SEALED_ANCHOR_ROOT');const bytes=safeExternalRead(pin.reviewAnchorRoot,pin.reviewAnchorLocator,{bytes:pin.reviewAnchorBytes,rawSha256:pin.reviewAnchorRawSha256},'SEALED_ANCHOR_PIN');const candidate=realpathSync(resolve(pin.reviewAnchorRoot,pin.reviewAnchorLocator));const rel=relative(packageRoot,candidate);assert(rel==='..'||rel.startsWith(`..${process.platform==='win32'?'\\':'/'}`),'SEALED_ANCHOR_INSIDE_PACKAGE');assertNoDuplicateJsonKeys(bytes,'SEALED_ANCHOR_DUPLICATE');let anchor;try{anchor=JSON.parse(bytes);}catch{fail('SEALED_ANCHOR_PARSE');}assert(bytes.toString('utf8')===`${canonicalJson(anchor)}\n`,'SEALED_ANCHOR_CANONICAL');return anchor; };
const assertAnchorIndependent = (anchor, packageRoot) => { exactKeys(anchor,reviewAnchorKeys,'SEALED_ANCHOR_SHAPE');assert(anchor.schema===`${DIGEST_PREFIX}/external-review-anchor/v1`&&anchor.package===PACKAGE_LOCATOR,'SEALED_ANCHOR_IDENTITY');const envelope=deriveSealEnvelope(packageRoot);assert(anchor.entryCount===AUTHORED_FILES.length&&same(anchor.orderedClosure,envelope.entries),'SEALED_ANCHOR_ORDERED_CLOSURE');assert(same(anchor.rosterDigest,envelope.manifest.rosterDigest),'SEALED_ANCHOR_ROSTER');assert(sha256(localBytes(packageRoot,'execution-admission-contract-root.v1.json','SEALED_ANCHOR_ROOT'))===anchor.rootRawSha256,'SEALED_ANCHOR_ROOT_RAW');assert(sha256(localBytes(packageRoot,'validate-static.mjs','SEALED_ANCHOR_VALIDATOR'))===anchor.validatorRawSha256,'SEALED_ANCHOR_VALIDATOR_RAW');const manifestBytes=localBytes(packageRoot,'MANIFEST.json','SEALED_ANCHOR_MANIFEST');const sumsBytes=localBytes(packageRoot,'SHA256SUMS','SEALED_ANCHOR_SUMS');assert(sha256(manifestBytes)===anchor.manifestRawSha256,'SEALED_ANCHOR_MANIFEST_RAW');assert(sha256(sumsBytes)===anchor.sha256SumsRawSha256,'SEALED_ANCHOR_SUMS_RAW');assert(manifestBytes.equals(envelope.manifestBytes),'MANIFEST_RECOMPUTE');assert(sumsBytes.equals(envelope.sumsBytes),'SUMS_RECOMPUTE');assert(same(anchor.parentBinding,PARENT_BINDING),'SEALED_ANCHOR_PARENT');assert(anchor.sourcePinTableDigest===SOURCE_PIN_TABLE_DIGEST,'SEALED_ANCHOR_SOURCE_TABLE'); };
const assertManifest = (packageRoot, ajv) => { const manifest=parseCanonical(packageRoot,'MANIFEST.json','MANIFEST');const validator=ajv.getSchema(`${SCHEMA_PREFIX}/manifest.v1.schema.json`);assert(validator&&validator(manifest),`MANIFEST_SCHEMA:${ajv.errorsText(validator?.errors)}`);const envelope=deriveSealEnvelope(packageRoot);assert(same(manifest,envelope.manifest),'MANIFEST_RECOMPUTE');assert(localBytes(packageRoot,'SHA256SUMS','SUMS').equals(envelope.sumsBytes),'SUMS_RECOMPUTE');return envelope; };
export const validateStatic = ({packageRoot=here,repositoryRoot=resolve(here,'../../../../..'),mode='unsealed',reviewAnchorPin=null}={}) => { assert(mode==='unsealed'||mode==='sealed','MODE');const rootDir=checkPackage(packageRoot,mode);const reviewAnchor=mode==='sealed'?readReviewAnchor(reviewAnchorPin,rootDir):null;if(reviewAnchor)assertAnchorIndependent(reviewAnchor,rootDir);assertSchemaRawPins(rootDir);assertStaticSourceBoundary(rootDir);const schemas=SCHEMA_LOCATORS.map(locator=>parseCanonical(rootDir,locator,`SCHEMA:${locator}`));assertSchemaReachability(schemas);const ajv=new Ajv2020({allErrors:true,strict:true,strictTypes:true});schemas.forEach(schema=>ajv.addSchema(schema));const root=parseCanonical(rootDir,'execution-admission-contract-root.v1.json','ROOT');const rootValidator=ajv.getSchema(root.schema);assert(rootValidator&&rootValidator(root),`ROOT_SCHEMA:${ajv.errorsText(rootValidator?.errors)}`);assertSchemaBindings(root,rootDir);const envelope=mode==='sealed'?assertManifest(rootDir,ajv):null;const found=assertSourcePins(root,repositoryRoot);assertRootSemantics(root,{repositoryRoot,sourceFound:found});if(envelope)assertAnchor(reviewAnchor,rootDir,envelope,root);return {files:mode==='sealed'?SEALED_FILES.length:AUTHORED_FILES.length,sourcePins:found.size,unsealed:mode==='unsealed',rootDigest:root.contentDigest.value}; };
export const parseValidationCliArgs = argv => { assert(Array.isArray(argv)&&argv.every(x=>typeof x==='string'),'CLI_ARGUMENTS');const allowed=['--mode','--review-anchor-root','--review-anchor-locator','--review-anchor-bytes','--review-anchor-raw-sha256'];const values=new Map();for(let i=0;i<argv.length;){const flag=argv[i];assert(allowed.includes(flag),'CLI_UNKNOWN_OR_EXTRA');assert(!values.has(flag),'CLI_DUPLICATE');const value=argv[i+1];assert(typeof value==='string'&&value.length>0&&!value.startsWith('--'),`CLI_VALUE:${flag}`);values.set(flag,value);i+=2;}assert(values.has('--mode'),'CLI_MODE_REQUIRED');const mode=values.get('--mode');assert(mode==='unsealed'||mode==='sealed','CLI_MODE_VALUE');const flags=['--review-anchor-root','--review-anchor-locator','--review-anchor-bytes','--review-anchor-raw-sha256'];if(mode==='unsealed'){assert(flags.every(flag=>!values.has(flag)),'CLI_UNSEALED_ANCHOR');return {mode,reviewAnchorPin:null};}for(const flag of flags)assert(values.has(flag),`CLI_SEALED_REQUIRED:${flag}`);const reviewAnchorRoot=values.get('--review-anchor-root');const reviewAnchorLocator=values.get('--review-anchor-locator');const text=values.get('--review-anchor-bytes');const reviewAnchorRawSha256=values.get('--review-anchor-raw-sha256');assert(isAbsolute(reviewAnchorRoot),'CLI_ANCHOR_ROOT');safeLocator(reviewAnchorLocator,'CLI_ANCHOR_LOCATOR');assert(/^[1-9][0-9]*$/.test(text),'CLI_ANCHOR_BYTES');const reviewAnchorBytes=Number(text);assert(Number.isSafeInteger(reviewAnchorBytes)&&String(reviewAnchorBytes)===text,'CLI_ANCHOR_BYTES');assert(/^[0-9a-f]{64}$/.test(reviewAnchorRawSha256),'CLI_ANCHOR_SHA');return {mode,reviewAnchorPin:{reviewAnchorRoot,reviewAnchorLocator,reviewAnchorBytes,reviewAnchorRawSha256}}; };
if(process.argv[1]===fileURLToPath(import.meta.url)){const options=parseValidationCliArgs(process.argv.slice(2));const result=validateStatic(options);console.log(`PASS Gate B0 execution admission ${options.mode} files=${result.files} pins=${result.sourcePins} root=${result.rootDigest}`);}
