import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { AUTHORED_FILES, SEALED_FILES, parseValidationCliArgs, rawFileDigest, validateStatic } from '../validate-static.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const options = parseValidationCliArgs(process.argv.slice(2));
const kat = JSON.parse(readFileSync(resolve(root, 'test/digest.kat.json')));
for (const row of kat.cases) assert.equal(createHash('sha256').update(row.inputUtf8).digest('hex'), row.sha256);
assert.equal(rawFileDigest(kat.rawFile.locator, Buffer.from(kat.rawFile.inputUtf8)).value, kat.rawFile.sha256);
const sealed = options.mode === 'sealed';
assert.equal(existsSync(resolve(root, 'MANIFEST.json')), sealed);
assert.equal(existsSync(resolve(root, 'SHA256SUMS')), sealed);
const result = validateStatic({ packageRoot: root, repositoryRoot: resolve(root, '../../../../..'), mode: options.mode, reviewAnchorPin: options.reviewAnchorPin });
assert.equal(result.sourcePins, 35);
assert.equal(result.files, sealed ? SEALED_FILES.length : AUTHORED_FILES.length);
assert.equal(result.unsealed, !sealed);
console.log(`PASS static mode=${options.mode} root=${result.rootDigest}`);
