import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { canonicalBytes, digestRecord, omit, validateLiveFailureContainer, validatePackageEnvelope, validateRecoverableCheckpointPrefix } from './validator.mjs';
import { buildFailureFixture, read, write } from './test-support/failure-fixture.mjs';

const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const here = path.dirname(new URL(import.meta.url).pathname);
const checkpointDomain = ordinal => `shieldkit-labs/p2/gate-b/cohort-live-accounting-v2/checkpoint/attempt-001/${ordinal}`;
const manifestDomain = 'shieldkit-labs/p2/gate-b/cohort-live-accounting-v2/checkpoint-manifest/attempt-001';
const rootDomain = 'shieldkit-labs/p2/gate-b/cohort-live-accounting-v2/failure-root/attempt-001';
const authorizationDomain = 'shieldkit-labs/p2/gate-b/cohort-executor-v3/authorization/v3/root';
const claimDomain = 'shieldkit-labs/p2/gate-b/cohort-executor-v3/execution-claim/v3/root';
const bind = (root, relative) => { const bytes = fs.readFileSync(path.join(root, relative)); const value = read(path.join(root, relative)); return { path: relative, rawSha256: sha(bytes), byteLength: bytes.length, contentDigest: value.contentDigest }; };
function redigest(value, domain) { value.contentDigest = digestRecord(domain, omit(value)); return value; }
function reseal(fixture, { rebuildChain = true } = {}) {
  const checkpointDir = path.join(fixture.root, 'checkpoints'); const names = fs.readdirSync(checkpointDir).sort(); let previous = null; const checkpoints = names.map((name, ordinal) => { const file = path.join(checkpointDir, name); const value = read(file); if (rebuildChain) value.previousCheckpointDigest = previous; redigest(value, checkpointDomain(ordinal)); write(file, value); previous = value.contentDigest; return value; });
  const manifestPath = path.join(fixture.root, 'checkpoint-manifest.v2.json'); const manifest = read(manifestPath); manifest.checkpointBindings = checkpoints.map((_, ordinal) => bind(fixture.root, `checkpoints/${String(ordinal).padStart(3, '0')}.checkpoint.v2.json`)); manifest.streamBindings = checkpoints.flatMap(checkpoint => checkpoint.event.capture === null ? [] : checkpoint.event.capture.slots.filter(slot => slot.path !== null).map(slot => ({ endpointOrdinal: checkpoint.event.endpointOrdinal, streamRole: slot.streamRole, path: slot.path, rawSha256: slot.rawSha256, byteLength: slot.byteLength, captureStatus: slot.captureStatus, fsynced: slot.fsynced }))); redigest(manifest, manifestDomain); write(manifestPath, manifest);
  const rootPath = path.join(fixture.root, 'live-failure.v2.json'); if (fs.existsSync(rootPath)) { const root = read(rootPath); root.checkpointManifestBinding = bind(fixture.root, 'checkpoint-manifest.v2.json'); redigest(root, rootDomain); write(rootPath, root); }
}
function refreshCopyBindings(fixture, { refreshClaimAuthorization = false } = {}) {
  const authorizationBinding = bind(fixture.root, 'authorization.copy.json');
  if (refreshClaimAuthorization) { const claimPath = path.join(fixture.root, 'execution-claim.copy.json'); const claim = read(claimPath); claim.authorizationBinding = authorizationBinding; redigest(claim, claimDomain); write(claimPath, claim); }
  const claimBinding = bind(fixture.root, 'execution-claim.copy.json'); const rootPath = path.join(fixture.root, 'live-failure.v2.json'); const root = read(rootPath); root.authorizationCopy = { copyBinding: authorizationBinding, authorityBinding: authorizationBinding }; root.claimCopy = { copyBinding: claimBinding, authorityBinding: claimBinding }; write(rootPath, root);
}
function resealPrefixManifest(fixture) {
  const checkpointDir = path.join(fixture.root, 'checkpoints'); const names = fs.readdirSync(checkpointDir).sort(); let previous = null; const checkpoints = names.map((name, index) => { const file = path.join(checkpointDir, name); const checkpoint = read(file); checkpoint.previousCheckpointDigest = previous; redigest(checkpoint, checkpointDomain(index)); write(file, checkpoint); previous = checkpoint.contentDigest; return { name, checkpoint }; });
  const manifestPath = path.join(fixture.root, 'checkpoint-manifest.v2.json'); const manifest = read(manifestPath); manifest.checkpointBindings = checkpoints.map(({ name }) => bind(fixture.root, `checkpoints/${name}`)); manifest.streamBindings = checkpoints.flatMap(({ checkpoint }) => checkpoint.event.capture === null ? [] : checkpoint.event.capture.slots.filter(slot => slot.path !== null).map(slot => ({ endpointOrdinal: checkpoint.event.endpointOrdinal, streamRole: slot.streamRole, path: slot.path, rawSha256: slot.rawSha256, byteLength: slot.byteLength, captureStatus: slot.captureStatus, fsynced: slot.fsynced }))); redigest(manifest, manifestDomain); write(manifestPath, manifest);
}
function modulePrefix(bytes) { const finalLf = bytes.lastIndexOf(0x0a); const prefix = finalLf < 0 ? Buffer.alloc(0) : bytes.subarray(0, finalLf + 1); const trailing = finalLf < 0 ? bytes : bytes.subarray(finalLf + 1); return { completedRowCount: prefix.length === 0 ? 0 : prefix.toString('utf8').slice(0, -1).split('\n').length, completedLfByteLength: prefix.length, completedLfRawSha256: sha(prefix), trailingFragmentByteLength: trailing.length, trailingFragmentRawSha256: sha(trailing) }; }
function withFixture(options, action) { const fixture = buildFailureFixture(options); try { return action(fixture); } finally { fixture.remove(); } }
function reject(name, mutate) { test(name, () => withFixture({}, fixture => { mutate(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root)); })); }

test('static package envelope is authority-neutral and checksum-bound', () => assert.equal(validatePackageEnvelope(), true));
test('static package envelope rejects an unlisted empty directory', () => { const extra = path.join(here, '.unlisted-empty'); fs.mkdirSync(extra); try { assert.throws(() => validatePackageEnvelope(), /directory closure/); } finally { fs.rmdirSync(extra); } });
for (const [name, options] of [
  ['controller before endpoint builder failure', { phase: 'controller-before-endpoint', failureKind: 'builder' }],
  ['controller before endpoint materializer failure', { phase: 'controller-before-endpoint', failureKind: 'materializer' }],
  ['controller between endpoints validator failure', { phase: 'controller-between-endpoints', failureKind: 'validator', endpointOrdinal: 2 }],
  ['controller after endpoint commit failure', { phase: 'controller-after-endpoint', failureKind: 'commit' }],
  ['controller after endpoint recovery failure', { phase: 'controller-after-endpoint', failureKind: 'recovery' }],
  ['abrupt-before-start selected-not-started boundary', { phase: 'abrupt-before-start', failureKind: 'abrupt-before-start' }],
  ['abrupt module death with recovery-sealed durable prefix', { phase: 'abrupt-module-death', failureKind: 'abrupt-module-death' }],
  ['external partial recovery prefix', { phase: 'endpoint-failure', failureKind: 'external-process', endpointOrdinal: 2 }],
  ['module partial recovery prefix', { phase: 'endpoint-failure', failureKind: 'module-error', endpointOrdinal: 0 }],
]) test(`accepts ${name}`, () => withFixture(options, fixture => { const result = validateLiveFailureContainer(fixture.root); assert.equal(result.status, 'PASS'); assert.equal(result.authorityNeutral, true); assert.equal(result.executionAllowed, false); }));
test('accepts a complete module capture only with an empty trailing fragment', () => withFixture({ phase: 'endpoint-failure', failureKind: 'module-error', endpointOrdinal: 0, moduleComplete: true }, fixture => assert.equal(validateLiveFailureContainer(fixture.root).status, 'PASS')));
test('crash prefix is recoverable but cannot be misrepresented as a sealed failure', () => withFixture({ crashPrefix: true }, fixture => { assert.equal(validateRecoverableCheckpointPrefix(fixture.root).status, 'RECOVERABLE-PREFIX-ONLY'); assert.throws(() => validateLiveFailureContainer(fixture.root), /live-failure|container exact|ENOENT/i); }));
test('accepts a recoverable prefix with only manifest-bound durable capture files', () => withFixture({ crashPrefix: true }, fixture => { const result = validateRecoverableCheckpointPrefix(fixture.root); assert.equal(result.status, 'RECOVERABLE-PREFIX-ONLY'); assert.equal(result.checkpointCount, 1); }));
test('recoverable prefix rejects a symlinked root directory', () => withFixture({ crashPrefix: true }, fixture => { const real = path.join(fixture.parent, 'real-failure'); fs.renameSync(fixture.root, real); fs.symlinkSync(real, fixture.root, 'dir'); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /prefix root directory/); }));
test('recoverable prefix rejects a noncanonical checkpoint identity after manifest reseal', () => withFixture({ crashPrefix: true }, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.checkpointId = 'checkpoint:attempt-001:99'; redigest(checkpoint, checkpointDomain(0)); write(checkpointPath, checkpoint); resealPrefixManifest(fixture); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /prefix checkpoint identity/); }));
test('recoverable prefix rejects a re-bound noncanonical checkpoint path after manifest reseal', () => withFixture({ crashPrefix: true }, fixture => { const source = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const target = path.join(fixture.root, 'checkpoints/099.checkpoint.v2.json'); fs.renameSync(source, target); resealPrefixManifest(fixture); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /prefix checkpoint path\/order/); }));
test('recoverable prefix rejects a re-digested capture pointing at a missing stream', () => withFixture({ crashPrefix: true }, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.capture.slots[1].path = 'streams/missing.bin'; write(checkpointPath, checkpoint); resealPrefixManifest(fixture); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /ENOENT|stream bytes/); }));
test('recoverable prefix rejects a re-digested manifest stream substitution', () => withFixture({ crashPrefix: true }, fixture => { const manifestPath = path.join(fixture.root, 'checkpoint-manifest.v2.json'); const manifest = read(manifestPath); manifest.streamBindings[0].rawSha256 = '0'.repeat(64); redigest(manifest, manifestDomain); write(manifestPath, manifest); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /prefix stream manifest/); }));
test('recoverable prefix rejects an unbound stream file', () => withFixture({ crashPrefix: true }, fixture => { fs.writeFileSync(path.join(fixture.root, 'streams/unbound.bin'), Buffer.from('x')); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /prefix exact file closure/); }));
test('recoverable prefix rejects a symlinked stream namespace entry', () => withFixture({ crashPrefix: true }, fixture => { fs.symlinkSync('/tmp', path.join(fixture.root, 'streams/symlink')); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /symlink namespace/); }));
test('recoverable prefix rejects a hardlinked durable stream', () => withFixture({ crashPrefix: true }, fixture => { const source = path.join(fixture.root, 'streams/02.stdout.bin'); fs.linkSync(source, path.join(fixture.root, 'streams/hardlink.bin')); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /hardlinked/); }));
test('recoverable prefix rejects a durable stream with a non-private mode', () => withFixture({ crashPrefix: true }, fixture => { fs.chmodSync(path.join(fixture.root, 'streams/02.stdout.bin'), 0o644); assert.throws(() => validateRecoverableCheckpointPrefix(fixture.root), /durable private mode/); }));
reject('rejects broken append-only predecessor after all enclosing records are re-digested', fixture => { const file = path.join(fixture.root, 'checkpoints/001.checkpoint.v2.json'); const checkpoint = read(file); checkpoint.previousCheckpointDigest = { ...checkpoint.previousCheckpointDigest, value: '0'.repeat(64) }; write(file, checkpoint); reseal(fixture, { rebuildChain: false }); });
reject('rejects reordered exact five-endpoint order after root re-digest', fixture => { const file = path.join(fixture.root, 'live-failure.v2.json'); const root = read(file); [root.endpointOrder[0], root.endpointOrder[1]] = [root.endpointOrder[1], root.endpointOrder[0]]; write(file, root); reseal(fixture); });
reject('rejects result reuse after root re-digest', fixture => { const file = path.join(fixture.root, 'live-failure.v2.json'); const root = read(file); root.resultReuse = 'forged'; write(file, root); reseal(fixture); });
reject('rejects endpoint reinvocation after root re-digest', fixture => { const file = path.join(fixture.root, 'live-failure.v2.json'); const root = read(file); root.recovery.endpointReinvoked = true; write(file, root); reseal(fixture); });
reject('rejects selected-not-started non-suffix after root re-digest', fixture => { const file = path.join(fixture.root, 'live-failure.v2.json'); const root = read(file); root.selectedNotStarted = [4]; write(file, root); reseal(fixture); });
reject('rejects completed-endpoint non-prefix after root re-digest', fixture => { const file = path.join(fixture.root, 'live-failure.v2.json'); const root = read(file); root.completedEndpointPrefix = [1]; write(file, root); reseal(fixture); });
reject('rejects a stream byte mutation without a matching checkpoint binding', fixture => fs.writeFileSync(path.join(fixture.root, 'streams/02.stdout.bin'), Buffer.from([0x00])));
reject('rejects a re-digested claim whose authorization binding is substituted', fixture => { const claimPath = path.join(fixture.root, 'execution-claim.copy.json'); const claim = read(claimPath); claim.authorizationBinding.contentDigest.value = 'f'.repeat(64); redigest(claim, claimDomain); write(claimPath, claim); refreshCopyBindings(fixture); reseal(fixture); });
reject('rejects extra container file', fixture => fs.writeFileSync(path.join(fixture.root, 'unexpected'), 'x'));
reject('rejects a symlinked stream escape', fixture => fs.symlinkSync('/tmp', path.join(fixture.root, 'stream-link')));
reject('rejects simultaneous controller and endpoint terminal checkpoints after re-digest', fixture => { const file = path.join(fixture.root, 'checkpoints/001.checkpoint.v2.json'); const checkpoint = read(file); checkpoint.event = { phase: 'endpoint', kind: 'external-terminal', endpointOrdinal: 2, endpointId: 'engine:bchn/primary', endpointKind: 'external-process', controllerFailureKind: null, capture: null }; write(file, checkpoint); reseal(fixture); });
test('rejects a module endpoint laundered as an external terminal after a full reseal', () => withFixture({ phase: 'endpoint-failure', failureKind: 'module-error', endpointOrdinal: 0 }, fixture => { const rootPath = path.join(fixture.root, 'live-failure.v2.json'); const root = read(rootPath); root.terminal.failureKind = 'external-process'; write(rootPath, root); const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.kind = 'external-terminal'; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /module endpoint terminal coupling/); }));
test('rejects an external endpoint laundered as a module terminal after a full reseal', () => withFixture({ phase: 'endpoint-failure', failureKind: 'external-process', endpointOrdinal: 2 }, fixture => { const rootPath = path.join(fixture.root, 'live-failure.v2.json'); const root = read(rootPath); root.terminal.failureKind = 'module-error'; write(rootPath, root); const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.kind = 'module-terminal'; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /external endpoint terminal coupling/); }));
test('rejects controller terminal event with endpoint identity after a full reseal', () => withFixture({ phase: 'controller-between-endpoints', failureKind: 'validator', endpointOrdinal: 2 }, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.endpointId = 'engine:bchn/primary'; checkpoint.event.endpointKind = 'external-process'; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /controller endpoint identity absent/); }));
test('rejects a recovery seal with any non-null operational field after a full reseal', () => withFixture({}, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/001.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.endpointId = 'engine:bchn/primary'; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /recovery sealed exact shape/); }));
test('rejects a pre-terminal recovery checkpoint after a full reseal', () => withFixture({}, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event = { phase: 'recovery', kind: 'recovery-sealed', endpointOrdinal: null, endpointId: null, endpointKind: null, controllerFailureKind: null, capture: null }; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /sealed terminal checkpoint index 0/); }));
test('rejects a duplicate recovery checkpoint after a full reseal', () => withFixture({}, fixture => { const source = read(path.join(fixture.root, 'checkpoints/001.checkpoint.v2.json')); source.ordinal = 2; source.checkpointId = 'checkpoint:attempt-001:2'; source.previousCheckpointDigest = null; redigest(source, checkpointDomain(2)); write(path.join(fixture.root, 'checkpoints/002.checkpoint.v2.json'), source); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /sealed chain exact cardinality/); }));
test('rejects an endpoint event with a controller failure kind after a full reseal', () => withFixture({}, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.controllerFailureKind = 'validator'; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /endpoint terminal identity/); }));
test('rejects a controller-between endpoint ordinal zero after a full reseal', () => withFixture({ phase: 'controller-between-endpoints', failureKind: 'validator', endpointOrdinal: 1 }, fixture => { const rootPath = path.join(fixture.root, 'live-failure.v2.json'); const root = read(rootPath); root.terminal.endpointOrdinal = 0; root.completedEndpointPrefix = []; root.selectedNotStarted = [0, 1, 2, 3, 4]; write(rootPath, root); const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); checkpoint.event.endpointOrdinal = 0; write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /between endpoint ordinal/); }));
test('rejects a complete module capture with a trailing fragment after a full reseal', () => withFixture({ phase: 'endpoint-failure', failureKind: 'module-error', endpointOrdinal: 0, moduleComplete: true }, fixture => { const checkpointPath = path.join(fixture.root, 'checkpoints/000.checkpoint.v2.json'); const checkpoint = read(checkpointPath); const stdoutPath = path.join(fixture.root, checkpoint.event.capture.slots[1].path); const bytes = Buffer.concat([fs.readFileSync(stdoutPath), Buffer.from('{"truncated"', 'utf8')]); fs.writeFileSync(stdoutPath, bytes); const stdout = checkpoint.event.capture.slots[1]; stdout.rawSha256 = sha(bytes); stdout.byteLength = bytes.length; checkpoint.event.capture.modulePrefix = modulePrefix(bytes); write(checkpointPath, checkpoint); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /complete module trailing fragment/); }));
test('rejects a correctly redigested authorization copy with an arbitrary domain', () => withFixture({}, fixture => { const authorizationPath = path.join(fixture.root, 'authorization.copy.json'); const authorization = read(authorizationPath); redigest(authorization, 'forged/live-authority/authorization'); write(authorizationPath, authorization); refreshCopyBindings(fixture, { refreshClaimAuthorization: true }); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /authorizationCopy.*contentDigest|authorization copy/i); }));
test('rejects a correctly redigested claim copy with an arbitrary domain', () => withFixture({}, fixture => { const claimPath = path.join(fixture.root, 'execution-claim.copy.json'); const claim = read(claimPath); redigest(claim, 'forged/live-authority/claim'); write(claimPath, claim); refreshCopyBindings(fixture); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /claimCopy.*contentDigest|claim copy/i); }));
test('rejects a correctly redigested authorization copy with an arbitrary schema', () => withFixture({}, fixture => { const authorizationPath = path.join(fixture.root, 'authorization.copy.json'); const authorization = read(authorizationPath); authorization.schema = 'forged/authorization'; redigest(authorization, authorizationDomain); write(authorizationPath, authorization); refreshCopyBindings(fixture, { refreshClaimAuthorization: true }); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /authorization copy schema/); }));
test('rejects a correctly redigested claim copy with an arbitrary schema', () => withFixture({}, fixture => { const claimPath = path.join(fixture.root, 'execution-claim.copy.json'); const claim = read(claimPath); claim.schema = 'forged/claim'; redigest(claim, claimDomain); write(claimPath, claim); refreshCopyBindings(fixture); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /claim copy schema/); }));
test('rejects an extra authorization-copy property after a full copy and root reseal', () => withFixture({}, fixture => { const authorizationPath = path.join(fixture.root, 'authorization.copy.json'); const authorization = read(authorizationPath); authorization.forged = true; redigest(authorization, authorizationDomain); write(authorizationPath, authorization); refreshCopyBindings(fixture, { refreshClaimAuthorization: true }); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /authorization copy strict v3 schema/); }));
test('rejects an extra claim-copy property after a full copy and root reseal', () => withFixture({}, fixture => { const claimPath = path.join(fixture.root, 'execution-claim.copy.json'); const claim = read(claimPath); claim.forged = true; redigest(claim, claimDomain); write(claimPath, claim); refreshCopyBindings(fixture); reseal(fixture); assert.throws(() => validateLiveFailureContainer(fixture.root), /claim copy strict v3 schema/); }));
test('canonical serializer has no authority reads or external execution side effects', () => { const body = canonicalBytes({ b: 1, a: 2 }); assert.equal(body.toString('utf8'), '{\n  "a": 2,\n  "b": 1\n}\n'); });
