/* Static R generator. Only JSON/bytes are read. Freeze stages all new sealed
 * files in a same-parent temporary directory, validates that directory, then
 * publishes with no-replace links. No endpoint, loader, VM, or process runs. */
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  AUTHORITY, AUTH_DOMAIN, CONTENT_DOMAIN, ENDPOINT_ORDER, EXTERNALS, MODULE_WORKERS, ROOT_DOMAIN,
  PACKAGE as CURRENT_PACKAGE, REPO, ROOT, SCHEMA_FILES, SCHEMA_PREFIX, WORKER_FORBIDDEN_KEYS,
  WORKER_KEYS, authorityDigest, buildExternalEndpoint, buildModuleEndpoint, canonicalJson,
  domainDigest, sha256, stable, validateEndpointBinding, validatePackage, validateRSchemaBindings
} from './semantic-validator.mjs';

const PACKAGE = CURRENT_PACKAGE;
const fail = message => { throw new Error(`cohort-runtime-binding-v1: ${message}`); };
const requireCondition = (condition, message) => { if (!condition) fail(message); };
const readBytes = (root, relative) => { const full = path.join(root, relative); const stat = fs.lstatSync(full); requireCondition(stat.isFile() && !stat.isSymbolicLink() && stat.nlink === 1, `regular leaf file ${relative}`); return fs.readFileSync(full); };
const readJson = (root, relative) => JSON.parse(readBytes(root, relative).toString('utf8'));
const canonical = value => canonicalJson(value);
const writeJson = (root, relative, value) => fs.writeFileSync(path.join(root, relative), canonical(value), { mode: 0o644 });
const fileBinding = (root, relative, role = undefined) => { const bytes = readBytes(root, relative); const value = { path: relative, bytes: bytes.length, rawSha256: sha256(bytes), contentDigest: domainDigest(CONTENT_DOMAIN, bytes) }; return role === undefined ? value : { ...value, role }; };
const rawBinding = (root, relative) => { const bytes = readBytes(root, relative); return { path: relative, bytes: bytes.length, rawSha256: sha256(bytes) }; };
const schemaBindings = root => SCHEMA_FILES.map(name => { const relative = `schemas/${name}`; const bytes = readBytes(root, relative); const value = JSON.parse(bytes.toString('utf8')); requireCondition(value.$id === `${SCHEMA_PREFIX}${name}`, `R schema id ${relative}`); return { id: value.$id, path: relative, bytes: bytes.length, rawSha256: sha256(bytes), contentDigest: domainDigest(CONTENT_DOMAIN, bytes) }; });
const roster = manifest => ({ algorithm: 'sha256', domain: manifest.rosterDomain ?? manifest.domainSeparator, frame: 'utf8(domain)||0x00||canonical-json-roster-v1', value: manifest.rosterDigest });
const manifestBinding = (root, relative = 'MANIFEST.json') => fileBinding(root, relative);
const sumsBinding = (root, relative = 'SHA256SUMS') => rawBinding(root, relative);
const leafSchemaBindings = (root, names, packageId) => [...names].sort((a, b) => a.localeCompare(b)).map(relative => { const bytes = readBytes(root, relative); const value = JSON.parse(bytes.toString('utf8')); const id = typeof value.$id === 'string' ? value.$id : `https://shieldkit-labs.local/p2/gate-b/${packageId}/${relative}`; return { id, path: relative, bytes: bytes.length, rawSha256: sha256(bytes), contentDigest: domainDigest(CONTENT_DOMAIN, bytes) }; });
const leafRecord = (root, relative, role) => fileBinding(root, relative, role);

const LEAF_ROOTS = Object.freeze({ N: 'research-lanes/bch-shielded-pool-design/p2/gate-b/cohort-node-runtime-materialized-v1', E: 'research-lanes/bch-shielded-pool-design/p2/gate-b/cohort-endpoint-modules-v1', X: 'research-lanes/bch-shielded-pool-design/p2/gate-b/cohort-engine-runtime-materialized-v1' });
const N_RUNTIME = Object.freeze({ runtimeKind: 'node', identity: { runtime: 'node', version: 'v22.23.1', nodeSha256: '93956de2e59480474a7b46571da1651180b1a050cdf32641ebec4ce6e478e068', loaderSha256: 'd52fe2ff87fff536ed5c5eae8e954cb50655884e4709fedd24cf57f9ec98ad80' }, closure: { dsoCount: 6, imageLaunchQualification: false, semanticQualification: false } });
const X_RUNTIME = Object.freeze({ runtimeKind: 'external', identity: { loaderSha256: 'd52fe2ff87fff536ed5c5eae8e954cb50655884e4709fedd24cf57f9ec98ad80', bchnSha256: '92dce8fbf31fb8dd5d6853aeb16fb6b6ee26bbbce50a4cafc5feeb89d2f72a26', leanVmbconfSha256: '7ffb0aef41ccea6df8b31cb8588cc4cdcb9b6caae8696c37caebec23f3ac1604', costprobeSha256: 'c5847f22da2a057410be91474f7b142716cd18b8e2ba8e6e7b3c1717e4cbbe88' }, closure: { dsoCount: 17, imageLaunchQualification: false, semanticQualification: false, imageWorkdirPolicy: 'provenanceOnly/nonLiveCwd' } });

function packageLeaf(root, id, packageId, rootPath, rootRelative, schemaNames, materializationRelative, recordPaths, runtime, nativeManifest) {
  const manifest = readJson(root, 'MANIFEST.json'); requireCondition(manifest.rosterDigest, `${id} manifest lacks native roster`); const wrapperManifest = manifestBinding(root); if (nativeManifest?.contentDigest) { nativeManifest = { ...nativeManifest }; }
  return { id, packageId, packageRoot: rootPath, root: fileBinding(root, rootRelative), schemaBindings: leafSchemaBindings(root, schemaNames, packageId), manifest: wrapperManifest, nativeManifest, roster: roster(manifest), sums: sumsBinding(root), materialization: fileBinding(root, materializationRelative), records: recordPaths.map(([relative, role]) => leafRecord(root, relative, role)), runtime };
}
function allSchemaNames(root) { const names = []; const visit = current => { for (const entry of fs.readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const full = path.join(current, entry.name); if (entry.isDirectory()) visit(full); else if (entry.name.endsWith('.schema.json')) names.push(path.relative(root, full).split(path.sep).join('/')); } }; visit(root); return names; }
function nodeLeaf() { const root = path.resolve(REPO, LEAF_ROOTS.N); const schemaNames = allSchemaNames(root); const manifest = readJson(root, 'MANIFEST.json'); return packageLeaf(root, 'N', 'cohort-node-runtime-materialized-v1', LEAF_ROOTS.N, 'runtime-image.v1.json', schemaNames, 'materialization.v1.json', [['runtime-image.v1.json', 'runtime-image'], ['source/node-runtime-closure.v1.json', 'runtime-source-closure']], N_RUNTIME, { kind: 'node-runtime-manifest', contentDigest: manifest.contentDigest, rosterDigest: manifest.rosterDigest, rosterDomain: manifest.rosterDomain }); }
function externalLeaf() { const root = path.resolve(REPO, LEAF_ROOTS.X); const schemaPaths = allSchemaNames(root); const manifest = readJson(root, 'MANIFEST.json'); const leaf = packageLeaf(root, 'X', 'cohort-engine-runtime-materialized-v1', LEAF_ROOTS.X, 'runtime-image.v1.json', schemaPaths, 'materialization.v1.json', [['runtime-image.v1.json', 'runtime-image'], ['source/external-runtime-closure.v1.json', 'runtime-source-closure']], X_RUNTIME, { kind: 'external-runtime-manifest', contentField: 'absent', rosterDigest: manifest.rosterDigest }); leaf.roster = { algorithm: 'sha256', domain: 'shieldkit-labs/p2/gate-b/manifest-roster/v1', frame: 'utf8(domain)||0x00||canonical-json-roster-v1', value: manifest.rosterDigest }; return leaf; }
function endpointLeafFromReviewed(bindingPath) { const binding = validateEndpointBinding(bindingPath ? path.resolve(bindingPath) : null); const root = path.resolve(REPO, binding.packageRoot); const native = buildModuleEndpoint(root, 'engine:native'); const libauth = buildModuleEndpoint(root, 'engine:libauth'); const { leafId: _leafId, ...withoutLeafId } = binding; return { leaf: { id: 'E', ...withoutLeafId }, endpoints: [native, libauth] }; }
function endpointUnion(E) { const modules = E.endpoints; const xRoot = path.resolve(REPO, LEAF_ROOTS.X); const bchn = buildExternalEndpoint(xRoot, 'engine:bchn'); const leanPrimary = buildExternalEndpoint(xRoot, 'engine:leanbch:primary'); const leanSecondary = buildExternalEndpoint(xRoot, 'engine:leanbch:secondary'); return { expectedRows: 4608, order: [...ENDPOINT_ORDER], entries: [modules[0], modules[1], bchn, leanPrimary, leanSecondary] }; }
function rootDocument(E, nLeaf, xLeaf) { const root = { artifactId: 'artifact:gate-b:cohort-runtime-binding-v1', contentDigest: null, endpointUnion: endpointUnion(E), executionAllowed: false, packageClosure: { leafCount: 3, leaves: [nLeaf, E.leaf, xLeaf] }, packageId: 'cohort-runtime-binding-v1', runtimeAuthority: { digest: authorityDigest(), common: AUTHORITY.common, module: AUTHORITY.module, external: AUTHORITY.external }, schema: 'shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/root', schemaBindings: schemaBindings(PACKAGE), status: 'static-runtime-binding-materialized-unexecuted', tests: ['tests/static-kat.test.mjs', 'tests/mutation.test.mjs'] }; const without = { ...root }; delete without.contentDigest; root.contentDigest = { algorithm: 'sha256', canonicalization: 'recursive-lexicographic-object-key-sort-arrays-preserve-order-json-utf8-lf-v1', domain: ROOT_DOMAIN, frame: 'utf8(domain)||0x00||canonical-json-utf8-with-contentDigest-omitted', value: domainDigest(ROOT_DOMAIN, without) }; return root; }
function walkForManifest(root) { const files = []; const directories = []; const visit = current => { for (const entry of fs.readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const full = path.join(current, entry.name); const relative = path.relative(root, full).split(path.sep).join('/'); const stat = fs.lstatSync(full); requireCondition(!stat.isSymbolicLink() && (stat.mode & 0o7000) === 0, `R package unsafe ${relative}`); if (entry.isDirectory()) { directories.push({ path: relative, mode: stat.mode & 0o777 }); visit(full); } else { requireCondition(entry.isFile() && stat.nlink === 1, `R package non-regular ${relative}`); if (entry.name !== 'MANIFEST.json' && entry.name !== 'SHA256SUMS') { const bytes = fs.readFileSync(full); files.push({ path: relative, bytes: bytes.length, rawSha256: sha256(bytes), contentDigest: domainDigest(CONTENT_DOMAIN, bytes), mode: stat.mode & 0o777 }); } } } }; visit(root); return { files: files.sort((a, b) => a.path.localeCompare(b.path)), directories: directories.sort((a, b) => a.path.localeCompare(b.path)) }; }
function manifestDocument(walked) { const manifest = { contentDigest: null, directories: walked.directories, directoryCount: walked.directories.length, domainSeparator: CONTENT_DOMAIN, executionAllowed: false, fileCount: walked.files.length, files: walked.files, schema: 'shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/manifest', status: 'static-content-addressed' }; const without = { ...manifest }; delete without.contentDigest; manifest.contentDigest = domainDigest(CONTENT_DOMAIN, without); return manifest; }
function sumsDocument(root, walked) { const names = ['MANIFEST.json', ...walked.files.map(item => item.path)]; return `${names.map(name => `${sha256(fs.readFileSync(path.join(root, name)))}  ${ROOT}/${name}`).join('\n')}\n`; }
function writeStaged(root, E) { writeJson(root, 'runtime-binding-root.v1.json', rootDocument(E, nodeLeaf(), externalLeaf())); const walked = walkForManifest(root); writeJson(root, 'MANIFEST.json', manifestDocument(walked)); fs.writeFileSync(path.join(root, 'SHA256SUMS'), sumsDocument(root, walked), { mode: 0o644 }); }
const STATE_FILE = '.freeze-state.v1.json';
function writeState(value) { const statePath = path.join(PACKAGE, STATE_FILE); const fd = fs.openSync(statePath, 'wx', 0o600); try { fs.writeFileSync(fd, canonical(value)); fs.fsyncSync(fd); } finally { fs.closeSync(fd); } }
function readState() { const statePath = path.join(PACKAGE, STATE_FILE); if (!fs.existsSync(statePath)) return null; const bytes = fs.readFileSync(statePath); requireCondition(bytes.at(-1) === 10 && !bytes.includes(13), 'freeze state canonical LF'); let state; try { state = JSON.parse(bytes.toString('utf8')); } catch (error) { fail(`freeze state JSON: ${error.message}`); } requireCondition(stable(state) === stable({ schema: 'shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/freeze-state', files: ['MANIFEST.json', 'SHA256SUMS', 'runtime-binding-root.v1.json'], stage: state.stage, phase: state.phase }), 'freeze state exact descriptor'); return state; }
function publishNoReplace(staged) { const names = ['MANIFEST.json', 'SHA256SUMS', 'runtime-binding-root.v1.json']; writeState({ schema: 'shieldkit-labs/p2/gate-b/cohort-runtime-binding/v1/freeze-state', files: names, stage: staged, phase: 'validated-stage-pending-publish' }); try { for (const name of names) fs.linkSync(path.join(staged, name), path.join(PACKAGE, name)); fs.unlinkSync(path.join(PACKAGE, STATE_FILE)); } catch (error) { throw error; } }
function parseArgs() { const args = process.argv.slice(2); const mode = args[0]; const index = args.indexOf('--endpoint-binding'); return { mode, endpointBinding: index >= 0 ? args[index + 1] : null }; }
const { mode, endpointBinding } = parseArgs();
if (mode === '--check') { const state = readState(); if (state) { console.log(JSON.stringify({ ok: false, status: 'incomplete-freeze-state; manual recovery required', state })); process.exitCode = 1; } else console.log(JSON.stringify(validatePackage())); }
else if (mode === '--freeze') {
  requireCondition(!fs.existsSync(path.join(PACKAGE, STATE_FILE)), 'incomplete freeze state; manual recovery required'); requireCondition(!fs.existsSync(path.join(PACKAGE, 'runtime-binding-root.v1.json')) && !fs.existsSync(path.join(PACKAGE, 'MANIFEST.json')) && !fs.existsSync(path.join(PACKAGE, 'SHA256SUMS')), 'R already sealed or partially sealed');
  const E = endpointLeafFromReviewed(endpointBinding); const staged = fs.mkdtempSync(path.join(path.dirname(PACKAGE), '.cohort-runtime-binding-v1.stage-')); fs.chmodSync(staged, 0o755); try { for (const entry of fs.readdirSync(PACKAGE, { withFileTypes: true })) { if (entry.name === 'runtime-binding-root.v1.json' || entry.name === 'MANIFEST.json' || entry.name === 'SHA256SUMS') continue; const source = path.join(PACKAGE, entry.name); const destination = path.join(staged, entry.name); if (entry.isDirectory()) fs.cpSync(source, destination, { recursive: true, errorOnExist: true, force: false }); else fs.copyFileSync(source, destination, fs.constants.COPYFILE_EXCL); } writeStaged(staged, E); validatePackage(staged); publishNoReplace(staged); } finally { fs.rmSync(staged, { recursive: true, force: true }); } console.log(JSON.stringify({ ok: true, mode: 'freeze', package: ROOT, expectedRows: 4608, endpoints: 5, leaves: ['N', 'E', 'X'] }));
}
else { console.error('usage: node generate.mjs --check | node generate.mjs --freeze [--endpoint-binding <reviewed-E-binding.json>]'); process.exitCode = 2; }
