/* Execute-only complete-success evidence derivation.
 *
 * It accepts only captured endpoint bytes/outcomes, re-parses those bytes, and
 * derives raw, normalized, cross, manifest, and root records. It never accepts
 * prebuilt raw/normalized/cross payloads and never substitutes corpus expected
 * values for observed engine output.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { EVIDENCE_DOMAINS, ENGINE_ORDER, METRICS, canonicalBytes, canonicalize, digestRecord, evidenceAuthorityRows, instantiateEvidenceDomain, metricValueDigest, omit } from '../cohort-execution-v3/contract.mjs';
import { encodeBchnBatchStdin, encodeLeanCostprobeStdin, encodeLeanVmbconfStdin, encodeLibauthModuleStdin, encodeNativeModuleStdin, parseBchnEffectsTranscript, parseCanonicalNdjsonTranscript, parseLeanAggregateCorroboration, parseLeanCostprobeAuthority } from '../cohort-execution-v3/adapters.mjs';
import { deriveVerifiedFixtureRows } from '../cohort-execution-v3/fixtures.mjs';
import { successPayloadPaths } from './evidence-validator.mjs';

const sha = body => crypto.createHash('sha256').update(body).digest('hex');
const assert = (condition, message) => { if (!condition) throw new Error(`cohort-executor-v3 evidence builder: ${message}`); };
const domain = (template, values) => instantiateEvidenceDomain(template, values);
const bytes = value => canonicalBytes(value);
const value = record => record?.value ?? record;
const here = path.dirname(new URL(import.meta.url).pathname);

function lineSpans(body) { const result = []; let start = 0; for (let index = 0; index < body.length; index += 1) if (body[index] === 0x0a) { result.push([start, index + 1]); start = index + 1; } assert(start === body.length, 'stdout must end LF'); return result; }
function entry(item, ordinal, body) { const core = { ordinal, ...item, rawSha256: sha(body), byteLength: body.length }; return { ...core, manifestEntryDigest: digestRecord(core, `shieldkit-labs/p2/gate-b/execution-evidence/v3/manifest/entry/${item.path}`) }; }
function readyRows(verified, engineId) { const rows = verified.byEngine[engineId].filter(row => !row.preflightLimitViolation); assert(rows.length === 4608, `${engineId} ready cardinality`); return rows; }
function expectedStdin(engineId, role, rows) { if (engineId === 'engine:native') return encodeNativeModuleStdin(rows); if (engineId === 'engine:libauth') return encodeLibauthModuleStdin(rows); if (engineId === 'engine:bchn') return encodeBchnBatchStdin(rows); return role === 'primary' ? encodeLeanVmbconfStdin(rows) : encodeLeanCostprobeStdin(rows); }
function capturedEndpoint(captured, engineId, role, endpoint) {
  const item = captured?.[engineId]?.[role]; assert(item && Buffer.isBuffer(item.stdin) && Buffer.isBuffer(item.stdout) && Buffer.isBuffer(item.stderr) && item.outcome && typeof item.outcome === 'object', `captured endpoint ${engineId}/${role}`);
  const outcome = item.outcome;
  if (endpoint.endpointKind === 'module-ndjson') assert(outcome.exitCode === null && outcome.signal === null && outcome.timedOut === false && outcome.parserStatus === 'complete' && outcome.captureClosed === true, `module complete endpoint ${engineId}/${role}`);
  else assert(outcome.exitCode === 0 && outcome.signal === null && outcome.timedOut === false && outcome.parserStatus === 'complete' && outcome.captureClosed === true && item.stdout.length + item.stderr.length <= 134217728, `external complete endpoint ${engineId}/${role}`);
  return item;
}
function engineMetric(engineId, metricId, payload) {
  const values = payload?.metrics; if (!values || typeof values !== 'object') return undefined;
  const fields = {
    'engine:native': {},
    'engine:libauth': { vmCost: ['vmCost', 'operationCost'], opCost: ['opCost', 'operationCost'], stackMax: ['stackMax'], elementMax: ['elementMax'], opcodeHistogram: ['opcodeHistogram'], mulByteProduct: ['mulByteProduct'], divByteProduct: ['divByteProduct'], modByteProduct: ['modByteProduct'], resultPushBytes: ['resultPushBytes'], limits: ['limits'], headroom: ['headroom'] },
    'engine:bchn': { vmCost: ['operationCost'], opCost: ['operationCost'], limits: ['maximumOperationCost'], headroom: ['maximumOperationCost'] },
    'engine:leanbch': { vmCost: ['arithmeticCost'], opCost: ['nativeConsensus64OperationCost'], limits: ['limits'], headroom: ['headroom'] },
  }[engineId]; const key = (fields[metricId] ?? []).find(candidate => Object.hasOwn(values, candidate));
  if (!key) return undefined;
  if (engineId === 'engine:bchn' && metricId === 'limits') return { operationCost: values.maximumOperationCost, hashDigestIterations: values.maximumHashDigestIterations, signatureChecks: values.maximumSignatureCheckCount };
  if (engineId === 'engine:bchn' && metricId === 'headroom') return { operationCost: values.maximumOperationCost - values.operationCost, hashDigestIterations: values.maximumHashDigestIterations - values.hashDigestIterations, signatureChecks: values.maximumSignatureCheckCount - values.signatureCheckCount };
  return values[key];
}
function metric({ engineId, batch, raw, row, fixture, metricId }) {
  if (row.disposition === 'preflight-limit-unsupported') {
    const output = { metricId, status: 'preflight-limit-unsupported', value: null, provenance: null, reason: 'preflight-limit-unsupported', comparable: false };
    output.contentDigest = digestRecord(omit(output), domain(EVIDENCE_DOMAINS.metricCell, { engineId, batchOrdinal: batch, workItemId: row.workItemId, metricId })); return output;
  }
  const common = { lockingBytes: fixture.byteBindings.sourceLockingBytecode.byteLength, unlockingBytes: fixture.byteBindings.unlockingBytecode.byteLength, sourceBytes: fixture.byteBindings.sourceOutputs.byteLength };
  let output;
  if (metricId === 'verdict') output = { metricId, status: 'measured', value: row.rawObservation.payload.verdict, provenance: { sourceArtifactDigest: raw.contentDigest.value, method: 'raw-observation-verdict-v3' }, reason: null, comparable: true };
  else if (Object.hasOwn(common, metricId)) output = { metricId, status: 'derived-common', value: common[metricId], provenance: { sourceArtifactDigest: fixture.contentDigest.value, method: 'frozen-fixture-byte-binding-v1' }, reason: null, comparable: true };
  else {
    const observed = engineMetric(engineId, metricId, row.rawObservation.payload);
    output = observed === undefined ? { metricId, status: 'not-exposed', value: null, provenance: null, reason: 'not-exposed-by-engine', comparable: false } : { metricId, status: 'measured-noncomparable', value: observed, provenance: { sourceArtifactDigest: raw.contentDigest.value, method: 'raw-engine-metric-v3' }, reason: null, comparable: false };
  }
  output.contentDigest = digestRecord(omit(output), domain(EVIDENCE_DOMAINS.metricCell, { engineId, batchOrdinal: batch, workItemId: row.workItemId, metricId })); return output;
}
function sourcePayload(engineId, parsed) { return engineId === 'engine:leanbch' ? { workItemId: parsed.workItemId, verdict: parsed.verdict, failureStage: parsed.verdict === 'accept' ? 'accept' : null, metrics: parsed.metrics, txChecks: 'unsupported', phase: 'costprobe', terminalStatus: 'observed' } : parsed; }
function statusFromCells(cells, preflight) { if (preflight) return 'preflight-unsupported'; if (cells.some(cell => cell.terminalStatus === 'engine-unsupported-incomplete')) return 'not-comparable'; if (cells.some(cell => cell.terminalStatus !== 'observed')) return 'incomplete'; if (!cells.every(cell => cell.comparable)) return 'not-comparable'; return new Set(cells.map(cell => cell.observedVerdict)).size === 1 ? 'agree' : 'disagree'; }

/**
 * Build all 24 non-transport payload bytes from exact captured bytes. This is
 * deliberately complete-success only: a process/parser/capture failure never
 * falls through to a partially normalized result and must use the sealed
 * failure publisher once that separate integration is present.
 */
export function deriveCompleteSuccessPayloadBytes({ authorization, authorizationBytes, claim, claimBytes, captured }) {
  assert(Buffer.isBuffer(authorizationBytes) && Buffer.isBuffer(claimBytes) && authorization?.attempt?.index === 1 && claim?.attemptIndex === 1, 'authenticated transport buffers');
  const authority = evidenceAuthorityRows(); const verified = deriveVerifiedFixtureRows(); const bodies = new Map(); const payloads = successPayloadPaths(); const streams = new Map();
  for (const [batch, engineId] of ENGINE_ORDER.entries()) {
    const endpoints = authorization.endpoints.filter(endpoint => endpoint.engineId === engineId); const ready = readyRows(verified, engineId);
    for (const endpoint of endpoints) {
      const capturedItem = capturedEndpoint(captured, engineId, endpoint.endpointRole, endpoint); const stdin = expectedStdin(engineId, endpoint.endpointRole, ready);
      assert(capturedItem.stdin.equals(stdin), `captured stdin codec/order ${engineId}/${endpoint.endpointRole}`);
      for (const role of ['stdin', 'stdout', 'stderr']) {
        const relative = `raw/${engineId}/${endpoint.endpointRole}-${role}.bin`; const body = capturedItem[role]; assert(Buffer.isBuffer(body), `captured ${role} bytes`); bodies.set(relative, body); streams.set(`${engineId}/${endpoint.endpointRole}/${role}`, { endpoint, body, relative, outcome: capturedItem.outcome });
      }
    }
  }
  const streamEntries = new Map(payloads.map((item, ordinal) => [item.path, item.kind === 'raw-stream' ? entry(item, ordinal, bodies.get(item.path)) : null]).filter(([, value]) => value !== null));
  const raws = [];
  for (const [batch, engineId] of ENGINE_ORDER.entries()) {
    const all = authority.byEngine.get(engineId); const ready = readyRows(verified, engineId); const endpointAuth = authorization.endpoints.filter(endpoint => endpoint.engineId === engineId); const parserRole = engineId === 'engine:leanbch' ? 'secondary' : 'primary'; const parser = streams.get(`${engineId}/${parserRole}/stdout`); const parserText = new TextDecoder('utf-8', { fatal: true }).decode(parser.body); assert(!parserText.includes('\r'), `${engineId} parser CR`);
    const parsed = engineId === 'engine:native' || engineId === 'engine:libauth' ? parseCanonicalNdjsonTranscript(parser.body, { rows: ready, engineId }) : engineId === 'engine:bchn' ? parseBchnEffectsTranscript(parser.body, { rows: ready }) : parseLeanCostprobeAuthority(parserText, { rows: ready });
    assert(parsed.size === 4608, `${engineId} parsed ready cardinality`); const spans = lineSpans(parser.body); const offset = engineId === 'engine:leanbch' ? 1 : 0; if (offset) assert(parserText.startsWith('ORACLE reject\n'), 'Lean CostProbe header'); assert(spans.length === 4608 + offset, `${engineId} stdout lines`);
    if (engineId === 'engine:leanbch') {
      const primary = streams.get(`${engineId}/primary/stdout`); const aggregate = parseLeanAggregateCorroboration(new TextDecoder('utf-8', { fatal: true }).decode(primary.body), { rows: ready }); let rejectedValid = 0; let acceptedInvalid = 0;
      for (const row of ready) { const observed = parsed.get(row.workItem.workItemId); assert(observed.status === 'observed-script-engine-only', `Lean SKIP cannot form complete success ${row.workItem.workItemId}`); if (observed.verdict === 'reject' && row.expected.verdict === 'accept') rejectedValid += 1; if (observed.verdict === 'accept' && row.expected.verdict === 'reject') acceptedInvalid += 1; }
      assert(aggregate.rejectedValid === rejectedValid && aggregate.acceptedInvalid === acceptedInvalid, 'Lean aggregate/costprobe mismatch');
    }
    const endpoints = endpointAuth.map(endpoint => {
      const stream = role => { const item = streams.get(`${engineId}/${endpoint.endpointRole}/${role}`); const manifest = streamEntries.get(item.relative); return { path: item.relative, rawSha256: sha(item.body), byteLength: item.body.length, mediaType: role === 'stdout' ? 'text/plain-utf8' : 'application/octet-stream', manifestPath: 'evidence-manifest.v3.json', manifestEntryDigest: manifest.manifestEntryDigest }; };
      const outcome = streams.get(`${engineId}/${endpoint.endpointRole}/stdout`).outcome;
      return { role: endpoint.endpointRole, endpointKind: endpoint.endpointKind, path: endpoint.invocation.entrypointBinding.path, rawSha256: endpoint.invocation.entrypointBinding.rawSha256, argv: endpoint.invocation.argv, cwd: endpoint.invocation.cwd, environment: endpoint.invocation.environment, runtime: endpoint.invocation.runtime, stdin: stream('stdin'), stdout: stream('stdout'), stderr: stream('stderr'), exitCode: endpoint.endpointKind === 'module-ndjson' ? null : outcome.exitCode, signal: outcome.signal, timedOut: outcome.timedOut, parserStatus: outcome.parserStatus, captureClosed: outcome.captureClosed };
    });
    let readyOrdinal = 0;
    const rows = all.map((work, ordinal) => {
      const fixture = authority.fixtureRoster.records[ordinal]; const limit = Boolean(fixture.preflightLimitViolation?.scriptSig || fixture.preflightLimitViolation?.redeem);
      if (limit) { const row = { workItemId: work.workItemId, fixtureKey: fixture.fixtureKey, terminalCellId: work.terminalCellId, workItemOrdinal: ordinal, fixtureRecordDigest: fixture.contentDigest.value, disposition: 'preflight-limit-unsupported', preflightBinding: { kind: 'preflight-limit', executionCeilingBytes: 10000, scriptSig: Boolean(fixture.preflightLimitViolation?.scriptSig), redeem: Boolean(fixture.preflightLimitViolation?.redeem), reason: 'preflight-limit-unsupported-no-engine-invocation' }, unsupportedBinding: null, notRunBinding: null, rawObservation: null }; row.rawRowDigest = digestRecord(omit(row, 'rawRowDigest'), domain(EVIDENCE_DOMAINS.rawRow, { engineId, batchOrdinal: batch, workItemId: row.workItemId })); return row; }
      const observed = parsed.get(work.workItemId); assert(observed && observed.status !== 'engine-unsupported-incomplete', `complete observed row ${work.workItemId}`); const [byteStart, byteEnd] = spans[offset + readyOrdinal]; const sourceStream = { path: parser.relative, artifactRawSha256: sha(parser.body), artifactByteLength: parser.body.length, byteStart, byteEnd, lineStart: offset + readyOrdinal + 1, lineEnd: offset + readyOrdinal + 1, spanSha256: sha(parser.body.subarray(byteStart, byteEnd)), manifestPath: 'evidence-manifest.v3.json', manifestEntryDigest: streamEntries.get(parser.relative).manifestEntryDigest }; readyOrdinal += 1;
      const payload = { ...sourcePayload(engineId, observed), sourceStream }; const observation = { kind: 'structured', status: 'observed', rawObservationDigest: null, endpointRole: parserRole, exitCode: 0, parserStatus: 'complete', payload }; observation.rawObservationDigest = digestRecord(omit(observation, 'rawObservationDigest'), domain(EVIDENCE_DOMAINS.rawObservation, { engineId, batchOrdinal: batch, workItemId: work.workItemId })); const row = { workItemId: work.workItemId, fixtureKey: fixture.fixtureKey, terminalCellId: work.terminalCellId, workItemOrdinal: ordinal, fixtureRecordDigest: fixture.contentDigest.value, disposition: 'observed', preflightBinding: null, unsupportedBinding: null, notRunBinding: null, rawObservation: observation }; row.rawRowDigest = digestRecord(omit(row, 'rawRowDigest'), domain(EVIDENCE_DOMAINS.rawRow, { engineId, batchOrdinal: batch, workItemId: row.workItemId })); return row;
    });
    assert(readyOrdinal === 4608, `${engineId} ready row consumption`);
    const raw = { schema: 'shieldkit-labs/p2/gate-b/cohort-executor-v3/raw-engine-observation/v3', evidenceId: 'evidence:execution-epoch-gate-b-v2:attempt-001', epochId: 'execution-epoch:gate-b-v2', attemptIndex: 1, engineId, engineBatchOrdinal: batch, shardIndex: 0, shardCount: 1, status: 'complete', workItemOrderDigest: digestRecord(all.map(row => row.workItemId), `shieldkit-labs/p2/gate-b/execution-contract/v3/schedule/${engineId}`), engineBinding: { engineId, ...endpointAuth[0].invocation.engineBinding }, invocation: { entrypointKind: engineId === 'engine:leanbch' ? 'paired' : endpointAuth[0].endpointKind === 'module-ndjson' ? 'module' : 'external', entrypoints: endpoints, stdinCodecs: endpointAuth.map(endpoint => endpoint.invocation.stdinCodec), implementationDigest: endpointAuth[0].invocation.implementationDigest }, lifecycle: { status: 'complete', endpoints: endpoints.map(endpoint => ({ role: endpoint.role, status: 'complete', exitCode: endpoint.exitCode, signal: endpoint.signal, timedOut: endpoint.timedOut, parserStatus: endpoint.parserStatus, captureClosed: endpoint.captureClosed })) }, rows };
    raw.contentDigest = digestRecord(omit(raw), domain(EVIDENCE_DOMAINS.rawArtifact, { engineId, batchOrdinal: batch })); raws.push(raw); bodies.set(`raw/${engineId}/raw-engine-observation.v3.json`, bytes(raw));
  }
  const normals = raws.map((raw, batch) => {
    const engineId = raw.engineId; const all = authority.byEngine.get(engineId); const rows = raw.rows.map((rawRow, ordinal) => { const fixture = authority.fixtureRoster.records[ordinal]; const expected = authority.cases.get(fixture.epochIdentity.caseKey).expected; const metrics = METRICS.map(metricId => metric({ engineId, batch, raw, row: rawRow, fixture, metricId })); const preflight = rawRow.disposition === 'preflight-limit-unsupported'; const row = { workItemId: rawRow.workItemId, fixtureKey: rawRow.fixtureKey, terminalCellId: rawRow.terminalCellId, workItemOrdinal: ordinal, fixtureRecordDigest: rawRow.fixtureRecordDigest, disposition: rawRow.disposition, expected, terminalStatus: preflight ? 'preflight-limit-unsupported' : 'observed', observed: preflight ? { verdict: null, failureStage: 'preflight-limit' } : { verdict: rawRow.rawObservation.payload.verdict, failureStage: rawRow.rawObservation.payload.failureStage }, rawObservationDigest: preflight ? null : rawRow.rawRowDigest, unsupportedBinding: null, notRunBinding: null, metrics }; row.contentDigest = digestRecord(omit(row), domain(EVIDENCE_DOMAINS.normalizedRow, { engineId, batchOrdinal: batch, workItemId: row.workItemId })); return row; }); const normal = { schema: 'shieldkit-labs/p2/gate-b/cohort-executor-v3/normalized-engine-result/v3', evidenceId: 'evidence:execution-epoch-gate-b-v2:attempt-001', epochId: 'execution-epoch:gate-b-v2', attemptIndex: 1, engineId, engineBatchOrdinal: batch, shardIndex: 0, shardCount: 1, status: 'complete', workItemOrderDigest: raw.workItemOrderDigest, rawArtifactDigest: raw.contentDigest.value, rows, metricCellCount: 70980 }; normal.contentDigest = digestRecord(omit(normal), domain(EVIDENCE_DOMAINS.normalizedArtifact, { engineId, batchOrdinal: batch })); bodies.set(`normalized/${engineId}/normalized-engine-result.v3.json`, bytes(normal)); return normal; });
  const fixtureRows = []; const metricAgreementRows = [];
  for (let ordinal = 0; ordinal < 4732; ordinal += 1) {
    const fixture = authority.fixtureRoster.records[ordinal]; const expected = authority.cases.get(fixture.epochIdentity.caseKey).expected; const preflight = Boolean(fixture.preflightLimitViolation?.scriptSig || fixture.preflightLimitViolation?.redeem); const cells = ENGINE_ORDER.map((engineId, batch) => { const raw = raws[batch].rows[ordinal]; const normal = normals[batch].rows[ordinal]; return { engineId, workItemId: normal.workItemId, terminalCellId: normal.terminalCellId, terminalStatus: normal.terminalStatus, observedVerdict: normal.observed.verdict, comparable: !preflight && normal.terminalStatus === 'observed', rawRowDigest: raw.rawRowDigest.value, normalizedRowDigest: normal.contentDigest.value }; }); const fixtureRow = { fixtureKey: fixture.fixtureKey, terminalCellId: cells[0].terminalCellId, fixtureRecordDigest: fixture.contentDigest.value, expectedVerdict: expected.verdict, engines: cells, agreementStatus: statusFromCells(cells, preflight) }; fixtureRow.contentDigest = digestRecord(omit(fixtureRow), domain(EVIDENCE_DOMAINS.summaryFixture, { fixtureKey: fixture.fixtureKey })); fixtureRows.push(fixtureRow);
    for (let metricOrdinal = 0; metricOrdinal < METRICS.length; metricOrdinal += 1) { const metricId = METRICS[metricOrdinal]; const metricCells = ENGINE_ORDER.map((engineId, batch) => { const raw = raws[batch].rows[ordinal]; const normal = normals[batch].rows[ordinal]; const metricValue = normal.metrics[metricOrdinal]; return { engineId, workItemId: normal.workItemId, terminalCellId: normal.terminalCellId, rawRowDigest: raw.rawRowDigest.value, normalizedRowDigest: normal.contentDigest.value, metricCellDigest: metricValue.contentDigest.value, status: metricValue.status, valueDigest: metricValue.comparable ? metricValueDigest(metricValue) : null, comparable: metricValue.comparable }; }); const comparable = metricCells.filter(cell => cell.comparable).map(cell => cell.engineId); const metricRow = { fixtureKey: fixture.fixtureKey, metricOrdinal, metricId, cells: metricCells, agreementStatus: preflight ? 'preflight-unsupported' : comparable.length === 4 ? new Set(metricCells.map(cell => cell.valueDigest)).size === 1 ? 'agree' : 'disagree' : 'not-comparable', comparableEngineIds: comparable, incomparableEngineIds: ENGINE_ORDER.filter(engineId => !comparable.includes(engineId)), valueDigests: metricCells.map(cell => cell.valueDigest) }; metricRow.contentDigest = digestRecord(omit(metricRow), domain(EVIDENCE_DOMAINS.summaryMetric, { fixtureKey: fixture.fixtureKey, metricId })); metricAgreementRows.push(metricRow); }
  }
  const cross = { schema: 'shieldkit-labs/p2/gate-b/cohort-executor-v3/cross-engine-summary/v3', evidenceId: 'evidence:execution-epoch-gate-b-v2:attempt-001', epochId: 'execution-epoch:gate-b-v2', attemptIndex: 1, status: 'complete', rawArtifactDigests: raws.map(raw => raw.contentDigest.value), normalizedArtifactDigests: normals.map(normal => normal.contentDigest.value), fixtureRows, metricAgreementRows, verdictAgreement: fixtureRows.some(row => row.agreementStatus === 'disagree') ? 'disagreement' : 'complete-eligible-only', metricCoverageAgreement: metricAgreementRows.some(row => row.agreementStatus === 'disagree') ? 'disagreement' : 'complete-eligible-only', ranking: null, selection: null }; cross.contentDigest = digestRecord(omit(cross), EVIDENCE_DOMAINS.summary); bodies.set('cross-engine-summary.v3.json', bytes(cross));
  const manifestFiles = payloads.map((item, ordinal) => entry(item, ordinal, item.path === 'authorization.json' ? authorizationBytes : item.path === 'execution-claim.json' ? claimBytes : bodies.get(item.path))); const manifest = { schema: 'shieldkit-labs/p2/gate-b/cohort-executor-v3/evidence-manifest/v3', manifestId: 'evidence-manifest:cohort-executor-v3:attempt-001', status: 'complete', attemptIndex: 1, evidenceRootExcluded: true, selfManifestExcluded: true, files: manifestFiles, inventoryDigest: digestRecord(manifestFiles, 'shieldkit-labs/p2/gate-b/execution-evidence/v3/manifest/inventory') }; manifest.contentDigest = digestRecord(omit(manifest), 'shieldkit-labs/p2/gate-b/execution-evidence/v3/manifest/root'); bodies.set('evidence-manifest.v3.json', bytes(manifest));
  const artifactBinding = (engineId, batch, root) => { const relative = `${root}/${engineId}/${root === 'raw' ? 'raw-engine-observation.v3.json' : 'normalized-engine-result.v3.json'}`; const artifact = root === 'raw' ? raws[batch] : normals[batch]; const body = bodies.get(relative); return { engineId, batchOrdinal: batch, shardIndex: 0, shardCount: 1, path: relative, rawSha256: sha(body), byteLength: body.length, contentDigest: artifact.contentDigest.value, status: artifact.status }; };
  const root = { schema: 'shieldkit-labs/p2/gate-b/cohort-executor-v3/evidence-root/v3', evidenceId: 'evidence:execution-epoch-gate-b-v2:attempt-001', epochId: 'execution-epoch:gate-b-v2', attemptIndex: 1, status: 'complete', componentAndScriptEngineOnly: true, bchnTxChecks: 'unsupported', contractBinding: authorization.contractBinding, manifestBinding: { path: 'evidence-manifest.v3.json', schemaPath: 'research-lanes/bch-shielded-pool-design/p2/gate-b/cohort-executor-v3/evidence-manifest.v3.schema.json', rawSha256: sha(bodies.get('evidence-manifest.v3.json')), schemaSha256: sha(fs.readFileSync(path.join(here, 'evidence-manifest.v3.schema.json'))), contentDigest: manifest.contentDigest.value, inventoryDigest: manifest.inventoryDigest.value, listedPayloadCount: 26, selfManifestExcluded: true, evidenceRootExcluded: true }, authorizationCopy: { path: 'authorization.json', rawSha256: sha(authorizationBytes), byteLength: authorizationBytes.length, contentDigest: authorization.contentDigest }, claimCopy: { path: 'execution-claim.json', rawSha256: sha(claimBytes), byteLength: claimBytes.length, contentDigest: claim.contentDigest }, rawArtifacts: ENGINE_ORDER.map((id, batch) => artifactBinding(id, batch, 'raw')), normalizedArtifacts: ENGINE_ORDER.map((id, batch) => artifactBinding(id, batch, 'normalized')), crossSummary: { path: 'cross-engine-summary.v3.json', rawSha256: sha(bodies.get('cross-engine-summary.v3.json')), byteLength: bodies.get('cross-engine-summary.v3.json').length, contentDigest: cross.contentDigest.value, status: cross.status }, obligationAccounting: { total: 18928, preflightUnsupported: 496, executable: 18432, metricCells: 283920 }, ranking: null, selection: null }; root.contentDigest = digestRecord(omit(root), 'shieldkit-labs/p2/gate-b/execution-evidence/v3/root'); bodies.set('evidence-root.v3.json', bytes(root));
  const payloadBytes = new Map([...bodies].filter(([relative]) => !['authorization.json', 'execution-claim.json'].includes(relative))); assert(payloadBytes.size === 26, 'complete non-transport container cardinality'); return Object.freeze({ payloadBytes, raws: Object.freeze(raws), normalized: Object.freeze(normals), cross: Object.freeze(cross), manifest: Object.freeze(manifest), root: Object.freeze(root) });
}
