import test from 'node:test';
import assert from 'node:assert/strict';
import Ajv2020 from 'ajv/dist/2020.js';
import { createHash } from 'node:crypto';
import { chmodSync, cpSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateStatic } from '../validate-static.mjs';

const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const packageParent=dirname(packageRoot);
const AUTHORED_FILES=Object.freeze(['COMMAND.txt','README.md','external-authority-control-plane-schema-bridge-root.v1.json','schemas/artifact-dependency-dag.v1.schema.json','schemas/b0-execution-authorization.v1.schema.json','schemas/binding-creation-authorization-g0.v1.schema.json','schemas/control-plane-transition.v2.schema.json','schemas/dependency-binding.v1.schema.json','schemas/digest.v1.schema.json','schemas/external-authority-contract.v2.schema.json','schemas/governance-authorization-g1.v1.schema.json','schemas/instance-creation-event.v1.schema.json','schemas/issuer-decision.v1.schema.json','schemas/manifest.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/principal-identity-ref.v1.schema.json','schemas/provider-binding-catalog.v1.schema.json','schemas/provider-binding.v2.schema.json','schemas/provider-contract.v1.schema.json','schemas/root.v1.schema.json','schemas/source-collision-decision.v2.schema.json','test/digest.kat.json','test/future-schema.test.mjs','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs','validate-static.mjs']);
const canonicalJson=value=>Array.isArray(value)?`[${value.map(canonicalJson).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`:JSON.stringify(value);
const writeCanonical=(root,locator,value)=>writeFileSync(resolve(root,locator),`${canonicalJson(value)}\n`);
const readJson=(root,locator)=>JSON.parse(readFileSync(resolve(root,locator),'utf8'));
const ROOT_FILE='external-authority-control-plane-schema-bridge-root.v1.json';
const PREFIX='shieldkit-labs/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge/v1';
const SCHEMA_PREFIX='https://shieldkit-labs.local/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge/v1/';
const ROOT_ORACLE=`${canonicalJson(readJson(packageRoot,ROOT_FILE))}\n`;
const sourceBytes=Object.freeze(Object.fromEntries(AUTHORED_FILES.map(locator=>[locator,readFileSync(resolve(packageRoot,locator))])));
const copySource=target=>{mkdirSync(target,{recursive:true});chmodSync(target,0o755);for(const locator of AUTHORED_FILES){const destination=resolve(target,locator);mkdirSync(dirname(destination),{recursive:true});cpSync(resolve(packageRoot,locator),destination);}};
const assertCloneBaseline=clone=>{for(const locator of AUTHORED_FILES)assert.equal(readFileSync(resolve(clone,locator)).equals(sourceBytes[locator]),true,`H1 baseline drift ${locator}`);assert.equal(readFileSync(resolve(clone,ROOT_FILE),'utf8'),ROOT_ORACLE,'H1 root oracle');};
const withClone=async run=>{const clone=mkdtempSync(resolve(packageParent,'.cpsb-mutation-'));copySource(clone);try{assertCloneBaseline(clone);return await run(clone);}finally{rmSync(clone,{recursive:true,force:true});}};
const setAt=(value,path,replacement)=>{let cursor=value;for(const part of path.slice(0,-1))cursor=cursor[part];cursor[path.at(-1)]=replacement;};
const expectCpsb=(expected,run)=>assert.throws(run,error=>error?.message===expected);
const make=(partition,scope,rows,expected)=>rows.map((row,index)=>Object.freeze({mutationId:`${partition}-${String(index+1).padStart(2,'0')}`,partition,scope,expected,...row}));
const aPaths=Object.freeze([
  ['schema'],['artifactId'],['packageId'],['status'],['purpose'],['executionAllowed'],['measurementAdmissionAllowed'],['eappV1Disposition','recordInstantiationAllowed'],['eappV1Disposition','selectedDag'],['runtimeBoundary','activationCapability'],['runtimeBoundary','runtimeEntrypoint'],['runtimeBoundary','runtimeModules'],['runtimeBoundary','runtimeExports'],['runtimeBoundary','childProcessAllowed'],['runtimeBoundary','endpointImportAllowed'],['runtimeBoundary','importEvaluationAllowed'],['runtimeBoundary','ioAllowed'],['nonAuthorityBoundary','admissionAllowed'],['nonAuthorityBoundary','executionAllowed'],['nonAuthorityBoundary','instanceCreationAllowed'],['nonAuthorityBoundary','packageMaySelfAuthorize'],['nonAuthorityBoundary','principalAuthenticationAllowed'],['nonAuthorityBoundary','providerBindingCreationAllowed'],['nonAuthorityBoundary','qualificationAllowed'],['nonAuthorityBoundary','sourceCollisionSelectionAllowed'],['nonAuthorityBoundary','principalCount'],['nonAuthorityBoundary','decisionCount'],['nonAuthorityBoundary','externalAuthorityContractCount'],['nonAuthorityBoundary','providerContractCount'],['nonAuthorityBoundary','providerBindingCount'],['nonAuthorityBoundary','authorizationCount'],['nonAuthorityBoundary','instanceCount']
]);
const schemaFiles=Object.freeze(AUTHORED_FILES.filter(locator=>locator.startsWith('schemas/')));
const bRows=Object.freeze(Array.from({length:11},(_,index)=>[
  {index,kind:'reorder'},
  {index,kind:index%2===0?'schemaId':'definitionPointer'},
  {index,kind:index%2===0?'recordCount':'creationAllowed'},
  {index,kind:'requiredKeys'},
]).flat());
const cRows=Object.freeze(['status','currentState','automaticTransitionAllowed','downgradeAllowed','selectedDag','authorizedTransitions','representedFrom','representedTo','representedDisposition','rotateStates','swapStates','rotateEdges','edgeSelfFrom','edgeSelfTo','edgeStatus','edgeArtifact'].map(kind=>({kind})));
const dRows=Object.freeze([
  {kind:'deleteNode',nodeId:'CONTROL_PLANE_SCHEMA_BRIDGE'},{kind:'deleteEdge',from:'PINNED_STATIC_FOUNDATION',to:'CONTROL_PLANE_SCHEMA_BRIDGE'},{kind:'reverseEdge',from:'PINNED_STATIC_FOUNDATION',to:'CONTROL_PLANE_SCHEMA_BRIDGE'},{kind:'reverseEdge',from:'EXTERNAL_AUTHORITY_CONTRACT_CORE_SET',to:'EXTERNAL_AUTHORITY_CONTRACT_ISSUER_DECISION_SET'},{kind:'reverseEdge',from:'EXTERNAL_PROVIDER_CONTRACT_CORE_SET',to:'EXTERNAL_PROVIDER_CONTRACT_ISSUER_DECISION_SET'},{kind:'reverseEdge',from:'SOURCE_COLLISION_DECISION_CORE',to:'SOURCE_COLLISION_ISSUER_DECISION'},{kind:'retargetEdge',from:'EXTERNAL_AUTHORITY_CONTRACT_CORE_SET',to:'EXTERNAL_AUTHORITY_CONTRACT_ISSUER_DECISION_SET',newTo:'EXTERNAL_AUTHORITY_CONTRACT_SET'},{kind:'retargetEdge',from:'EXTERNAL_PROVIDER_CONTRACT_CORE_SET',to:'EXTERNAL_PROVIDER_CONTRACT_ISSUER_DECISION_SET',newTo:'EXTERNAL_PROVIDER_CONTRACT_SET'},{kind:'retargetEdge',from:'SOURCE_COLLISION_DECISION_CORE',to:'SOURCE_COLLISION_ISSUER_DECISION',newTo:'SOURCE_COLLISION_DECISION'},{kind:'retargetIndex',index:27,newTo:'ROOT_SOL_BINDING_CREATION_AUTHORIZATION_G0'},{kind:'retargetIndex',index:43,newTo:'PROVIDER_BINDING_CATALOG'},{kind:'retargetIndex',index:52,newTo:'ROOT_SOL_GOVERNANCE_AUTHORIZATION_G1'},{kind:'retargetIndex',index:63,newTo:'B0_EXECUTION_AUTHORIZATION'},{kind:'retargetIndex',index:70,newTo:'INSTANCE_CREATION_EVENT'},{kind:'reverseEdge',from:'B0_EXECUTION_AUTHORIZATION_ISSUER_DECISION',to:'B0_EXECUTION_AUTHORIZATION'},{kind:'reverseEdge',from:'INSTANCE_CREATION_ISSUER_DECISION',to:'INSTANCE_CREATION_EVENT'}
]);
const eRows=Object.freeze([
  {path:['dependencyBinding','directParent','root','rawSha256'],kind:'flip64'},
  {path:['dependencyBinding','directParent','root','bytes'],kind:'increment'},
  {path:['dependencyBinding','directParent','root','contentDigest'],kind:'flip64'},
  {path:['dependencyBinding','directParent','authorityDisposition'],kind:'append'},
  {path:['eappV1Disposition','parentManifestRawSha256'],kind:'flip64'},
  {path:['eappV1Disposition','parentChecksumsRawSha256'],kind:'flip64'},
  {path:['eappV1Disposition','selectedDag'],kind:'uopc'},
  {path:['dependencyBinding','sourceLanguageAuthority','root','rawSha256'],kind:'flip64'},
  {path:['dependencyBinding','sourceLanguageAuthority','root','bytes'],kind:'increment'},
  {path:['dependencyBinding','sourceLanguageAuthority','root','contentDigest'],kind:'flip64'},
  {path:['dependencyBinding','sourceRoots',0,'rawSha256'],kind:'flip64'},
  {path:['dependencyBinding','sourceRoots',2,'contentDigest'],kind:'flip64'},
]);
const fRows=Object.freeze([
  {kind:'bindingRaw'},{kind:'bindingId'},{kind:'bindingPointer'},{kind:'bindingOrder'},
  {kind:'unusedDef',locator:'schemas/digest.v1.schema.json'},{kind:'extraProperty',locator:'schemas/principal-identity-ref.v1.schema.json'},{kind:'recursiveRef',locator:'schemas/digest.v1.schema.json'},{kind:'widenExecution',locator:'schemas/root.v1.schema.json'},
]);
const cases=Object.freeze([
  ...make('A','root-and-governance',aPaths.map(path=>({path})),'CPSB_ROOT_SCHEMA'),
  ...make('B','future-record-descriptors',bRows.map((row,index)=>{const id=`B-${String(index+1).padStart(2,'0')}`,entry=readJson(packageRoot,ROOT_FILE).futureRecordContracts.entries[row.index];return {...row,expected:row.kind==='schemaId'?`CPSB_SCHEMA_REF:${SCHEMA_PREFIX}missing-${id}.schema.json${entry.definitionPointer}`:row.kind==='definitionPointer'?`CPSB_SCHEMA_REF:${entry.schemaId}#/$defs/missing_${id.replaceAll('-','_')}`:'CPSB_ROOT_SCHEMA'};}),'CPSB_ROOT_SCHEMA'),
  ...make('C','control-plane-transition',cRows,'CPSB_ROOT_SCHEMA'),
  ...make('D','artifact-dag-causal-order',dRows,'CPSB_ROOT_SCHEMA'),
  ...make('E','dependency-and-parent-pins',eRows,'CPSB_ROOT_SCHEMA'),
  ...make('F','schema-binding-and-grammar',fRows.map((row,index)=>({...row,expected:index===0||index===3||index>=4?'CPSB_SCHEMA_RAW':'CPSB_ROOT_SCHEMA'})),'CPSB_ROOT_SCHEMA')
]);
const rewriteRoot=(clone,edit)=>{const root=readJson(clone,ROOT_FILE);edit(root);writeCanonical(clone,ROOT_FILE,root);};
const changedLocator=fixture=>fixture.partition==='F'&&fixture.locator?fixture.locator:ROOT_FILE;
const leafDiffCount=(left,right)=>{if(Object.is(left,right))return 0;if(!left||!right||typeof left!=='object'||typeof right!=='object'||Array.isArray(left)!==Array.isArray(right))return 1;const keys=[...new Set([...Object.keys(left),...Object.keys(right)])];return keys.reduce((count,key)=>count+leafDiffCount(left[key],right[key]),0);};
const assertOnePrimaryMutation=(clone,before,fixture)=>{const changed=changedLocator(fixture);for(const locator of AUTHORED_FILES)if(locator!==changed)assert.equal(readFileSync(resolve(clone,locator)).equals(before[locator]),true,`A0 non-primary drift ${fixture.mutationId}:${locator}`);assert.notEqual(readFileSync(resolve(clone,changed),'utf8'),before[changed].toString('utf8'),`A0 primary mutation ${fixture.mutationId}`);};
const mutate=({partition,mutationId,...row},clone)=>{
  if(partition==='A'){rewriteRoot(clone,root=>{const current=row.path.reduce((value,key)=>value[key],root),replacement=typeof current==='string'?`${current}:${mutationId}`:current===false?true:current===0?1:current===null?mutationId:Array.isArray(current)?[mutationId]:mutationId;setAt(root,row.path,replacement);});return;}
  if(partition==='B'){rewriteRoot(clone,root=>{const entries=root.futureRecordContracts.entries,entry=entries[row.index];if(row.kind==='reorder'){const [moved]=entries.splice(row.index,1);entries.splice((row.index+1)%11,0,moved);}else if(row.kind==='schemaId')entry.schemaId=`${SCHEMA_PREFIX}missing-${mutationId}.schema.json`;else if(row.kind==='definitionPointer')entry.definitionPointer=`#/$defs/missing_${mutationId.replaceAll('-','_')}`;else if(row.kind==='recordCount')entry.recordCount=1;else if(row.kind==='creationAllowed')entry.creationAllowed=true;else entry.requiredKeys=[...entry.requiredKeys.slice(1),entry.requiredKeys[0]];});return;}
  if(partition==='C'){rewriteRoot(clone,root=>{const value=root.controlPlaneTransition,rotate=array=>array.push(array.shift());if(row.kind==='status')value.status+=`:${mutationId}`;else if(row.kind==='currentState')value.currentState=value.states[0];else if(row.kind==='automaticTransitionAllowed')value.automaticTransitionAllowed=true;else if(row.kind==='downgradeAllowed')value.downgradeAllowed=true;else if(row.kind==='selectedDag')value.selectedDag='UOPC';else if(row.kind==='authorizedTransitions')value.authorizedTransitions=[structuredClone(value.edges[1])];else if(row.kind==='representedFrom')value.representedTransition.from=value.states[1];else if(row.kind==='representedTo')value.representedTransition.to=value.states[2];else if(row.kind==='representedDisposition')value.representedTransition.disposition+=`:${mutationId}`;else if(row.kind==='rotateStates')rotate(value.states);else if(row.kind==='swapStates')[value.states[1],value.states[2]]=[value.states[2],value.states[1]];else if(row.kind==='rotateEdges')rotate(value.edges);else if(row.kind==='edgeSelfFrom')value.edges[0].from=value.edges[0].to;else if(row.kind==='edgeSelfTo')value.edges[0].to=value.edges[0].from;else if(row.kind==='edgeStatus')value.edges[1].authorizationStatus=value.edges[0].authorizationStatus;else value.edges[1].requiredAuthorityArtifact=value.edges[0].requiredAuthorityArtifact;});return;}
  if(partition==='D'){rewriteRoot(clone,root=>{const dag=root.artifactDependencyDag,edge=row.index===undefined?dag.edges.find(value=>value.from===row.from&&value.to===row.to):dag.edges[row.index];if(row.kind==='deleteNode')dag.nodes.splice(dag.nodes.findIndex(value=>value.nodeId===row.nodeId),1);else if(row.kind==='deleteEdge')dag.edges.splice(dag.edges.indexOf(edge),1);else if(row.kind==='reverseEdge')[edge.from,edge.to]=[edge.to,edge.from];else edge.to=row.newTo;});return;}
  if(partition==='E'){rewriteRoot(clone,root=>{const current=row.path.reduce((value,key)=>value[key],root);setAt(root,row.path,row.kind==='flip64'?(current[0]==='0'?'1':'0')+current.slice(1):row.kind==='increment'?current+1:row.kind==='append'?`${current}:${mutationId}`:'UOPC');});return;}
  if(row.kind==='bindingRaw'||row.kind==='bindingId'||row.kind==='bindingPointer'||row.kind==='bindingOrder'){rewriteRoot(clone,root=>{if(row.kind==='bindingRaw')root.schemaBindings[0].rawSha256=(root.schemaBindings[0].rawSha256[0]==='0'?'1':'0')+root.schemaBindings[0].rawSha256.slice(1);else if(row.kind==='bindingId')root.schemaBindings[0].schemaId=`${SCHEMA_PREFIX}missing-binding-${mutationId}.schema.json`;else if(row.kind==='bindingPointer')root.schemaBindings[0].rootJsonPointers=['/artifactDependencyDag/edges'];else [root.schemaBindings[0],root.schemaBindings[1]]=[root.schemaBindings[1],root.schemaBindings[0]];});return;}
  const schema=readJson(clone,row.locator);if(row.kind==='unusedDef')schema.$defs.__cpsb_unused={type:'null'};else if(row.kind==='extraProperty')schema.$defs.principalIdentityRef.properties.cpsbExtraProbe={type:'string'};else if(row.kind==='recursiveRef')schema.$recursiveRef='#/$defs/digestRecord';else schema.$defs.root.properties.executionAllowed={anyOf:[{const:false},{const:true}]};writeCanonical(clone,row.locator,schema);
};

/* H1 is deliberately independent of validate-static. Each case is either an
 * exact source restoration or a noncanonical structural/Ajv counterfactual;
 * it is not production semantic acceptance or authority. H1 never writes a
 * production envelope or review anchor. */
const equalJson=(left,right)=>canonicalJson(left)===canonicalJson(right);
const getAt=(value,path)=>path.reduce((cursor,part)=>cursor[part],value);
const constPath=(schema,path)=>{const parent=getAt(schema,path.slice(0,-1)),key=path.at(-1);assert.ok(Object.hasOwn(parent,key),`H1 const path ${path.join('.')}`);return [parent,key];};
const assertRepairChange=(before,after,id,label)=>{assert.equal(equalJson(before,after),false,`${id}: H1 ${label} changes`);};
const patchExactConsts=(root,locator,patches,id)=>{const schema=readJson(root,locator);for(const {path,before,after,label} of patches){const [parent,key]=constPath(schema,path);assert.equal(equalJson(parent[key],before),true,`${id}: H1 ${label??path.join('.')} pre-repair`);assertRepairChange(before,after,id,label??path.join('.'));parent[key]=structuredClone(after);}writeCanonical(root,locator,schema);const repaired=readJson(root,locator);for(const {path,after,label} of patches)assert.equal(equalJson(getAt(repaired,path),after),true,`${id}: H1 ${label??path.join('.')} changed`);return locator;};
const patchExactConst=(root,locator,path,before,after,id)=>patchExactConsts(root,locator,[{path,before,after}],id);
const replaceOrderedPrefixItem=(root,locator,path,from,to,id)=>{assertRepairChange(from,to,id,'ordered prefix');const schema=readJson(root,locator),items=getAt(schema,path);assert.ok(Array.isArray(items),`${id}: H1 ordered prefix exists`);assert.equal(equalJson(items,from),true,`${id}: H1 ordered-const pre-repair`);items.splice(0,items.length,...structuredClone(to));writeCanonical(root,locator,schema);assert.equal(equalJson(getAt(readJson(root,locator),path),to),true,`${id}: H1 ordered prefix changed`);return locator;};
const H1_ROOT_DEF=['$defs','root','properties'];
const descriptorSchemaLocator=(before,index,id)=>{const entry=before.futureRecordContracts.entries[index],binding=before.schemaBindings.find(row=>row.schemaId===entry.schemaId);assert.ok(binding,`${id}: H1 descriptor schema binding exists`);assert.ok(schemaFiles.includes(binding.locator),`${id}: H1 descriptor schema locator`);return binding.locator;};
const assertPrefixDescriptorRefs=(schema,entries,id)=>{const prefix=getAt(schema,['$defs','futureRecordContracts','properties','entries','prefixItems']);assert.equal(prefix.length,entries.length,`${id}: H1 descriptor prefix cardinality`);for(const [index,entry] of entries.entries()){const ref=getAt(prefix,[index,'allOf',1,'$ref']);assert.equal(ref,`${entry.schemaId}${entry.definitionPointer}`,`${id}: H1 descriptor ref ${index}`);}return prefix;};
const patchSelectedDescriptorContract=(root,index,field,before,after,id)=>{assert.equal(['recordCount','creationAllowed'].includes(field),true,`${id}: H1 selected descriptor field`);assertRepairChange(before,after,id,`selected ${field}`);const schema=readJson(root,ROOT_SCHEMA),sharedPath=['$defs','futureRecordContractDescriptor'],shared=getAt(schema,sharedPath),fieldPath=['properties',field,'const'],sharedRef={$ref:'#/$defs/futureRecordContractDescriptor'},prefixPath=['$defs','futureRecordContracts','properties','entries','prefixItems'],prefixBefore=structuredClone(getAt(schema,prefixPath)),selectedPath=[...prefixPath,index,'allOf',0];assert.equal(equalJson(getAt(shared,fieldPath),before),true,`${id}: H1 shared ${field} pre-repair`);assert.equal(equalJson(getAt(schema,selectedPath),sharedRef),true,`${id}: H1 selected shared descriptor ref pre-repair`);const selected=structuredClone(shared);setAt(selected,fieldPath,structuredClone(after));setAt(schema,selectedPath,selected);writeCanonical(root,ROOT_SCHEMA,schema);const repaired=readJson(root,ROOT_SCHEMA);assert.equal(equalJson(getAt(repaired,sharedPath),shared),true,`${id}: H1 shared descriptor retained exactly`);assert.equal(equalJson(getAt(repaired,selectedPath),selected),true,`${id}: H1 selected descriptor overlay exact`);assert.equal(equalJson(getAt(repaired,[...selectedPath,...fieldPath]),after),true,`${id}: H1 selected ${field} changed`);const prefix=getAt(repaired,prefixPath);for(const [row,item] of prefix.entries())if(row!==index){assert.equal(equalJson(item,prefixBefore[row]),true,`${id}: H1 unrelated descriptor row ${row} retained exactly`);assert.equal(equalJson(getAt(item,['allOf',0]),sharedRef),true,`${id}: H1 unrelated descriptor ref ${row} retained`);}return ROOT_SCHEMA;};
const repairDescriptorReorder=(root,before,after,id,index)=>{const descriptorPath=['$defs','futureRecordContracts','properties','entries','prefixItems'],schemaBindingPath=['$defs','root','properties','schemaBindings','prefixItems'],schema=readJson(root,ROOT_SCHEMA),descriptorItems=assertPrefixDescriptorRefs(schema,before.futureRecordContracts.entries,id),repairedItems=[...descriptorItems],[moved]=repairedItems.splice(index,1);repairedItems.splice((index+1)%11,0,moved);assertPrefixDescriptorRefs({$defs:{futureRecordContracts:{properties:{entries:{prefixItems:repairedItems}}}}},after.futureRecordContracts.entries,id);const document=readJson(root,ROOT_FILE),bindingItems=getAt(schema,schemaBindingPath),changed=[];for(const [entryIndex,entry] of after.futureRecordContracts.entries.entries()){const bindingIndex=document.schemaBindings.findIndex(row=>row.schemaId===entry.schemaId);assert.notEqual(bindingIndex,-1,`${id}: H1 reordered descriptor binding ${entry.recordKind}`);const binding=document.schemaBindings[bindingIndex],expectedPointer=[`/futureRecordContracts/entries/${entryIndex}`];if(!equalJson(binding.rootJsonPointers,expectedPointer)){const bindingSchemaPointer=getAt(bindingItems,[bindingIndex,'allOf',1,'properties','rootJsonPointers']);assert.equal(equalJson(bindingSchemaPointer.const,binding.rootJsonPointers),true,`${id}: H1 binding pointer pre-repair ${entry.recordKind}`);binding.rootJsonPointers=expectedPointer;bindingSchemaPointer.const=structuredClone(expectedPointer);changed.push(entry.recordKind);}}assert.equal(changed.length,index===10?11:2,`${id}: H1 reordered binding pointer cardinality`);getAt(schema,descriptorPath).splice(0,descriptorItems.length,...structuredClone(repairedItems));writeCanonical(root,ROOT_SCHEMA,schema);writeCanonical(root,ROOT_FILE,document);assertPrefixDescriptorRefs(readJson(root,ROOT_SCHEMA),after.futureRecordContracts.entries,id);return [ROOT_FILE,ROOT_SCHEMA];};
const repairDagDeletion=(root,before,fixture)=>{const id=fixture.mutationId,document=readJson(root,ROOT_FILE),dag=document.artifactDependencyDag,original=before.artifactDependencyDag;
  if(fixture.kind==='deleteNode'){const removed=original.nodes.find(node=>node.nodeId===fixture.nodeId);assert.ok(removed,`${id}: H1 deleted node existed`);assert.equal(dag.nodes.some(node=>node.nodeId===fixture.nodeId),false,`${id}: H1 deleted node absent`);const dependent=original.edges.filter(edge=>edge.from===fixture.nodeId||edge.to===fixture.nodeId);assert.ok(dependent.length>0,`${id}: H1 dependent edges exist`);assert.equal(equalJson(dag.edges,original.edges),true,`${id}: H1 node mutation retained edges before repair`);dag.edges=dag.edges.filter(edge=>edge.from!==fixture.nodeId&&edge.to!==fixture.nodeId);assert.equal(dag.edges.some(edge=>edge.from===fixture.nodeId||edge.to===fixture.nodeId),false,`${id}: H1 dependent edges removed`);}
  else {assert.equal(dag.edges.length,original.edges.length-1,`${id}: H1 deleted edge absent`);}
  const previousNodeCount=dag.nodeCount,previousEdgeCount=dag.edgeCount;dag.nodeCount=dag.nodes.length;dag.edgeCount=dag.edges.length;if(fixture.kind==='deleteNode')assertRepairChange(previousNodeCount,dag.nodeCount,id,'nodeCount aggregate');assertRepairChange(previousEdgeCount,dag.edgeCount,id,'edgeCount aggregate');writeCanonical(root,ROOT_FILE,document);return document;
};
const h1CoherentRepair=(fixture,root,before,after)=>{
  const id=fixture.mutationId;
  if(fixture.partition==='A'){
    const head=fixture.path[0],tail=fixture.path.slice(1);
    if(head==='runtimeBoundary'||head==='nonAuthorityBoundary')return [patchExactConst(root,'schemas/non-authority-boundary.v1.schema.json',['$defs',head,'properties',tail[0],'const'],getAt(before,fixture.path),getAt(after,fixture.path),id)];
    if(head==='eappV1Disposition')return [patchExactConst(root,ROOT_SCHEMA,['$defs','eappV1Disposition','properties',tail[0],'const'],getAt(before,fixture.path),getAt(after,fixture.path),id)];
    return [patchExactConst(root,ROOT_SCHEMA,[...H1_ROOT_DEF,head,'const'],getAt(before,fixture.path),getAt(after,fixture.path),id)];
  }
  if(fixture.partition==='B'){
    const path=['$defs','futureRecordContracts','properties','entries','prefixItems'];
    if(fixture.kind==='reorder')return repairDescriptorReorder(root,before,after,id,fixture.index);
    const rootSchema=readJson(root,ROOT_SCHEMA),prefix=assertPrefixDescriptorRefs(rootSchema,before.futureRecordContracts.entries,id),descriptorRef=getAt(prefix,[fixture.index,'allOf',1,'$ref']),field=fixture.kind==='requiredKeys'?'requiredKeys':fixture.kind,entryPath=['futureRecordContracts','entries',fixture.index,field],descriptorLocator=descriptorSchemaLocator(before,fixture.index,id),descriptorPath=['$defs','recordContractDescriptor','properties',field,'const'],rootPatches=[],descriptorPatches=[{path:descriptorPath,before:getAt(before,entryPath),after:getAt(after,entryPath),label:`descriptor ${field}`}];
    if(field==='requiredKeys'){const definitionName=before.futureRecordContracts.entries[fixture.index].definitionPointer.split('/').at(-1);descriptorPatches.push({path:['$defs',definitionName,'required'],before:getAt(before,entryPath),after:getAt(after,entryPath),label:'record required order'});}
    const descriptor=patchExactConsts(root,descriptorLocator,descriptorPatches,id);
    if(['schemaId','definitionPointer','requiredKeys'].includes(field))rootPatches.push({path:[...path,fixture.index,'allOf',2,'properties',field,'const'],before:getAt(before,entryPath),after:getAt(after,entryPath),label:`prefix ${field}`});
    const rootSchemaRepair=['recordCount','creationAllowed'].includes(field)?patchSelectedDescriptorContract(root,fixture.index,field,getAt(before,entryPath),getAt(after,entryPath),id):(assert.ok(rootPatches.length>0,`${id}: H1 active root constraint exists`),patchExactConsts(root,ROOT_SCHEMA,rootPatches,id));assert.equal(getAt(readJson(root,ROOT_SCHEMA),['$defs','futureRecordContracts','properties','entries','prefixItems',fixture.index,'allOf',1,'$ref']),descriptorRef,`${id}: H1 descriptor ref retained`);return [descriptor,rootSchemaRepair];
  }
  if(fixture.partition==='C'){
    const base=['$defs','controlPlaneTransition','properties'];
    if(['edgeSelfFrom','edgeSelfTo','edgeStatus','edgeArtifact','rotateEdges'].includes(fixture.kind))return [patchExactConst(root,'schemas/control-plane-transition.v2.schema.json',[...base,'edges','const'],before.controlPlaneTransition.edges,after.controlPlaneTransition.edges,id)];
    if(['representedFrom','representedTo','representedDisposition'].includes(fixture.kind)){const field=fixture.kind==='representedFrom'?'from':fixture.kind==='representedTo'?'to':'disposition';return [patchExactConst(root,'schemas/control-plane-transition.v2.schema.json',['$defs','representedTransition','properties',field,'const'],before.controlPlaneTransition.representedTransition[field],after.controlPlaneTransition.representedTransition[field],id)];}
    const field=fixture.kind==='rotateStates'||fixture.kind==='swapStates'?'states':fixture.kind;
    return [patchExactConst(root,'schemas/control-plane-transition.v2.schema.json',[...base,field,'const'],before.controlPlaneTransition[field],after.controlPlaneTransition[field],id)];
  }
  if(fixture.partition==='D'){
    if(['deleteNode','deleteEdge'].includes(fixture.kind)){const repaired=repairDagDeletion(root,before,fixture),properties=['$defs','artifactDependencyDag','properties'],patches=[];
      if(fixture.kind==='deleteNode')patches.push({path:[...properties,'nodes','const'],before:before.artifactDependencyDag.nodes,after:repaired.artifactDependencyDag.nodes,label:'nodes exact aggregate'},{path:[...properties,'nodeCount','const'],before:before.artifactDependencyDag.nodeCount,after:repaired.artifactDependencyDag.nodeCount,label:'nodeCount exact aggregate'},{path:[...properties,'nodes','minItems'],before:before.artifactDependencyDag.nodes.length,after:repaired.artifactDependencyDag.nodes.length,label:'nodes minItems'},{path:[...properties,'nodes','maxItems'],before:before.artifactDependencyDag.nodes.length,after:repaired.artifactDependencyDag.nodes.length,label:'nodes maxItems'});
      patches.push({path:[...properties,'edges','const'],before:before.artifactDependencyDag.edges,after:repaired.artifactDependencyDag.edges,label:'edges exact aggregate'},{path:[...properties,'edgeCount','const'],before:before.artifactDependencyDag.edgeCount,after:repaired.artifactDependencyDag.edgeCount,label:'edgeCount exact aggregate'},{path:[...properties,'edges','minItems'],before:before.artifactDependencyDag.edges.length,after:repaired.artifactDependencyDag.edges.length,label:'edges minItems'},{path:[...properties,'edges','maxItems'],before:before.artifactDependencyDag.edges.length,after:repaired.artifactDependencyDag.edges.length,label:'edges maxItems'});return [ROOT_FILE,patchExactConsts(root,'schemas/artifact-dependency-dag.v1.schema.json',patches,id)];}
    return [patchExactConst(root,'schemas/artifact-dependency-dag.v1.schema.json',['$defs','artifactDependencyDag','properties','edges','const'],before.artifactDependencyDag.edges,after.artifactDependencyDag.edges,id)];
  }
  if(fixture.partition==='E'){
    if(fixture.path[0]==='eappV1Disposition')return [patchExactConst(root,ROOT_SCHEMA,['$defs','eappV1Disposition','properties',fixture.path[1],'const'],getAt(before,fixture.path),getAt(after,fixture.path),id)];
    const field=fixture.path[1],value=field==='sourceRoots'?before.dependencyBinding.sourceRoots:before.dependencyBinding[field],next=field==='sourceRoots'?after.dependencyBinding.sourceRoots:after.dependencyBinding[field];
    return [patchExactConst(root,'schemas/dependency-binding.v1.schema.json',['$defs','dependencyBinding','properties',field,'const'],value,next,id)];
  }
  if(fixture.partition==='F'&&fixture.kind==='bindingId')return [patchExactConst(root,ROOT_SCHEMA,['$defs','root','properties','schemaBindings','prefixItems',0,'allOf',1,'properties','schemaId','const'],before.schemaBindings[0].schemaId,after.schemaBindings[0].schemaId,id)];
  if(fixture.partition==='F'&&fixture.kind==='bindingPointer')return [patchExactConst(root,ROOT_SCHEMA,['$defs','root','properties','schemaBindings','prefixItems',0,'allOf',1,'properties','rootJsonPointers','const'],before.schemaBindings[0].rootJsonPointers,after.schemaBindings[0].rootJsonPointers,id)];
  if(fixture.partition==='F'&&fixture.kind==='bindingOrder'){
    const path=['$defs','root','properties','schemaBindings','prefixItems'],schema=readJson(root,ROOT_SCHEMA),items=getAt(schema,path),repaired=[...items];[repaired[0],repaired[1]]=[repaired[1],repaired[0]];
    return [replaceOrderedPrefixItem(root,ROOT_SCHEMA,path,items,repaired,id)];
  }
  if(fixture.partition==='F'&&fixture.kind==='widenExecution')return [patchExactConst(root,ROOT_SCHEMA,[...H1_ROOT_DEF,'executionAllowed'],{anyOf:[{const:false},{const:true}]},{const:false},id)];
  return [];
};
/* Some probes deliberately point at a missing local schema/definition or relax
 * a frozen grammar.  Those are A0 rejection probes, not alternate CPSB source
 * states: H1 restores their exact source bytes.  This avoids fabricating a
 * schema identity, changing the schema roster, or admitting a remote ref. */
const h1RepairClass=fixture=>fixture.partition==='B'&&['schemaId','definitionPointer'].includes(fixture.kind)||fixture.partition==='F'&&['bindingRaw','bindingId','bindingPointer','bindingOrder','unusedDef','widenExecution'].includes(fixture.kind)?'restoration':'schema-counterfactual';
const restoreExactSource=(root,locator,source,id)=>{const target=resolve(root,locator),mutated=readFileSync(target);assert.equal(mutated.equals(source),false,`${id}: H1 source mutation present before restoration`);writeFileSync(target,source);assert.equal(readFileSync(target).equals(source),true,`${id}: H1 exact source restoration ${locator}`);return locator;};
const h1Restore=(fixture,root,before,after,beforeFiles)=>{
  const id=fixture.mutationId;
  if(fixture.partition==='B'){
    const entry=after.futureRecordContracts.entries[fixture.index],original=before.futureRecordContracts.entries[fixture.index],locator=descriptorSchemaLocator(before,fixture.index,id),schema=readJson(root,locator);
    assert.equal(entry.recordKind,original.recordKind,`${id}: H1 descriptor identity retained`);
    if(fixture.kind==='schemaId'){assert.equal(entry.schemaId,`${SCHEMA_PREFIX}missing-${id}.schema.json`,`${id}: H1 missing local schema-id probe`);assert.equal(schema.$id,original.schemaId,`${id}: H1 source target schema-id`);assert.equal(schemaFiles.some(file=>readJson(root,file).$id===entry.schemaId),false,`${id}: H1 missing schema has no local target`);}
    else {const missing=`missing_${id.replaceAll('-','_')}`;assert.equal(entry.definitionPointer,`#/$defs/${missing}`,`${id}: H1 missing local definition probe`);assert.equal(Object.hasOwn(schema.$defs??{},missing),false,`${id}: H1 missing definition has no local target`);}
    return [restoreExactSource(root,ROOT_FILE,beforeFiles[ROOT_FILE],id)];
  }
  const bindingBefore=before.schemaBindings[0],bindingAfter=after.schemaBindings[0];
  if(fixture.kind==='bindingRaw')assert.notEqual(bindingAfter.rawSha256,bindingBefore.rawSha256,`${id}: H1 binding raw probe`);
  else if(fixture.kind==='bindingId'){const schema=readJson(root,bindingBefore.locator);assert.equal(bindingAfter.schemaId,`${SCHEMA_PREFIX}missing-binding-${id}.schema.json`,`${id}: H1 missing binding schema-id probe`);assert.equal(schema.$id,bindingBefore.schemaId,`${id}: H1 binding source schema-id`);}
  else if(fixture.kind==='bindingPointer')assert.deepEqual(bindingAfter.rootJsonPointers,['/artifactDependencyDag/edges'],`${id}: H1 binding pointer probe`);
  else if(fixture.kind==='bindingOrder')assert.deepEqual(after.schemaBindings.slice(0,2),[before.schemaBindings[1],before.schemaBindings[0]],`${id}: H1 binding order probe`);
  else if(fixture.kind==='unusedDef'){const schema=readJson(root,fixture.locator);assert.deepEqual(schema.$defs.__cpsb_unused,{type:'null'},`${id}: H1 unused definition probe`);delete schema.$defs.__cpsb_unused;writeCanonical(root,fixture.locator,schema);assert.equal(readFileSync(resolve(root,fixture.locator)).equals(beforeFiles[fixture.locator]),true,`${id}: H1 unused definition removed exactly`);return [fixture.locator];}
  else {const schema=readJson(root,fixture.locator),source=readJson(root,fixture.locator);assert.deepEqual(schema.$defs.root.properties.executionAllowed,{anyOf:[{const:false},{const:true}]},`${id}: H1 widened execution probe`);source.$defs.root.properties.executionAllowed={const:false};writeCanonical(root,fixture.locator,source);assert.equal(readFileSync(resolve(root,fixture.locator)).equals(beforeFiles[fixture.locator]),true,`${id}: H1 execution grammar restored exactly`);return [fixture.locator];}
  return [restoreExactSource(root,fixture.kind==='unusedDef'||fixture.kind==='widenExecution'?fixture.locator:ROOT_FILE,beforeFiles[fixture.kind==='unusedDef'||fixture.kind==='widenExecution'?fixture.locator:ROOT_FILE],id)];
};
const h1Repair=(fixture,root,before,after,beforeFiles)=>{const repairClass=h1RepairClass(fixture),locators=repairClass==='restoration'?h1Restore(fixture,root,before,after,beforeFiles):h1CoherentRepair(fixture,root,before,after);return {locators,repairClass};};

test('canonical mutation inventory is exactly A32/B44/C16/D16/E12/F8 with 128 unique IDs',()=>{assert.deepEqual(cases.filter(row=>row.partition==='A').length,32);assert.deepEqual(cases.filter(row=>row.partition==='B').length,44);assert.deepEqual(cases.filter(row=>row.partition==='C').length,16);assert.deepEqual(cases.filter(row=>row.partition==='D').length,16);assert.deepEqual(cases.filter(row=>row.partition==='E').length,12);assert.deepEqual(cases.filter(row=>row.partition==='F').length,8);assert.equal(cases.length,128);assert.equal(new Set(cases.map(row=>row.mutationId)).size,128);});
test('H1 restoration classification is limited to source-impossible probes',()=>{assert.deepEqual(cases.filter(fixture=>h1RepairClass(fixture)==='restoration').map(fixture=>fixture.mutationId),['B-02','B-06','B-10','B-14','B-18','B-22','B-26','B-30','B-34','B-38','B-42','F-01','F-02','F-03','F-04','F-05','F-08']);assert.deepEqual(cases.filter(fixture=>fixture.partition==='F'&&h1RepairClass(fixture)==='schema-counterfactual').map(fixture=>fixture.mutationId),['F-06','F-07']);});

test('A0 source-only clone remains the sole validator positive',()=>withClone(clone=>{const result=validateStatic({packageRoot:clone,mode:'unsealed'});assert.equal(result.files,27);assert.equal(result.totalRecordCount,0);assert.equal(result.unsealed,true);}));

const coherentFExpected=Object.freeze({'F-05':'CPSB_SCHEMA_REACHABILITY','F-06':'CPSB_SCHEMA_COMPILE:semantic-fingerprint:schemas/principal-identity-ref.v1.schema.json','F-07':'CPSB_SCHEMA_REF:$recursiveRef','F-08':'CPSB_SCHEMA_COMPILE:semantic-fingerprint:schemas/root.v1.schema.json'});
for(const fixture of cases)test(`mutation ${fixture.mutationId} ${fixture.scope} rejects a fresh source clone with ${fixture.expected}`,async()=>await withClone(async clone=>{const before=Object.fromEntries(AUTHORED_FILES.map(locator=>[locator,readFileSync(resolve(clone,locator))]));mutate(fixture,clone);assertOnePrimaryMutation(clone,before,fixture);expectCpsb(fixture.expected,()=>validateStatic({packageRoot:clone,mode:'unsealed'}));if(Object.hasOwn(coherentFExpected,fixture.mutationId))await withClone(async coherent=>{const coherentBefore=Object.fromEntries(AUTHORED_FILES.map(locator=>[locator,readFileSync(resolve(coherent,locator))]));mutate(fixture,coherent);assertOnePrimaryMutation(coherent,coherentBefore,fixture);const document=readJson(coherent,ROOT_FILE);await rebindSchemaRaws(document,coherent);await redigestCpsb(document);writeCanonical(coherent,ROOT_FILE,document);expectCpsb(coherentFExpected[fixture.mutationId],()=>validateStatic({packageRoot:coherent,mode:'unsealed'}));});}));

const ANCHOR_LOCATOR='cpsb-review-anchor.v1.json';
const ROOT_SCHEMA='schemas/root.v1.schema.json';
const sha256=bytes=>createHash('sha256').update(bytes).digest('hex');
const digestRecord=async(domain,value)=>({algorithm:'sha256',canonicalization:'recursive-lexicographic-object-key-sort-arrays-preserve-order-json-utf8-lf-v1',domain,frame:'utf8(domain)||0x00||canonical-json-utf8||0x0a',value:await sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),Buffer.from(`${canonicalJson(value)}\n`)]))});
const canonicalNfc=value=>typeof value==='string'?value.normalize('NFC')===value:Array.isArray(value)?value.every(canonicalNfc):value&&typeof value==='object'?Object.entries(value).every(([key,item])=>key.normalize('NFC')===key&&canonicalNfc(item)):true;
const strictCanonical=(bytes,label)=>{const source=bytes.toString('utf8'),value=JSON.parse(source);assert.equal(Buffer.from(source,'utf8').equals(bytes),true,`${label}: utf8`);assert.equal(canonicalNfc(value),true,`${label}: nfc`);assert.equal(source,`${canonicalJson(value)}\n`,`${label}: canonical duplicate-free`);return value;};
const componentDomains=Object.freeze([['dependencyBinding','dependency-binding'],['eappV1Disposition','eapp-v1-disposition'],['futureRecordContracts','future-record-contracts'],['controlPlaneTransition','control-plane-transition'],['artifactDependencyDag','artifact-dependency-dag'],['nonAuthorityBoundary','nonauthority-boundary'],['runtimeBoundary','runtime-boundary'],['schemaBindings','schema-bindings']]);
const componentValue=value=>Array.isArray(value)?value:(()=>{const copy={...value};delete copy.contentDigest;return copy;})();
const redigestDescriptors=async root=>{for(const row of root.futureRecordContracts.entries){const copy={...row};delete copy.contentDigest;row.contentDigest=await digestRecord(`${PREFIX}/future-record-contract/${row.recordKind}`,copy);}};
const redigestCpsb=async root=>{await redigestDescriptors(root);for(const [component,suffix] of componentDomains){if(!Array.isArray(root[component]))root[component].contentDigest=await digestRecord(`${PREFIX}/${suffix}`,componentValue(root[component]));}for(const [component,suffix] of componentDomains)root.componentDigests.find(row=>row.component===component).digest=await digestRecord(`${PREFIX}/${suffix}`,componentValue(root[component]));const body={...root};delete body.contentDigest;root.contentDigest=await digestRecord(`${PREFIX}/root`,body);return root;};
const fileDigest=async(locator,bytes)=>({algorithm:'sha256',canonicalization:'raw-file-bytes-v1',domain:`${PREFIX}/file/${locator}`,frame:'utf8(domain)||0x00||raw-file-bytes',value:await sha256(Buffer.concat([Buffer.from(`${PREFIX}/file/${locator}`),Buffer.from([0]),bytes]))});
const deriveEnvelope=async root=>{const entries=[];for(const locator of AUTHORED_FILES){const bytes=readFileSync(resolve(root,locator));entries.push({bytes:bytes.length,fileDigest:await fileDigest(locator,bytes),locator,rawSha256:await sha256(bytes)});}const rosterDigest=await digestRecord(`${PREFIX}/manifest-roster`,entries),manifest={schema:`${SCHEMA_PREFIX}manifest.v1.schema.json`,format:'shieldkit-static-manifest-v1',packageId:'gate-b0-external-authority-control-plane-schema-bridge-v1',entryCount:27,entries,rosterDigest},manifestBytes=Buffer.from(`${canonicalJson(manifest)}\n`),sumsBytes=Buffer.from(`${[...entries,{locator:'MANIFEST.json',rawSha256:await sha256(manifestBytes)}].map(row=>`${row.rawSha256}  ${row.locator}`).join('\n')}\n`);return {entries,manifest,manifestBytes,rosterDigest,sumsBytes};};
const writeEnvelope=async root=>{const envelope=await deriveEnvelope(root);writeFileSync(resolve(root,'MANIFEST.json'),envelope.manifestBytes,{mode:0o644});writeFileSync(resolve(root,'SHA256SUMS'),envelope.sumsBytes,{mode:0o644});return envelope;};
const buildAnchor=async(root,envelope,pins={})=>{const rootRawSha256=pins.rootRawSha256??await sha256(readFileSync(resolve(root,ROOT_FILE))),validatorRawSha256=pins.validatorRawSha256??await sha256(readFileSync(resolve(root,'validate-static.mjs')));return {schema:`${PREFIX}/external-review-anchor/v1`,artifactId:'artifact:gate-b:gate-b0-external-authority-control-plane-schema-bridge-review-anchor-v1',packageId:'gate-b0-external-authority-control-plane-schema-bridge-v1',status:'sealed-static-control-plane-schema-bridge-review-anchor-no-principals-no-decisions-no-contracts-no-bindings-no-authorizations-no-instances-no-admission-no-execution-unqualified',package:'research-lanes/bch-shielded-pool-design/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge-v1',rootRawSha256,rootContentDigest:root.contentDigest,validatorRawSha256,entryCount:27,rosterDigest:envelope.rosterDigest,manifestRawSha256:await sha256(envelope.manifestBytes),sha256SumsRawSha256:await sha256(envelope.sumsBytes),schemaBindingTableDigest:await digestRecord(`${PREFIX}/schema-bindings`,root.schemaBindings),schemaBindings:root.schemaBindings,componentDigests:root.componentDigests,directDependencyBinding:root.dependencyBinding,eappV1DispositionDigest:root.componentDigests.find(row=>row.component==='eappV1Disposition').digest,nonAuthorityBoundary:root.nonAuthorityBoundary,orderedClosure:envelope.entries};};
const installAnchor=async(root,anchorRoot,anchor)=>{const bytes=Buffer.from(`${canonicalJson(anchor)}\n`);writeFileSync(resolve(anchorRoot,ANCHOR_LOCATOR),bytes,{mode:0o644});return {mode:'sealed',anchorRoot,anchorLocator:ANCHOR_LOCATOR,anchorBytes:bytes.length,anchorRawSha256:await sha256(bytes)};};
const cloneSealed=async()=>{const root=mkdtempSync(resolve(packageParent,'.cpsb-coordinated-')),anchorRoot=mkdtempSync(resolve(packageParent,'.cpsb-coordinated-anchor-'));chmodSync(root,0o755);chmodSync(anchorRoot,0o755);copySource(root);const envelope=await writeEnvelope(root),document=strictCanonical(readFileSync(resolve(root,ROOT_FILE)),'H0 root'),anchor=await buildAnchor(root,envelope),pin=await installAnchor(root,anchorRoot,anchor);return {anchor,anchorRoot,document,envelope,pin,root};};
const removeClone=fixture=>{rmSync(fixture.root,{recursive:true,force:true});rmSync(fixture.anchorRoot,{recursive:true,force:true});};
const walk=(root,relative='')=>readdirSync(resolve(root,relative),{withFileTypes:true}).flatMap(entry=>{const locator=relative?`${relative}/${entry.name}`:entry.name;return entry.isDirectory()?[{kind:'directory',locator},...walk(root,locator)]:[{kind:entry.isFile()?'file':entry.isSymbolicLink()?'link':'special',locator}];});
const pointer=(document,fragment)=>fragment.slice(1).split('/').filter(Boolean).reduce((value,part)=>value[part.replaceAll('~1','/').replaceAll('~0','~')],document);
const assertSchemaReachability=async(root,id)=>{const schemas=[];for(const locator of schemaFiles)schemas.push(strictCanonical(readFileSync(resolve(root,locator)),`${id}:${locator}`));const byId=new Map(schemas.map(schema=>[schema.$id,schema]));assert.equal(byId.size,18,`${id}: distinct schema ids`);const document=strictCanonical(readFileSync(resolve(root,ROOT_FILE)),`${id}: root`);assert.deepEqual(document.schemaBindings.map(row=>row.locator),schemaFiles,`${id}: schema roster`);for(const row of document.schemaBindings){const bytes=readFileSync(resolve(root,row.locator));assert.equal(row.schemaId,strictCanonical(bytes,`${id}:${row.loc}`).$id,`${id}: schema id ${row.loc}`);assert.equal(row.rawSha256,await sha256(bytes),`${id}: schema raw ${row.loc}`);}const reached=new Set(),visit=(schemaId,node)=>{if(Array.isArray(node)){node.forEach(value=>visit(schemaId,value));return;}if(!node||typeof node!=='object')return;if(typeof node.$ref==='string'){const [target='',fragment='']=node.$ref.split('#'),resolved=target||schemaId;if(fragment.startsWith('/$defs/')){const name=fragment.split('/')[2];reached.add(`${resolved}#/$defs/${name}`);visit(resolved,pointer(byId.get(resolved),fragment));}}for(const [key,value] of Object.entries(node))if(key!=='$defs'&&key!=='$ref')visit(schemaId,value);};const seed=(schemaId,fragment)=>{reached.add(`${schemaId}#${fragment}`);visit(schemaId,pointer(byId.get(schemaId),fragment));};seed(`${SCHEMA_PREFIX}root.v1.schema.json`,'/$defs/root');seed(`${SCHEMA_PREFIX}manifest.v1.schema.json`,'/$defs/manifest');for(const entry of document.futureRecordContracts.entries)seed(entry.schemaId,entry.definitionPointer.replace('#',''));const defined=schemas.flatMap(schema=>Object.keys(schema.$defs??{}).map(name=>`${schema.$id}#/$defs/${name}`)).sort();assert.equal(defined.length,75,`${id}: exact 75 definitions`);assert.deepEqual([...reached].sort(),defined,`${id}: all definitions reachable`);return document;};
const assertH1Oracle=async(fixture,id)=>{const tree=walk(fixture.root),files=tree.filter(row=>row.kind==='file').map(row=>row.locator).sort(),dirs=['.',...tree.filter(row=>row.kind==='directory').map(row=>row.locator)].sort();assert.deepEqual(files,[...AUTHORED_FILES,'MANIFEST.json','SHA256SUMS'].sort(),`${id}: exact 29 closure`);assert.deepEqual(dirs,['.','schemas','test'],`${id}: exact 3 directories`);for(const locator of dirs){const stat=lstatSync(resolve(fixture.root,locator));assert.equal(stat.isDirectory()&&!stat.isSymbolicLink()&&(stat.mode&0o777)===0o755,true,`${id}: directory mode ${locator}`);}for(const locator of files){const stat=lstatSync(resolve(fixture.root,locator));assert.equal(stat.isFile()&&!stat.isSymbolicLink()&&(stat.mode&0o777)===0o644&&stat.nlink===1,true,`${id}: file mode/nlink ${locator}`);}const root=await assertSchemaReachability(fixture.root,id),envelope=await deriveEnvelope(fixture.root);assert.equal(readFileSync(resolve(fixture.root,'MANIFEST.json')).equals(envelope.manifestBytes),true,`${id}: manifest`);assert.equal(readFileSync(resolve(fixture.root,'SHA256SUMS')).equals(envelope.sumsBytes),true,`${id}: sums`);for(const [component,suffix] of componentDomains)assert.deepEqual(root.componentDigests.find(row=>row.component===component).digest,await digestRecord(`${PREFIX}/${suffix}`,componentValue(root[component])),`${id}: component ${component}`);for(const row of root.futureRecordContracts.entries){const copy={...row};delete copy.contentDigest;assert.deepEqual(row.contentDigest,await digestRecord(`${PREFIX}/future-record-contract/${row.recordKind}`,copy),`${id}: descriptor ${row.recordKind}`);}const future={...root.futureRecordContracts};delete future.contentDigest;assert.deepEqual(root.futureRecordContracts.contentDigest,await digestRecord(`${PREFIX}/future-record-contracts`,future),`${id}: future digest`);const body={...root};delete body.contentDigest;assert.deepEqual(root.contentDigest,await digestRecord(`${PREFIX}/root`,body),`${id}: root digest`);const anchorBytes=readFileSync(resolve(fixture.anchorRoot,ANCHOR_LOCATOR)),anchor=strictCanonical(anchorBytes,`${id}: anchor`),expected=await buildAnchor(fixture.root,envelope),anchorStat=lstatSync(resolve(fixture.anchorRoot,ANCHOR_LOCATOR));assert.equal(Object.keys(anchor).length,19,`${id}: exact 19 anchor keys`);assert.equal(anchorStat.isFile()&&!anchorStat.isSymbolicLink()&&anchorStat.nlink===1&&(anchorStat.mode&0o777)===0o644,true,`${id}: outside anchor mode/nlink`);assert.deepEqual(anchor,expected,`${id}: coherent anchor`);assert.equal(sha256(anchorBytes),fixture.pin.anchorRawSha256,`${id}: anchor raw`);return root;};
const updateSameWidthRoot=async root=>{const document=strictCanonical(readFileSync(resolve(root,ROOT_FILE)),'A1 source root'),schema=strictCanonical(readFileSync(resolve(root,ROOT_SCHEMA)),'A1 root schema'),before=structuredClone(document),oldPurpose=document.purpose,newPurpose=`${oldPurpose.slice(0,6)}X${oldPurpose.slice(7)}`;assert.equal(newPurpose.length,oldPurpose.length,'A1 same-width purpose');document.purpose=newPurpose;schema.$defs.root.properties.purpose.const=newPurpose;writeCanonical(root,ROOT_SCHEMA,schema);document.schemaBindings.find(row=>row.locator===ROOT_SCHEMA).rawSha256=await sha256(readFileSync(resolve(root,ROOT_SCHEMA)));await redigestCpsb(document);writeCanonical(root,ROOT_FILE,document);const normalized=structuredClone(document);normalized.schemaBindings=before.schemaBindings;delete normalized.componentDigests;delete normalized.contentDigest;const original=structuredClone(before);delete original.componentDigests;delete original.contentDigest;assert.equal(leafDiffCount(original,normalized),1,'A1 exact one semantic root mutation');return {before,document};};
const H0_ROOT_BYTES=50052;
const H0_ROOT_RAW_SHA256='89c281e916790e5d488f554fdf508af80cc7c3e0b8d9a2b99f62707c150a17e4';
const H0_VALIDATOR_BYTES=438375;
const H0_VALIDATOR_RAW_SHA256='65727edaa77d783dd0db33f70f57856240f7c732b7156fa8c76785aadf94546c';

const rebindSchemaRaws=async(root,packageRoot)=>{assert.ok(Array.isArray(root.schemaBindings),`H1 schema bindings exist`);for(const binding of root.schemaBindings){assert.equal(typeof binding?.locator,'string',`H1 schema binding locator`);const bytes=readFileSync(resolve(packageRoot,binding.locator));binding.rawSha256=await sha256(bytes);}};
const h1RestoresOriginalRoot=fixture=>h1RepairClass(fixture)==='restoration';
const assertH1Redigested=(async(root,before,fixture)=>{const id=fixture.mutationId,document=readJson(root,ROOT_FILE);for(const binding of document.schemaBindings){assert.ok(schemaFiles.includes(binding.locator),`${id}: H1 schema binding repair path`);assert.equal(binding.rawSha256,await sha256(readFileSync(resolve(root,binding.locator))),`${id}: H1 rebound schema raw ${binding.locator}`);}for(const row of document.futureRecordContracts.entries){const copy={...row};delete copy.contentDigest;assert.deepEqual(row.contentDigest,await digestRecord(`${PREFIX}/future-record-contract/${row.recordKind}`,copy),`${id}: H1 redigested descriptor ${row.recordKind}`);}for(const [component,suffix] of componentDomains){const aggregate=document.componentDigests.find(row=>row.component===component);assert.ok(aggregate,`${id}: H1 component aggregate ${component}`);assert.deepEqual(aggregate.digest,await digestRecord(`${PREFIX}/${suffix}`,componentValue(document[component])),`${id}: H1 redigested component ${component}`);}const body={...document};delete body.contentDigest;assert.deepEqual(document.contentDigest,await digestRecord(`${PREFIX}/root`,body),`${id}: H1 redigested root`);if(h1RestoresOriginalRoot(fixture)){assert.deepEqual(document.contentDigest,before.contentDigest,`${id}: H1 root digest restored`);assert.deepEqual(document,before,`${id}: H1 root restored exactly`);}else assertRepairChange(before.contentDigest,document.contentDigest,id,'root semantics');return document;});
const assertH1LocalSchemaRefs=(root,id)=>{const schemas=schemaFiles.map(locator=>strictCanonical(readFileSync(resolve(root,locator)),`${id}: local refs ${locator}`)),ids=new Set(schemas.map(schema=>schema.$id));const visit=node=>{if(Array.isArray(node)){node.forEach(visit);return;}if(!node||typeof node!=='object')return;if(typeof node.$ref==='string'){const target=node.$ref.split('#',1)[0];assert.equal(target===''||ids.has(target),true,`${id}: H1 local schema ref ${node.$ref}`);}Object.values(node).forEach(visit);};schemas.forEach(visit);};
const assertH1AjvOracle=(root,id)=>{const ajv=new Ajv2020({strict:false,allErrors:true,validateFormats:false}),schemas=schemaFiles.map(locator=>strictCanonical(readFileSync(resolve(root,locator)),`${id}: Ajv ${locator}`));assert.equal(schemas.length,18,`${id}: H1 eighteen schemas`);for(const schema of schemas)ajv.addSchema(schema);for(const schema of schemas)assert.doesNotThrow(()=>ajv.getSchema(schema.$id)??ajv.compile(schema),`${id}: H1 compile ${schema.$id}`);const document=strictCanonical(readFileSync(resolve(root,ROOT_FILE)),`${id}: H1 root`),validate=ajv.getSchema(`${SCHEMA_PREFIX}root.v1.schema.json`);assert.equal(typeof validate,'function',`${id}: H1 root validator`);assert.equal(validate(document),true,`${id}: H1 root acceptance ${JSON.stringify(validate.errors)}`);};
const assertH1RepairClosure=(root,before,fixture,{locators,repairClass})=>{const tree=walk(root),files=tree.filter(row=>row.kind==='file').map(row=>row.locator).sort(),dirs=['.',...tree.filter(row=>row.kind==='directory').map(row=>row.locator)].sort();assert.deepEqual(files,[...AUTHORED_FILES].sort(),`${fixture.mutationId}: H1 exact source closure`);assert.deepEqual(dirs,['.','schemas','test'],`${fixture.mutationId}: H1 exact directory closure`);assert.equal(tree.every(row=>row.kind==='file'||row.kind==='directory'),true,`${fixture.mutationId}: H1 no links or specials`);for(const locator of dirs){const stat=lstatSync(resolve(root,locator));assert.equal(stat.isDirectory()&&!stat.isSymbolicLink()&&(stat.mode&0o777)===0o755,true,`${fixture.mutationId}: H1 directory mode ${locator}`);}for(const locator of files){const stat=lstatSync(resolve(root,locator));assert.equal(stat.isFile()&&!stat.isSymbolicLink()&&stat.nlink===1&&(stat.mode&0o777)===0o644,true,`${fixture.mutationId}: H1 file mode/link ${locator}`);}const repairs=new Set(locators),allowed=new Set([ROOT_FILE,changedLocator(fixture),...repairs]);if(repairClass==='restoration'){for(const locator of AUTHORED_FILES)assert.equal(readFileSync(resolve(root,locator)).equals(before[locator]),true,`${fixture.mutationId}: H1 source restored exactly`);return;}for(const locator of repairs)assert.equal(readFileSync(resolve(root,locator)).equals(before[locator]),false,`${fixture.mutationId}: H1 repair locator changed ${locator}`);for(const locator of AUTHORED_FILES){const changed=!readFileSync(resolve(root,locator)).equals(before[locator]);assert.equal(!changed||allowed.has(locator),true,`${fixture.mutationId}: H1 unrelated source drift ${locator}`);}};

for(const fixture of cases)test(`H1 ${fixture.mutationId} is an explicitly structural schema counterfactual or exact restoration`,async()=>{const root=mkdtempSync(resolve(packageParent,'.cpsb-h1-'));try{copySource(root);assertCloneBaseline(root);const before=Object.fromEntries(AUTHORED_FILES.map(locator=>[locator,readFileSync(resolve(root,locator))]));const primary=readJson(root,ROOT_FILE);mutate(fixture,root);assertOnePrimaryMutation(root,before,fixture);const mutated=readJson(root,ROOT_FILE),repair=h1Repair(fixture,root,primary,mutated,before);assert.ok(Array.isArray(repair.locators),`${fixture.mutationId}: H1 repair locator list`);assert.ok(['schema-counterfactual','restoration'].includes(repair.repairClass),`${fixture.mutationId}: H1 repair classification`);if(repair.repairClass==='schema-counterfactual'){const document=readJson(root,ROOT_FILE);await rebindSchemaRaws(document,root);await redigestCpsb(document);writeCanonical(root,ROOT_FILE,document);}await assertH1Redigested(root,primary,fixture);assertH1RepairClosure(root,before,fixture,repair);assertH1LocalSchemaRefs(root,fixture.mutationId);await assertSchemaReachability(root,`${fixture.mutationId}: H1`);assertH1AjvOracle(root,fixture.mutationId);}finally{rmSync(root,{recursive:true,force:true});}});

test('sealed coordinated H0/A1 uses frozen source literals and unchanged A0 validator',async()=>{assert.equal(readFileSync(resolve(packageRoot,ROOT_FILE)).length,H0_ROOT_BYTES,'literal H0 root bytes');assert.equal(sha256(readFileSync(resolve(packageRoot,ROOT_FILE))),H0_ROOT_RAW_SHA256,'literal H0 root raw');assert.equal(readFileSync(resolve(packageRoot,'validate-static.mjs')).length,H0_VALIDATOR_BYTES,'literal H0 validator bytes');assert.equal(sha256(readFileSync(resolve(packageRoot,'validate-static.mjs'))),H0_VALIDATOR_RAW_SHA256,'literal H0 validator raw');const h0=await cloneSealed();let staleFixture,a1;try{await assertH1Oracle(h0,'coherent H0');assertH1AjvOracle(h0.root,'coherent H0');assert.deepEqual(validateStatic({packageRoot:h0.root,...h0.pin}),{files:29,directories:3,schemaCount:18,futureRecordSchemaCount:11,totalRecordCount:0,rootContentDigest:h0.document.contentDigest.value,unsealed:false},'genuine production H0 sealed positive');staleFixture=await cloneSealed();assert.equal(readFileSync(resolve(staleFixture.root,'validate-static.mjs')).equals(sourceBytes['validate-static.mjs']),true,'unchanged original A0 validator');await updateSameWidthRoot(staleFixture.root);const staleEnvelope=await writeEnvelope(staleFixture.root),staleAnchor=await buildAnchor(staleFixture.root,staleEnvelope,{rootRawSha256:H0_ROOT_RAW_SHA256,validatorRawSha256:H0_VALIDATOR_RAW_SHA256}),stalePin=await installAnchor(staleFixture.root,staleFixture.anchorRoot,staleAnchor);expectCpsb('CPSB_ANCHOR_RAW:root',()=>validateStatic({packageRoot:staleFixture.root,...stalePin}));a1=await cloneSealed();const {before}=await updateSameWidthRoot(a1.root);assert.equal(readFileSync(resolve(a1.root,'validate-static.mjs')).equals(sourceBytes['validate-static.mjs']),true,'A1 retains unchanged imported A0 validator');const a1Envelope=await writeEnvelope(a1.root),a1Anchor=await buildAnchor(a1.root,a1Envelope,{validatorRawSha256:H0_VALIDATOR_RAW_SHA256});a1.pin=await installAnchor(a1.root,a1.anchorRoot,a1Anchor);const finalRoot=await assertH1Oracle(a1,'coherent A1');assertH1AjvOracle(a1.root,'coherent A1');expectCpsb('CPSB_SCHEMA_COMPILE:semantic-fingerprint:schemas/root.v1.schema.json',()=>validateStatic({packageRoot:a1.root,...a1.pin}));const semantic={...finalRoot,schemaBindings:before.schemaBindings};delete semantic.componentDigests;delete semantic.contentDigest;const original={...before};delete original.componentDigests;delete original.contentDigest;assert.equal(leafDiffCount(original,semantic),1,'A1 no semantic drift beyond purpose');}finally{if(a1)removeClone(a1);if(staleFixture)removeClone(staleFixture);removeClone(h0);}});
