import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { chmodSync, copyFileSync, linkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { validateStatic } from '../validate-static.mjs';

const packageRoot=resolve(import.meta.dirname,'..');
const packageParent=dirname(packageRoot);
const PREFIX='shieldkit-labs/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge/v1';
const SCHEMA_PREFIX='https://shieldkit-labs.local/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge/v1/';
const PACKAGE_ID='gate-b0-external-authority-control-plane-schema-bridge-v1';
const files=Object.freeze(['COMMAND.txt','README.md','external-authority-control-plane-schema-bridge-root.v1.json','schemas/artifact-dependency-dag.v1.schema.json','schemas/b0-execution-authorization.v1.schema.json','schemas/binding-creation-authorization-g0.v1.schema.json','schemas/control-plane-transition.v2.schema.json','schemas/dependency-binding.v1.schema.json','schemas/digest.v1.schema.json','schemas/external-authority-contract.v2.schema.json','schemas/governance-authorization-g1.v1.schema.json','schemas/instance-creation-event.v1.schema.json','schemas/issuer-decision.v1.schema.json','schemas/manifest.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/principal-identity-ref.v1.schema.json','schemas/provider-binding-catalog.v1.schema.json','schemas/provider-binding.v2.schema.json','schemas/provider-contract.v1.schema.json','schemas/root.v1.schema.json','schemas/source-collision-decision.v2.schema.json','test/digest.kat.json','test/future-schema.test.mjs','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs','validate-static.mjs']);
const canonicalJson=value=>Array.isArray(value)?`[${value.map(canonicalJson).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`:JSON.stringify(value);
const sha256=bytes=>createHash('sha256').update(bytes).digest('hex');
const digestRecord=async(domain,value)=>({algorithm:'sha256',canonicalization:'recursive-lexicographic-object-key-sort-arrays-preserve-order-json-utf8-lf-v1',domain,frame:'utf8(domain)||0x00||canonical-json-utf8||0x0a',value:await sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),Buffer.from(`${canonicalJson(value)}\n`)]))});
const fileDigestRecord=async(locator,bytes)=>({algorithm:'sha256',canonicalization:'raw-file-bytes-v1',domain:`${PREFIX}/file/${locator}`,frame:'utf8(domain)||0x00||raw-file-bytes',value:await sha256(Buffer.concat([Buffer.from(`${PREFIX}/file/${locator}`),Buffer.from([0]),bytes]))});
const expectToken=(action,token)=>assert.throws(action,error=>error instanceof Error&&error.message===`CPSB_${token}`);
const sourceClone=({shortPath=false}={})=>{const clone=mkdtempSync(shortPath?resolve(tmpdir(),'cpsb-b-'):resolve(packageParent,'.cpsb-boundary-'));chmodSync(clone,0o755);mkdirSync(resolve(clone,'schemas'),{mode:0o755});mkdirSync(resolve(clone,'test'),{mode:0o755});for(const locator of files){const destination=resolve(clone,locator);copyFileSync(resolve(packageRoot,locator),destination);chmodSync(destination,0o644);}return clone;};
const withClone=async(action,options={})=>{const clone=sourceClone(options),cleanups=[];try{return await action(clone,cleanups);}finally{for(const cleanup of cleanups.reverse())try{await cleanup();}catch{}rmSync(clone,{recursive:true,force:true});}};
const anchorObject=()=>({artifactId:'artifact:gate-b:gate-b0-external-authority-control-plane-schema-bridge-review-anchor-v1',componentDigests:[],directDependencyBinding:{},eappV1DispositionDigest:{},entryCount:27,manifestRawSha256:'0'.repeat(64),nonAuthorityBoundary:{},orderedClosure:[],package:'research-lanes/bch-shielded-pool-design/p2/gate-b/gate-b0-external-authority-control-plane-schema-bridge-v1',packageId:PACKAGE_ID,rootContentDigest:{},rootRawSha256:'0'.repeat(64),rosterDigest:{},schema:`${PREFIX}/external-review-anchor/v1`,schemaBindingTableDigest:{},schemaBindings:[],sha256SumsRawSha256:'0'.repeat(64),status:'sealed-static-control-plane-schema-bridge-review-anchor-no-principals-no-decisions-no-contracts-no-bindings-no-authorizations-no-instances-no-admission-no-execution-unqualified',validatorRawSha256:'0'.repeat(64)});
const writeAnchor=async(anchorRoot,locator='anchor.json')=>{const bytes=Buffer.from(`${canonicalJson(anchorObject())}\n`);writeFileSync(resolve(anchorRoot,locator),bytes,{mode:0o644});return {anchorRoot,anchorLocator:locator,anchorBytes:bytes.length,anchorRawSha256:await sha256(bytes)};};
const withExternalAnchor=async(cleanups,run)=>{const anchorRoot=mkdtempSync(resolve(packageParent,'.cpsb-anchor-'));chmodSync(anchorRoot,0o755);cleanups.push(()=>rmSync(anchorRoot,{recursive:true,force:true}));return run(await writeAnchor(anchorRoot),anchorRoot);};
const sealBytes=async root=>{const entries=[];for(const locator of files){const bytes=readFileSync(resolve(root,locator));entries.push({bytes:bytes.length,fileDigest:await fileDigestRecord(locator,bytes),locator,rawSha256:await sha256(bytes)});}const rosterDigest=await digestRecord(`${PREFIX}/manifest-roster`,entries),manifest={schema:`${SCHEMA_PREFIX}manifest.v1.schema.json`,format:'shieldkit-static-manifest-v1',packageId:PACKAGE_ID,entryCount:27,entries,rosterDigest},manifestBytes=Buffer.from(`${canonicalJson(manifest)}\n`),sumsBytes=Buffer.from(`${[...entries,{locator:'MANIFEST.json',rawSha256:await sha256(manifestBytes)}].map(row=>`${row.rawSha256}  ${row.locator}`).join('\n')}\n`);return {manifestBytes,sumsBytes};};
const closeSocket=server=>new Promise((resolveClose,reject)=>server.close(error=>error?reject(error):resolveClose()));
const boundaries=Object.freeze([
  ['source-only-positive',null,clone=>assert.equal(validateStatic({packageRoot:clone,mode:'unsealed'}).unsealed,true)],
  ['extra-file','PACKAGE_CLOSURE',clone=>writeFileSync(resolve(clone,'extra.txt'),'x\n',{mode:0o644})],
  ['missing-authored','PACKAGE_CLOSURE',clone=>unlinkSync(resolve(clone,'README.md'))],
  ['file-mode','FILE_MODE',clone=>chmodSync(resolve(clone,'README.md'),0o600)],
  ['dir-mode','DIR_MODE',clone=>{const sibling=sourceClone();try{chmodSync(clone,0o700);expectToken(()=>validateStatic({packageRoot:clone,mode:'unsealed'}),'DIR_MODE');chmodSync(sibling,0o755);chmodSync(resolve(sibling,'schemas'),0o700);expectToken(()=>validateStatic({packageRoot:sibling,mode:'unsealed'}),'DIR_MODE');}finally{chmodSync(clone,0o755);rmSync(sibling,{recursive:true,force:true});}return {handled:true};}],
  ['file-symlink','LINK',clone=>{unlinkSync(resolve(clone,'README.md'));symlinkSync('COMMAND.txt',resolve(clone,'README.md'));}],
  ['dir-symlink','LINK',clone=>{rmSync(resolve(clone,'schemas'),{recursive:true,force:true});symlinkSync('test',resolve(clone,'schemas'),'dir');}],
  ['hardlink','LINK',clone=>{unlinkSync(resolve(clone,'README.md'));linkSync(resolve(clone,'COMMAND.txt'),resolve(clone,'README.md'));}],
  ['unix-socket','SPECIAL_FILE',async(clone,cleanups)=>{const socket=resolve(clone,'s'),server=createServer();assert.ok(Buffer.byteLength(socket)<100);rmSync(socket,{force:true});cleanups.push(async()=>{if(server.listening)await closeSocket(server);rmSync(socket,{force:true});});await new Promise((resolveListen,reject)=>server.once('error',reject).listen(socket,resolveListen));}, {shortPath:true}],
  ['invalid-path','PATH',clone=>{for(const locator of ['.','..','bad\\anchor','bad\0anchor'])expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',anchorRoot:clone,anchorLocator:locator,anchorBytes:1,anchorRawSha256:'0'.repeat(64)}),'PATH');return {handled:true};}],
  ['manifest-only','PACKAGE_CLOSURE',clone=>writeFileSync(resolve(clone,'MANIFEST.json'),'{}\n',{mode:0o644})],
  ['sums-only','PACKAGE_CLOSURE',clone=>writeFileSync(resolve(clone,'SHA256SUMS'),'x\n',{mode:0o644})],
  ['stale-manifest','MANIFEST',async(clone,cleanups)=>{const sealed=await sealBytes(clone);writeFileSync(resolve(clone,'MANIFEST.json'),'{}\n',{mode:0o644});writeFileSync(resolve(clone,'SHA256SUMS'),sealed.sumsBytes,{mode:0o644});await withExternalAnchor(cleanups,async pin=>expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',...pin}),'MANIFEST'));return {handled:true};}],
  ['stale-sums','SUMS',async(clone,cleanups)=>{const sealed=await sealBytes(clone);writeFileSync(resolve(clone,'MANIFEST.json'),sealed.manifestBytes,{mode:0o644});writeFileSync(resolve(clone,'SHA256SUMS'),'stale\n',{mode:0o644});await withExternalAnchor(cleanups,async pin=>expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',...pin}),'SUMS'));return {handled:true};}],
  ['missing-anchor','ANCHOR_REQUIRED',clone=>{expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',anchorRoot:clone,anchorLocator:null,anchorBytes:1,anchorRawSha256:'0'.repeat(64)}),'ANCHOR_REQUIRED');expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',anchorRoot:dirname(clone),anchorLocator:'missing-anchor.json',anchorBytes:1,anchorRawSha256:'0'.repeat(64)}),'ANCHOR_LOCATION');return {handled:true};}],
  ['anchor-inside','ANCHOR_LOCATION',async clone=>{const pin=await writeAnchor(clone);expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',...pin}),'ANCHOR_LOCATION');rmSync(resolve(clone,pin.anchorLocator),{force:true});return {handled:true};}],
  ['anchor-symlink','LINK',async(clone,cleanups)=>{await withExternalAnchor(cleanups,async(pin,anchorRoot)=>{symlinkSync(pin.anchorLocator,resolve(anchorRoot,'anchor-link.json'));expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',...pin,anchorLocator:'anchor-link.json'}),'LINK');});return {handled:true};}],
  ['anchor-hardlink','LINK',async(clone,cleanups)=>{await withExternalAnchor(cleanups,async(pin,anchorRoot)=>{linkSync(resolve(anchorRoot,pin.anchorLocator),resolve(anchorRoot,'anchor-hardlink.json'));expectToken(()=>validateStatic({packageRoot:clone,mode:'sealed',...pin,anchorLocator:'anchor-hardlink.json'}),'LINK');});return {handled:true};}]
]);
assert.equal(boundaries.length,18);
assert.equal(new Set(boundaries.map(([label])=>label)).size,18);
for(const boundary of boundaries)test(boundary[0],async()=>withClone(async(clone,cleanups)=>{const result=await boundary[2](clone,cleanups);if(boundary[1]!==null&&!result?.handled)expectToken(()=>validateStatic({packageRoot:clone,mode:'unsealed'}),boundary[1]);},boundary[3]??{}));
