import test from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseValidationCliArgs, validateStatic } from '../validate-static.mjs';

const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const packageParent=dirname(packageRoot);
const root=JSON.parse(readFileSync(resolve(packageRoot,'external-authority-control-plane-schema-bridge-root.v1.json'),'utf8'));
const files=Object.freeze(['COMMAND.txt','README.md','external-authority-control-plane-schema-bridge-root.v1.json','schemas/artifact-dependency-dag.v1.schema.json','schemas/b0-execution-authorization.v1.schema.json','schemas/binding-creation-authorization-g0.v1.schema.json','schemas/control-plane-transition.v2.schema.json','schemas/dependency-binding.v1.schema.json','schemas/digest.v1.schema.json','schemas/external-authority-contract.v2.schema.json','schemas/governance-authorization-g1.v1.schema.json','schemas/instance-creation-event.v1.schema.json','schemas/issuer-decision.v1.schema.json','schemas/manifest.v1.schema.json','schemas/non-authority-boundary.v1.schema.json','schemas/principal-identity-ref.v1.schema.json','schemas/provider-binding-catalog.v1.schema.json','schemas/provider-binding.v2.schema.json','schemas/provider-contract.v1.schema.json','schemas/root.v1.schema.json','schemas/source-collision-decision.v2.schema.json','test/digest.kat.json','test/future-schema.test.mjs','test/mutation.test.mjs','test/package-boundary.test.mjs','test/static.test.mjs','validate-static.mjs']);
const copySource=target=>{chmodSync(target,0o755);mkdirSync(resolve(target,'schemas'),{mode:0o755});mkdirSync(resolve(target,'test'),{mode:0o755});for(const locator of files){const destination=resolve(target,locator);copyFileSync(resolve(packageRoot,locator),destination);chmodSync(destination,0o644);}};
const withClone=run=>{const clone=mkdtempSync(resolve(packageParent,'.cpsb-static-'));copySource(clone);try{return run(clone);}finally{rmSync(clone,{recursive:true,force:true});}};
const expectCpsb=(run,token)=>assert.throws(run,error=>error instanceof Error&&error.message.split(':',1)[0]===`CPSB_${token}`);
const withScannerClone=(label,payload,token)=>withClone(clone=>{const p1=label==='activation-13'?'\nC=>C("return 0");\nasync C=>C("return 0");\n(C=unknown)=>C("return 0");\n(...C)=>C("return 0");\n({x:C})=>C("return 0");\n([C])=>C("return 0");\n({x:C}=unknown);C("return 0");\n[C]=unknown;C("return 0");\nconst C=unknown?.x;C?.arbitrary("return 0");\nconst f=function(C){C("return 0")};\nconst g=function*(C){C("return 0")};\nconst o={m(C){C("return 0")}};\ntry{}catch(C){C("return 0")};\nlet R=()=>{};R=unknown;R("return 0");\nfor({x:I} of rows){I("return 0")};':'';if(payload)writeFileSync(resolve(clone,'test/static.test.mjs'),`${readFileSync(resolve(clone,'test/static.test.mjs'),'utf8')}\n${payload}${p1}\n`,{mode:0o644});if(token===null)assert.equal(validateStatic({packageRoot:clone,mode:'unsealed'}).unsealed,true,label);else expectCpsb(()=>validateStatic({packageRoot:clone,mode:'unsealed'}),token);});
const assertCliCausal=()=>{const good=['--mode','sealed','--anchor-root','/tmp','--anchor-locator','anchor.json','--anchor-bytes','1','--anchor-raw-sha256','0'.repeat(64)],cases=[['missing-mode',[],'CLI_ARGS'],['odd-arity',['--mode'],'CLI_ARGS'],['unsealed-extra',['--mode','unsealed','--anchor-root','/tmp'],'CLI_ARGS'],['sealed-wrong-mode',[...good.slice(0,1),'other',...good.slice(2)],'CLI_ARGS'],['sealed-wrong-flag',[...good.slice(0,2),'--root',...good.slice(3)],'CLI_ARGS'],['sealed-reordered-flags',[...good.slice(0,2),'--anchor-locator','anchor.json','--anchor-root','/tmp',...good.slice(6)],'CLI_ARGS'],['sealed-relative-root',good.map((value,index)=>index===3?'relative':value),'ANCHOR_LOCATION'],['sealed-empty-locator',good.map((value,index)=>index===5?'':value),'PATH'],['sealed-dot-locator',good.map((value,index)=>index===5?'.':value),'PATH'],['sealed-dotdot-locator',good.map((value,index)=>index===5?'../anchor':value),'PATH'],['sealed-backslash-locator',good.map((value,index)=>index===5?'bad\\anchor':value),'PATH'],['sealed-nul-locator',good.map((value,index)=>index===5?'bad\0anchor':value),'PATH'],['sealed-zero-bytes',good.map((value,index)=>index===7?'0':value),'ANCHOR_PIN'],['sealed-unsafe-bytes',good.map((value,index)=>index===7?'9007199254740992':value),'ANCHOR_PIN'],['sealed-upper-hash',good.map((value,index)=>index===9?'A'.repeat(64):value),'ANCHOR_PIN'],['sealed-short-hash',good.map((value,index)=>index===9?'0'.repeat(63):value),'ANCHOR_PIN']];assert.equal(cases.length,16);assert.equal(new Set(cases.map(([label])=>label)).size,16);for(const [,argv,token] of cases)expectCpsb(()=>parseValidationCliArgs(argv),token);assert.deepEqual(parseValidationCliArgs(['--mode','unsealed']),{mode:'unsealed'});assert.deepEqual(parseValidationCliArgs(good),{mode:'sealed',anchorRoot:'/tmp',anchorLocator:'anchor.json',anchorBytes:1,anchorRawSha256:'0'.repeat(64)});};
const decode=codes=>JSON.parse(`"${codes.map(code=>`\\u${code.toString(16).padStart(4,'0')}`).join('')}"`);
const assertModuleBoundaryCausal=()=>{const moduleWord=decode([105,109,112,111,114,116]),outWord=decode([101,120,112,111,114,116]),childModule=decode([110,111,100,101,58,99,104,105,108,100,95,112,114,111,99,101,115,115]),payloads=[['module-01','const from=1;const to=from;',null],['module-02',`${moduleWord} { basename } from 'node:path';`,'IMPORT_BOUNDARY'],['module-03',`${moduleWord} ${JSON.stringify(childModule)};`,'IMPORT_BOUNDARY'],['module-04',`const load=${moduleWord}('node:path');`,'IMPORT_BOUNDARY'],['module-05',`const load=${moduleWord}/*comment*/('node:path');`,'IMPORT_BOUNDARY'],['module-06',`const q=0; ${moduleWord} * as cp from ${JSON.stringify(childModule)};`,'IMPORT_BOUNDARY'],['module-07',`${outWord} { basename } from 'node:path';`,'EXPORT_BOUNDARY'],['module-08',`const q=0; ${outWord} { basename } from 'node:path';`,'EXPORT_BOUNDARY'],['module-09',`/*x*/ ${outWord} { basename } from 'node:path';`,'EXPORT_BOUNDARY']];assert.equal(payloads.length,9);assert.equal(new Set(payloads.map(([label])=>label)).size,9);for(const [label,payload,token] of payloads)withScannerClone(label,payload,token);};
const assertActivationBoundaryCausal=()=>{const esc=decode([92]),globalObject=decode([103,108,111,98,97,108,84,104,105,115]),ctorWord=decode([99,111,110,115,116,114,117,99,116,111,114]),ctorTail=decode([115,116,114,117,99,116,111,114]),words={a:decode([101,118,97,108]),b:decode([115,112,97,119,110,83,121,110,99]),c:decode([101,120,101,99,83,121,110,99]),d:decode([101,120,101,99,70,105,108,101,83,121,110,99]),e:decode([102,111,114,107]),f:decode([112,114,111,99,101,115,115]),g:decode([103,101,116,66,117,105,108,116,105,110,77,111,100,117,108,101])},payloads=[['activation-01',`${words.a}("0");`],['activation-02',`cp.${words.b}("x");`],['activation-03',`cp[${JSON.stringify(words.c)}]("x");`],['activation-04',`const h=cp.${words.d};h("x");`],['activation-05',`const {${words.e}:h}=cp;h("x");`],['activation-06',`${words.f}.${words.g}("node:fs");`],['activation-07',`${esc}u0065val("0");`],['activation-08','const C="Func".concat("tion");C("return 0");'],['activation-09','const W=["Web","Assembly"].join("");W.compile(bytes);'],['activation-10','`${\\u0065val("0")}`;'],['activation-11','const g=["global","This"].join("");const e="ev".concat("al");({})[g][e]("0");'],['activation-12',`const e=\`e\\x76al\`;${globalObject}[e]("0");const f=\`Fun\\x63tion\`;${globalObject}[f]("return 0");`],['activation-13',[`const e=("xev"+"al").slice(1);${globalObject}[e]("0");`,`let r="noop";r="ev"+"al";${globalObject}[r]("0");`,`const q="ev\\`,`al";${globalObject}[q]("0");`,`\`\${(()=>{})["con"+"${ctorTail}"]("return 0")()}\`;`,`const {["con"+"${ctorTail}"]:C}=()=>{};C("return "+"pro"+"cess")();`,`const {${ctorWord}:C}=()=>{};C("return 0")();`,'const [C=(()=>{})]=[];C("return 0")();',`\`\${(()=>{const {["con"+"${ctorTail}"]:C}=()=>{};return C("return "+"pro"+"cess")()})()}\`;`,'`${\\u0065val("0")}`;','const {x:C}=(()=>{});(C)("return 0")();','const C=unknown;C?.("return 0")();','const C=unknown;C.call(null,"return 0");','const C=unknown;C.apply(null,["return 0"]);','const C=unknown;C.bind(null,"return 0")();','const {x:C}=(()=>{});C["call"](null,"return 0");','const ok=0,C=unknown;(C)("return 0")();','const C=unknown;(0,C)("return 0")();','const {x:C}=unknown,ok=0;C("return 0")();','let C;C=unknown;C("return 0")();','let C="safe";C+=unknown;C("return 0")();','let C=unknown;C++;C("return 0")();','function f(C){C("return 0");}'].join('\n')]];assert.equal(payloads.length,13);assert.equal(new Set(payloads.map(([label])=>label)).size,13);for(const [label,payload] of payloads)withScannerClone(label,payload,'ACTIVATION_BOUNDARY');};

test('source-unsealed closure and scanner causal suites validate',()=>{assert.deepEqual(validateStatic({packageRoot,mode:'unsealed'}),{files:27,directories:3,schemaCount:18,futureRecordSchemaCount:11,totalRecordCount:0,rootContentDigest:root.contentDigest.value,unsealed:true});assertCliCausal();assertModuleBoundaryCausal();assertActivationBoundaryCausal();});
test('root freezes eleven zero-record contracts',()=>{assert.equal(root.futureRecordContracts.recordKindCount,11);assert.equal(root.futureRecordContracts.totalRecordCount,0);assert.equal(root.futureRecordContracts.entries.length,11);assert.ok(root.futureRecordContracts.entries.every(row=>row.recordCount===0&&row.creationAllowed===false&&row.packageMayEmbedRecord===false));});
test('dependency and source authority pins remain constraint-only',()=>{assert.equal(root.dependencyBinding.directParent.dependencyId,'EAPP');assert.equal(root.dependencyBinding.sourceLanguageAuthority.dependencyId,'SSA');assert.deepEqual(root.dependencyBinding.sourceRoots.map(row=>row.authorityId),['EAC','B0R','UOPC','SPM']);assert.equal(root.eappV1Disposition.recordInstantiationAllowed,false);});
test('zero boundary and static topology are exact',()=>{assert.equal(root.controlPlaneTransition.authorizedTransitions.length,0);assert.equal(root.controlPlaneTransition.selectedDag,null);assert.equal(root.artifactDependencyDag.nodeCount,28);assert.equal(root.artifactDependencyDag.edgeCount,75);assert.ok(Object.entries(root.nonAuthorityBoundary).every(([key,value])=>key==='status'||key==='contentDigest'||value===0||value===false));});
