import { cpSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { assertP0Freeze, AUTHORED_FILES, SEALED_FILES, canonicalJson, componentDigest, deriveReviewAnchor, deriveSealEnvelope, parseValidationCliArgs, rawFileDigest, sha256, validateStatic } from '../validate-static.mjs';

const here=dirname(fileURLToPath(import.meta.url));
const packageRoot=resolve(here,'..');
const repositoryRoot=resolve(packageRoot,'../../../../..');
const options=parseValidationCliArgs(process.argv.slice(2));
if(options.mode!=='sealed')throw new Error('PRODUCTION_SEALED_MODE_REQUIRED');
const root=JSON.parse(readFileSync(resolve(packageRoot,'execution-admission-contract-root.v1.json'),'utf8'));
const kat=JSON.parse(readFileSync(resolve(here,'digest.kat.json'),'utf8'));
const expect=(name,run,prefix)=>{let error='';try{run();}catch(caught){error=String(caught.message);}if(!error.startsWith(prefix))throw new Error(`${name}: expected ${prefix}, got ${error}`);};
const copyPackage=target=>{mkdirSync(target,{recursive:true});for(const locator of AUTHORED_FILES){const destination=resolve(target,locator);mkdirSync(dirname(destination),{recursive:true});cpSync(resolve(packageRoot,locator),destination);}};
const writeJson=(path,value)=>writeFileSync(path,`${canonicalJson(value)}\n`,{mode:0o644});
const sealFixture=target=>{const envelope=deriveSealEnvelope(target);writeFileSync(resolve(target,'MANIFEST.json'),envelope.manifestBytes,{mode:0o644});writeFileSync(resolve(target,'SHA256SUMS'),envelope.sumsBytes,{mode:0o644});const copiedRoot=JSON.parse(readFileSync(resolve(target,'execution-admission-contract-root.v1.json'),'utf8'));const anchor=deriveReviewAnchor(target,envelope,copiedRoot);const anchorRoot=resolve(dirname(target),'outside');mkdirSync(anchorRoot,{recursive:true});const locator='review-anchor.json';const bytes=Buffer.from(`${canonicalJson(anchor)}\n`);writeFileSync(resolve(anchorRoot,locator),bytes,{mode:0o644});return {anchor,anchorRoot,locator,bytes,pin:{reviewAnchorRoot:anchorRoot,reviewAnchorLocator:locator,reviewAnchorBytes:bytes.length,reviewAnchorRawSha256:sha256(bytes)}};};
const rewriteAnchor=(fixture,transform)=>{const value=transform(JSON.parse(JSON.stringify(fixture.anchor)));const bytes=Buffer.from(`${canonicalJson(value)}\n`);writeFileSync(resolve(fixture.anchorRoot,fixture.locator),bytes,{mode:0o644});fixture.anchor=value;fixture.bytes=bytes;fixture.pin.reviewAnchorBytes=bytes.length;fixture.pin.reviewAnchorRawSha256=sha256(bytes);};
const refreshFixtureEnvelope=(fixture,target,semanticRoot,preserve={})=>{const envelope=deriveSealEnvelope(target);writeFileSync(resolve(target,'MANIFEST.json'),envelope.manifestBytes,{mode:0o644});writeFileSync(resolve(target,'SHA256SUMS'),envelope.sumsBytes,{mode:0o644});const anchor={...deriveReviewAnchor(target,envelope,semanticRoot),...preserve};rewriteAnchor(fixture,()=>anchor);};
const p0Prefix='research-lanes/bch-shielded-pool-design';
const p0ManifestLocator=`${p0Prefix}/spec/p0-freeze-manifest.json`;
const copyP0=target=>{const manifest=JSON.parse(readFileSync(resolve(repositoryRoot,p0ManifestLocator),'utf8'));const copy=(locator)=>{const destination=resolve(target,locator);mkdirSync(dirname(destination),{recursive:true});cpSync(resolve(repositoryRoot,locator),destination);};copy(p0ManifestLocator);for(const row of manifest.artifacts)copy(`${p0Prefix}/${row.path}`);return manifest;};
const loadP0FixtureValidator=async (directory,bytes,raw)=>{const source=readFileSync(resolve(packageRoot,'validate-static.mjs'),'utf8').replace("{bytes:2587,rawSha256:'a55ebd49f117956dc3b0c8a94cf3a3e7b40c5d7477de2a99c53d58bef00012c2'}",`{bytes:${bytes},rawSha256:'${raw}'}`);const locator=resolve(directory,'p0-fixture-validator.mjs');writeFileSync(locator,source,{mode:0o644});return import(`${pathToFileURL(locator).href}?p0=${raw}`);};

if(kat.cases.length!==12)throw new Error('KAT_COUNT');
for(const row of kat.cases){const actual=row.kind==='component'?componentDigest(row.domain,row.input):rawFileDigest(row.domain,Buffer.from(row.input));if(actual!==row.value)throw new Error(`KAT:${row.domain}`);}
if(!existsSync(resolve(packageRoot,'MANIFEST.json'))||!existsSync(resolve(packageRoot,'SHA256SUMS')))throw new Error('PRODUCTION_SEALED_ENVELOPES_REQUIRED');
const production=validateStatic({packageRoot,repositoryRoot,mode:options.mode,reviewAnchorPin:options.reviewAnchorPin});
if(production.files!==SEALED_FILES.length||production.sourcePins!==64||production.unsealed)throw new Error('SEALED_RESULT');
const cliNegatives=[[],['--mode','other'],['--mode','unsealed','--mode','unsealed'],['x'],['--mode','unsealed','--review-anchor-root','/tmp'],['--mode','sealed'],['--mode','sealed','--review-anchor-root','/tmp'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1','--review-anchor-raw-sha256','0'.repeat(64),'--review-anchor-root','/tmp'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1','--review-anchor-raw-sha256','0'.repeat(64),'--review-anchor-locator','x'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1','--review-anchor-raw-sha256','0'.repeat(64),'--review-anchor-bytes','1'],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1','--review-anchor-raw-sha256','0'.repeat(64),'--review-anchor-raw-sha256','0'.repeat(64)],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','../x','--review-anchor-bytes','1','--review-anchor-raw-sha256','0'.repeat(64)],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','01','--review-anchor-raw-sha256','0'.repeat(64)],['--mode','sealed','--review-anchor-root','/tmp','--review-anchor-locator','x','--review-anchor-bytes','1','--review-anchor-raw-sha256','A'.repeat(64)]];
for(const argv of cliNegatives)expect(`CLI:${argv.join(' ')}`,()=>parseValidationCliArgs(argv),'CLI_');
const temp=mkdtempSync(resolve(tmpdir(),'gb0eac-static-'));
let sealedNegativeCount=0;
try{
  const copy=resolve(temp,'package');copyPackage(copy);const sourceClone=validateStatic({packageRoot:copy,repositoryRoot,mode:'unsealed'});if(sourceClone.files!==AUTHORED_FILES.length||sourceClone.sourcePins!==64||!sourceClone.unsealed)throw new Error('SOURCE_CLONE_UNSEALED_RESULT');const fixture=sealFixture(copy);
  const sealed=validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:fixture.pin});if(sealed.files!==20||sealed.unsealed)throw new Error('SEALED_RESULT');
  writeFileSync(resolve(copy,'execution-admission-contract-root.v1.json'),'{}\n');refreshFixtureEnvelope(fixture,copy,root,{rootRawSha256:fixture.anchor.rootRawSha256});expect('anchor-first-root',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:fixture.pin}),'SEALED_ANCHOR_ROOT_RAW');sealedNegativeCount+=1;
  rmSync(copy,{recursive:true,force:true});copyPackage(copy);const manifestFixture=sealFixture(copy);const manifest=JSON.parse(readFileSync(resolve(copy,'MANIFEST.json'),'utf8'));manifest.entries[0].fileDigest.value='0'.repeat(64);writeJson(resolve(copy,'MANIFEST.json'),manifest);rewriteAnchor(manifestFixture,anchor=>({...anchor,manifestRawSha256:sha256(readFileSync(resolve(copy,'MANIFEST.json')))}));expect('manifest-file-digest-recompute',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:manifestFixture.pin}),'MANIFEST_RECOMPUTE');sealedNegativeCount+=1;
  rmSync(copy,{recursive:true,force:true});copyPackage(copy);const staleFixture=sealFixture(copy);writeFileSync(resolve(copy,'README.md'),`${readFileSync(resolve(copy,'README.md'),'utf8')}\n`);expect('stale-authored-leaf-preparse',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:staleFixture.pin}),'SEALED_ANCHOR_ORDERED_CLOSURE');sealedNegativeCount+=1;
  rmSync(copy,{recursive:true,force:true});copyPackage(copy);const schemaFixture=sealFixture(copy);writeFileSync(resolve(copy,'schemas/digest.v1.schema.json'),`${readFileSync(resolve(copy,'schemas/digest.v1.schema.json'),'utf8')}\n`);refreshFixtureEnvelope(schemaFixture,copy,root);expect('stale-schema-preparse',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:schemaFixture.pin}),'SCHEMA:schemas/digest.v1.schema.json:RAW');sealedNegativeCount+=1;
  rmSync(copy,{recursive:true,force:true});copyPackage(copy);const validatorFixture=sealFixture(copy);writeFileSync(resolve(copy,'validate-static.mjs'),`${readFileSync(resolve(copy,'validate-static.mjs'),'utf8')}\n`);refreshFixtureEnvelope(validatorFixture,copy,root,{validatorRawSha256:validatorFixture.anchor.validatorRawSha256});expect('anchor-first-validator',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:validatorFixture.pin}),'SEALED_ANCHOR_VALIDATOR_RAW');sealedNegativeCount+=1;
  rmSync(copy,{recursive:true,force:true});copyPackage(copy);const coordinated=sealFixture(copy);writeFileSync(resolve(copy,'validate-static.mjs'),'export const replaced=true;\n');writeFileSync(resolve(copy,'schemas/root.v1.schema.json'),'{}\n');writeFileSync(resolve(copy,'execution-admission-contract-root.v1.json'),'{}\n');refreshFixtureEnvelope(coordinated,copy,root,{rootRawSha256:coordinated.anchor.rootRawSha256});expect('coordinated-local-replacement-anchor',()=>validateStatic({packageRoot:copy,repositoryRoot,mode:'sealed',reviewAnchorPin:coordinated.pin}),'SEALED_ANCHOR_ROOT_RAW');sealedNegativeCount+=1;
  const p0Root=resolve(temp,'p0-repository');const p0Manifest=copyP0(p0Root);assertP0Freeze(p0Root);
  const p0Case=async (name,mutate,expected,{rePinManifest=true}={})=>{const fixture=resolve(temp,`p0-${name}`);cpSync(p0Root,fixture,{recursive:true});const manifestPath=resolve(fixture,p0ManifestLocator);const manifest=JSON.parse(readFileSync(manifestPath,'utf8'));mutate(manifest,fixture);if(rePinManifest)writeJson(manifestPath,manifest);const moduleDir=mkdtempSync(resolve(packageRoot,'test/.p0-validator-'));try{const manifestBytes=readFileSync(manifestPath);const validator=rePinManifest?await loadP0FixtureValidator(moduleDir,manifestBytes.length,sha256(manifestBytes)):{assertP0Freeze};expect(`P0:${name}`,()=>validator.assertP0Freeze(fixture),expected);}finally{rmSync(moduleDir,{recursive:true,force:true});}};
  await p0Case('leaf-count',manifest=>manifest.artifacts.pop(),'P0_LEAF_COUNT');
  await p0Case('leaf-traversal',manifest=>{manifest.artifacts[0].path='../escape';},'P0_LEAF_PATH:SEGMENT');
  await p0Case('leaf-duplicate',manifest=>{manifest.artifacts[1].path=manifest.artifacts[0].path;},'P0_LEAF_DUPLICATE');
  await p0Case('leaf-order',manifest=>manifest.artifacts.reverse(),'P0_LEAF_ORDER');
  await p0Case('aggregate',manifest=>{manifest.aggregate.sha256='0'.repeat(64);},'P0_AGGREGATE');
  await p0Case('leaf-raw',(manifest,fixture)=>writeFileSync(resolve(fixture,`${p0Prefix}/${manifest.artifacts[0].path}`),'drift'),`P0_LEAF:${p0Manifest.artifacts[0].path}:BYTES`,{rePinManifest:false});
}finally{rmSync(temp,{recursive:true,force:true});}
console.log(`PASS static production=sealed sourceClone=unsealed kat=${kat.cases.length} cliNegatives=${cliNegatives.length} sealedNegatives=${sealedNegativeCount} p0Negatives=6`);
