import test from 'node:test';
import assert from 'node:assert/strict';
import Ajv2020 from 'ajv/dist/2020.js';
import { createHash } from 'node:crypto';
import { chmodSync, copyFileSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AUTHORED_FILES, PREFIX, canonicalJson, digestRecord, validateStatic } from '../validate-static.mjs';

const here=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const gateRoot=dirname(here);
const rootLocator='external-authority-prerequisite-policy-root.v1.json';
const validatorLocator='validate-static.mjs';
const schemaPrefix='https://shieldkit-labs.local/p2/gate-b/gate-b0-external-authority-prerequisite-policy/v1/';
const packageId='gate-b0-external-authority-prerequisite-policy-v1';
const packagePath='research-lanes/bch-shielded-pool-design/p2/gate-b/gate-b0-external-authority-prerequisite-policy-v1';
const anchorSchema=`${PREFIX}/external-review-anchor/v1`;
const anchorStatus='sealed-static-external-authority-prerequisite-policy-review-anchor-no-governance-authorization-no-authority-bindings-no-instances-no-admission-no-execution-unqualified';
const anchorKeys=['schema','artifactId','packageId','package','status','rootRawSha256','rootContentDigest','validatorRawSha256','manifestRawSha256','sha256SumsRawSha256','entryCount','orderedClosure','rosterDigest','directDependencyBinding','componentDigests','schemaBindings','schemaBindingTableDigest','sourceCollisionDigest','nonAuthorityBoundary'];
const rootKeys=['schema','artifactId','packageId','status','purpose','executionAllowed','measurementAdmissionAllowed','dependencyBinding','governanceBoundary','authorityPolicyGroups','supplementalPolicies','requirementAuthorityMap','sourceCollisions','creationTransitionPolicy','providerBindingPolicy','futureGovernanceAuthorizationSchema','futureExternalAuthorityContractSchema','independenceConstraints','causalDag','nonAuthorityBoundary','runtimeBoundary','schemaBindings','componentDigests','contentDigest'];
const components=['governance','dependencyPins','transitiveSourcePins','ownerContractSourceCatalog','retryLineageSourceCatalog','privateCaptureSourceCatalog','workloadProjectionSourceCatalog','stateFactSourceCatalog','supplementalContracts','requirementResolutions','preauthorizationSemantics','nonAuthorityBoundary','runtimeBoundary','schemaBindings'];
const componentDomains=[['dependencyBinding','dependency-binding'],['governanceBoundary','governance-boundary'],['authorityPolicyGroups','authority-policy-groups'],['supplementalPolicies','supplemental-policies'],['requirementAuthorityMap','requirement-authority-map'],['sourceCollisions','source-collisions'],['creationTransitionPolicy','creation-transition-policy'],['providerBindingPolicy','provider-binding-policy'],['futureGovernanceAuthorizationSchema','future-governance-authorization-schema'],['futureExternalAuthorityContractSchema','future-external-authority-contract-schema'],['independenceConstraints','independence-constraints'],['causalDag','causal-dag'],['nonAuthorityBoundary','nonauthority-boundary'],['runtimeBoundary','runtime-boundary'],['schemaBindings','schema-bindings']];
const bindingPointers=[['/authorityPolicyGroups','/supplementalPolicies'],['/causalDag'],['/creationTransitionPolicy'],['/dependencyBinding'],['/componentDigests','/contentDigest'],['/futureExternalAuthorityContractSchema'],['/governanceBoundary','/futureGovernanceAuthorizationSchema','/sourceCollisions'],[],['/independenceConstraints','/nonAuthorityBoundary','/runtimeBoundary'],['/providerBindingPolicy'],['/requirementAuthorityMap'],['']];

const rootAndGovernance=[...rootKeys.map(key=>({id:`root/omit/${key}`,token:'ROOT_SCHEMA',mutate:root=>{delete root[key];}})),{id:'root/extra',token:'ROOT_SCHEMA',mutate:root=>{root.extra=true;}},{id:'root/status',token:'ROOT_SCHEMA',mutate:root=>{root.status='authorized';}},{id:'root/execution',token:'ROOT_SCHEMA',mutate:root=>{root.executionAllowed=true;}},{id:'root/measurement',token:'ROOT_SCHEMA',mutate:root=>{root.measurementAdmissionAllowed=true;}},{id:'governance/issuer',token:'NONAUTHORITY',mutate:root=>{root.governanceBoundary.governanceIssuerId='issuer';}},{id:'governance/decision',token:'NONAUTHORITY',mutate:root=>{root.governanceBoundary.governanceDecisionId='decision';}},{id:'governance/authorization-present',token:'NONAUTHORITY',mutate:root=>{root.governanceBoundary.authorizationPresent=true;}},{id:'governance/self-authorize',token:'NONAUTHORITY',mutate:root=>{root.governanceBoundary.packageMaySelfAuthorize=true;}}];
const dependency=[{id:'dependency/ssa-root-raw',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.root.rawSha256='0'.repeat(64);}},{id:'dependency/ssa-root-content',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.root.contentDigest='0'.repeat(64);}},{id:'dependency/validator-raw',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.validator.rawSha256='0'.repeat(64);}},{id:'dependency/manifest-raw',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.manifest.rawSha256='0'.repeat(64);}},{id:'dependency/sums-raw',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.checksums.rawSha256='0'.repeat(64);}},{id:'dependency/anchor-raw',token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.reviewAnchor.rawSha256='0'.repeat(64);}},...components.map((component,index)=>({id:`dependency/ssa-component/${component}`,token:'DEPENDENCY_SEMANTIC',mutate:root=>{root.dependencyBinding.ssaComponentDigests[index].digest.value='0'.repeat(64);}}))];
const policy=[...Array.from({length:10},(_,index)=>[{id:`group/${index}/authority-root`,token:'GROUP_SLOT',mutate:root=>{root.authorityPolicyGroups[index].authorityRoot='root';}},{id:`group/${index}/creation`,token:'ROOT_SCHEMA',mutate:root=>{root.authorityPolicyGroups[index].creationAllowed=true;}}]).flat(),{id:'supplemental/0/implementation',token:'SUPPLEMENTAL',mutate:root=>{root.supplementalPolicies[0].implementationLocator='map.mjs';}},{id:'supplemental/0/creation',token:'ROOT_SCHEMA',mutate:root=>{root.supplementalPolicies[0].authorityCreationAllowed=true;}},{id:'supplemental/1/implementation',token:'SUPPLEMENTAL',mutate:root=>{root.supplementalPolicies[1].implementationLocator='validator.mjs';}},{id:'supplemental/1/evaluation',token:'ROOT_SCHEMA',mutate:root=>{root.supplementalPolicies[1].evaluationAllowed=true;}}];
const requirements=Array.from({length:30},(_,index)=>({id:`requirement/${index}/instance-count`,token:'ROOT_SCHEMA',mutate:root=>{root.requirementAuthorityMap[index].instanceCount=1;}}));
const collision=[{id:'collision/delete',token:'COLLISION_COUNTS',mutate:root=>{root.sourceCollisions.entries=[];}},{id:'collision/add',token:'COLLISION_COUNTS',mutate:root=>{root.sourceCollisions.entries.push(structuredClone(root.sourceCollisions.entries[0]));}},{id:'collision/status',token:'COLLISION_COUNTS',mutate:root=>{root.sourceCollisions.status='RESOLVED';}},{id:'collision/selected-dag',token:'COLLISION_SELECTION',mutate:root=>{root.sourceCollisions.entries[0].selectedDag='UOPC';}},{id:'collision/selected-a',token:'COLLISION_SELECTION',mutate:root=>{root.sourceCollisions.entries[0].selectedAPath='retry';}},{id:'collision/resolution',token:'ROOT_SCHEMA',mutate:root=>{root.sourceCollisions.entries[0].reconciliationPrerequisite.resolutionAllowed=true;}},{id:'collision/infer',token:'ROOT_SCHEMA',mutate:root=>{root.sourceCollisions.entries[0].reconciliationPrerequisite.packageMayInfer=true;}},{id:'collision/select',token:'ROOT_SCHEMA',mutate:root=>{root.sourceCollisions.entries[0].reconciliationPrerequisite.packageMaySelectSource=true;}},{id:'collision/decision-root',token:'COLLISION_SELECTION',mutate:root=>{root.sourceCollisions.entries[0].reconciliationPrerequisite.governanceDecisionRoot='root';}},{id:'collision/affected-reorder',token:'COLLISION_COUNTS',mutate:root=>{root.sourceCollisions.entries[0].affectedRequirementIds.reverse();}}];
const transitionBindingFutureRuntime=[{id:'transition/current',token:'ROOT_SCHEMA',mutate:root=>{root.creationTransitionPolicy.currentState='EXTERNAL_AUTHORITY_CONTRACTS_PINNED_NO_INSTANCES';}},{id:'transition/authorized',token:'ROOT_SCHEMA',mutate:root=>{root.creationTransitionPolicy.authorizedTransitions.push('SOURCE_LANGUAGE_RESOLVED→AUTHORITY_POLICY_FROZEN_NO_AUTHORITY');}},{id:'transition/automatic',token:'ROOT_SCHEMA',mutate:root=>{root.creationTransitionPolicy.automaticTransitionAllowed=true;}},{id:'transition/downgrade',token:'ROOT_SCHEMA',mutate:root=>{root.creationTransitionPolicy.downgradeAllowed=true;}},{id:'transition/attempt001',token:'ROOT_SCHEMA',mutate:root=>{root.creationTransitionPolicy.attempt001Allowed=true;}},{id:'binding/count',token:'ROOT_SCHEMA',mutate:root=>{root.providerBindingPolicy.bindingCount=1;}},{id:'binding/root',token:'BINDING_POLICY',mutate:root=>{root.providerBindingPolicy.bindingCatalogRoot='root';}},{id:'binding/self-attestation',token:'ROOT_SCHEMA',mutate:root=>{root.providerBindingPolicy.selfAttestationAllowed=true;}},{id:'governance/record-count',token:'ROOT_SCHEMA',mutate:root=>{root.futureGovernanceAuthorizationSchema.recordCount=1;}},{id:'contract/record-count',token:'ROOT_SCHEMA',mutate:root=>{root.futureExternalAuthorityContractSchema.recordCount=1;}},{id:'contract/creation',token:'ROOT_SCHEMA',mutate:root=>{root.futureExternalAuthorityContractSchema.creationAllowed=true;}},{id:'runtime/entrypoint',token:'RUNTIME_BOUNDARY',mutate:root=>{root.runtimeBoundary.runtimeEntrypoint='run.mjs';}}];
const partitions={rootAndGovernance,dependency,policy,requirements,collision,transitionBindingFutureRuntime};
const cases=Object.values(partitions).flat();
const structuralEndpointCases=[...Array.from({length:31},(_,index)=>['from','to'].map(field=>({id:`dag-edge-${String(index).padStart(2,'0')}-${field}`,token:'DAG',mutate:root=>{const nodes=root.causalDag.nodes,current=root.causalDag.edges[index][field],next=nodes[(nodes.indexOf(current)+1)%nodes.length];root.causalDag.edges[index][field]=next;}}))).flat(),...Array.from({length:5},(_,index)=>['from','to'].map(field=>({id:`transition-edge-${String(index).padStart(2,'0')}-${field}`,token:'TRANSITION',mutate:root=>{const states=root.creationTransitionPolicy.states,current=root.creationTransitionPolicy.edges[index][field],next=states[(states.indexOf(current)+1)%states.length];root.creationTransitionPolicy.edges[index][field]=next;}}))).flat()];

const clonePackage=()=>{const clone=mkdtempSync(resolve(gateRoot,'.eapp-mutation-'));chmodSync(clone,0o755);mkdirSync(resolve(clone,'schemas'),{mode:0o755});mkdirSync(resolve(clone,'test'),{mode:0o755});for(const locator of AUTHORED_FILES){copyFileSync(resolve(here,locator),resolve(clone,locator));chmodSync(resolve(clone,locator),0o644);}return clone;};
const redigestLeaf=(row,domain)=>{const value={...row};delete value.contentDigest;row.contentDigest=digestRecord(domain,value);};
const redigestRoot=root=>{for(const row of root.authorityPolicyGroups??[])redigestLeaf(row,`${PREFIX}/authority-policy-group/${row.policyGroupId}`);for(const row of root.supplementalPolicies??[])redigestLeaf(row,`${PREFIX}/supplemental-policy/${row.policyId}`);for(const row of root.requirementAuthorityMap??[])redigestLeaf(row,`${PREFIX}/requirement-authority-map/${row.requirementId}`);if(root.sourceCollisions?.entries)for(const row of root.sourceCollisions.entries)redigestLeaf(row,`${PREFIX}/source-collision/${row.collisionId}`);if(root.sourceCollisions?.contentDigest)redigestLeaf(root.sourceCollisions,`${PREFIX}/source-collisions`);if(root.creationTransitionPolicy?.contentDigest)redigestLeaf(root.creationTransitionPolicy,`${PREFIX}/creation-transition-policy`);if(Array.isArray(root.componentDigests))root.componentDigests=componentDomains.filter(([component])=>Object.hasOwn(root,component)).map(([component,suffix])=>({component,digest:digestRecord(`${PREFIX}/${suffix}`,root[component])}));if(root.contentDigest){const value={...root};delete value.contentDigest;root.contentDigest=digestRecord(`${PREFIX}/root`,value);}return root;};
const writeRoot=(packageRoot,root)=>{redigestRoot(root);writeFileSync(resolve(packageRoot,rootLocator),`${canonicalJson(root)}\n`,{mode:0o644});};
function sha256(bytes){return createHash('sha256').update(bytes).digest('hex');}
const a0RootRaw='870a8e1ea607735c9326e7ceeb4ea3e22ff2bf53cac8648c199d70a65fdd6904';
const a0RootBytes=86088;
const a0ValidatorRaw='43952a537b828c0d74fc4d4101e3dd9c952ac033e753dc6bbb6738e15e8dd6df';
const SAME_WIDTH_REPLACEMENT_BYTES=100000;
const expectedA0Raw=Object.fromEntries(AUTHORED_FILES.map(locator=>[locator,locator===validatorLocator?a0ValidatorRaw:sha256(readFileSync(resolve(here,locator)))]));
const exportWord=['ex','port'].join('');
const installLocalValidator=(packageRoot,id,rootRawSha256,root,{targetBytes=null}={})=>{const h1Schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:`urn:eapp:a1:${id}`,const:root},render=()=>`${exportWord} const A1_CASE_ID=${JSON.stringify(id)};\n${exportWord} const A1_ROOT_BYTES=${readFileSync(resolve(packageRoot,rootLocator)).length};\n${exportWord} const A1_ROOT_RAW_SHA256=${JSON.stringify(rootRawSha256)};\n${exportWord} const A1_ROOT_SCHEMA=${JSON.stringify(h1Schema)};\n`;let source=render();if(targetBytes!==null){assert.equal(Number.isSafeInteger(targetBytes)&&targetBytes>0,true,`${id}: replacement validator target bytes`);h1Schema.$comment='';const overhead=Buffer.byteLength(render())-Buffer.byteLength(source),padding=targetBytes-Buffer.byteLength(source)-overhead;assert.equal(padding>=0,true,`${id}: replacement validator padding`);h1Schema.$comment='x'.repeat(padding);source=render();assert.equal(Buffer.byteLength(source),targetBytes,`${id}: exact replacement validator bytes`);}writeFileSync(resolve(packageRoot,validatorLocator),source,{mode:0o644});return {bytes:Buffer.from(source),h1Schema};};
const walk=(root,relative='')=>readdirSync(resolve(root,relative),{withFileTypes:true}).flatMap(entry=>{const locator=relative?`${relative}/${entry.name}`:entry.name;return entry.isDirectory()?[{kind:'directory',locator},...walk(root,locator)]:[{kind:entry.isFile()?'file':entry.isSymbolicLink()?'link':'special',locator}];});
const allStringsNfc=value=>typeof value==='string'?value.normalize('NFC')===value:Array.isArray(value)?value.every(allStringsNfc):value&&typeof value==='object'?Object.entries(value).every(([key,item])=>key.normalize('NFC')===key&&allStringsNfc(item)):true;
const strictJson=(bytes,label)=>{
  const source=bytes.toString('utf8');
  assert.equal(Buffer.from(source,'utf8').equals(bytes),true,`${label}: strict UTF-8`);
  let index=0;
  const skip=()=>{while(/[ \t\r\n]/u.test(source[index]??''))index+=1;};
  const string=()=>{const start=index;assert.equal(source[index++],'"',`${label}: JSON string`);while(index<source.length){const char=source[index++];if(char==='\\'){assert.equal(index<source.length,true,`${label}: JSON escape`);if(source[index++]==='u')index+=4;}else if(char==='"')return JSON.parse(source.slice(start,index));else assert.equal(char.charCodeAt(0)>=0x20,true,`${label}: JSON control`);}assert.fail(`${label}: unterminated JSON string`);};
  const value=()=>{skip();const token=source[index];if(token==='{'){index+=1;skip();const keys=new Set();if(source[index]==='}'){index+=1;return;}for(;;){skip();const key=string();assert.equal(keys.has(key),false,`${label}: duplicate key ${key}`);keys.add(key);skip();assert.equal(source[index++],':',`${label}: JSON colon`);value();skip();if(source[index]==='}'){index+=1;return;}assert.equal(source[index++],',',`${label}: JSON comma`);}}else if(token==='['){index+=1;skip();if(source[index]===']'){index+=1;return;}for(;;){value();skip();if(source[index]===']'){index+=1;return;}assert.equal(source[index++],',',`${label}: JSON comma`);}}else if(token==='"')string();else{const literal=['true','false','null'].find(item=>source.startsWith(item,index));if(literal)index+=literal.length;else{const number=source.slice(index).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/u);assert.ok(number,`${label}: JSON scalar`);index+=number[0].length;}}};
  value();skip();assert.equal(index,source.length,`${label}: JSON trailing bytes`);
  const parsed=JSON.parse(source);
  assert.equal(allStringsNfc(parsed),true,`${label}: NFC`);
  assert.equal(source,`${canonicalJson(parsed)}\n`,`${label}: canonical JSON`);
  return parsed;
};
const pointerAt=(document,fragment,label)=>{assert.match(fragment,/^\/(?:[^/]+(?:\/[^/]+)*)?$/u,`${label}: JSON pointer`);let cursor=document;for(const encoded of fragment.slice(1).split('/').filter(Boolean)){const key=encoded.replaceAll('~1','/').replaceAll('~0','~');assert.equal(cursor!==null&&typeof cursor==='object'&&Object.hasOwn(cursor,key),true,`${label}: resolved pointer ${fragment}`);cursor=cursor[key];}return cursor;};
const assertSchemaGraph=(schemas,id)=>{
  const byId=new Map(schemas.map(schema=>[schema.$id,schema]));
  assert.equal(byId.size,12,`${id}: distinct schema IDs`);
  const reached=new Set(),visitedRefs=new Set();
  const visit=(schemaId,node)=>{if(!node||typeof node!=='object')return;if(Array.isArray(node)){for(const item of node)visit(schemaId,item);return;}if(typeof node.$ref==='string'){const marker=`${schemaId}|${node.$ref}`;if(!visitedRefs.has(marker)){visitedRefs.add(marker);const cut=node.$ref.indexOf('#'),targetId=cut<0?node.$ref:node.$ref.slice(0,cut),fragment=cut<0?'':node.$ref.slice(cut+1),resolvedId=targetId||schemaId,target=byId.get(resolvedId);assert.ok(target,`${id}: local schema target ${node.$ref}`);assert.match(fragment,/^\/\$defs\/[^/]+(?:\/.*)?$/u,`${id}: active definition ref ${node.$ref}`);const defName=fragment.split('/')[2].replaceAll('~1','/').replaceAll('~0','~');assert.equal(Object.hasOwn(target.$defs??{},defName),true,`${id}: defined fragment ${node.$ref}`);reached.add(`${resolvedId}#/$defs/${defName}`);visit(resolvedId,pointerAt(target,fragment,`${id}: ${node.$ref}`));}}for(const [key,child] of Object.entries(node))if(key!=='$defs'&&key!=='$ref')visit(schemaId,child);};
  for(const schema of schemas)visit(schema.$id,schema);
  const defined=schemas.flatMap(schema=>Object.keys(schema.$defs??{}).map(name=>`${schema.$id}#/$defs/${name}`)).sort();
  assert.deepEqual([...reached].sort(),defined,`${id}: no unused active definitions`);
};
const stripMechanicalDigests=value=>{const copy=structuredClone(value);delete copy.contentDigest;delete copy.componentDigests;for(const row of copy.authorityPolicyGroups??[])delete row.contentDigest;for(const row of copy.supplementalPolicies??[])delete row.contentDigest;for(const row of copy.requirementAuthorityMap??[])delete row.contentDigest;if(copy.sourceCollisions){delete copy.sourceCollisions.contentDigest;for(const row of copy.sourceCollisions.entries??[])delete row.contentDigest;}if(copy.creationTransitionPolicy)delete copy.creationTransitionPolicy.contentDigest;return copy;};
const primaryDiffPaths=(left,right,path='')=>{if(canonicalJson(left)===canonicalJson(right))return [];if(Array.isArray(left)||Array.isArray(right)||left===null||right===null||typeof left!=='object'||typeof right!=='object')return [path||'/'];const keys=[...new Set([...Object.keys(left),...Object.keys(right)])].sort(),changes=[];for(const key of keys){const child=`${path}/${key.replaceAll('~','~0').replaceAll('/','~1')}`;if(!Object.hasOwn(left,key)||!Object.hasOwn(right,key))changes.push(child);else changes.push(...primaryDiffPaths(left[key],right[key],child));}return changes;};
const localFileDigest=(locator,bytes)=>{const domain=`${PREFIX}/file/${locator}`;return {algorithm:'sha256',canonicalization:'raw-file-bytes-v1',domain,frame:'utf8(domain)||0x00||raw-file-bytes',value:sha256(Buffer.concat([Buffer.from(domain),Buffer.from([0]),bytes]))};};
const localEnvelope=packageRoot=>{const entries=AUTHORED_FILES.map(locator=>{const bytes=readFileSync(resolve(packageRoot,locator));return {bytes:bytes.length,fileDigest:localFileDigest(locator,bytes),locator,rawSha256:sha256(bytes)};}),rosterDigest=digestRecord(`${PREFIX}/manifest-roster`,entries),manifest={schema:`${schemaPrefix}manifest.v1.schema.json`,format:'shieldkit-static-manifest-v1',packageId,entryCount:21,entries,rosterDigest},manifestBytes=Buffer.from(`${canonicalJson(manifest)}\n`),sumsBytes=Buffer.from(`${[...entries,{locator:'MANIFEST.json',rawSha256:sha256(manifestBytes)}].map(row=>`${row.rawSha256}  ${row.locator}`).join('\n')}\n`);return {entries,manifest,manifestBytes,sumsBytes};};
const localAnchor=({root,validatorRawSha256,envelope})=>({schema:anchorSchema,artifactId:'artifact:gate-b:gate-b0-external-authority-prerequisite-policy-review-anchor-v1',packageId,package:packagePath,status:anchorStatus,rootRawSha256:sha256(Buffer.from(`${canonicalJson(root)}\n`)),rootContentDigest:root.contentDigest,validatorRawSha256,manifestRawSha256:sha256(envelope.manifestBytes),sha256SumsRawSha256:sha256(envelope.sumsBytes),entryCount:21,orderedClosure:envelope.entries,rosterDigest:envelope.manifest.rosterDigest,directDependencyBinding:root.dependencyBinding,componentDigests:root.componentDigests,schemaBindings:root.schemaBindings,schemaBindingTableDigest:digestRecord(`${PREFIX}/schema-binding-table`,root.schemaBindings),sourceCollisionDigest:root.componentDigests.find(row=>row.component==='sourceCollisions').digest,nonAuthorityBoundary:root.nonAuthorityBoundary});
const installSealedFixture=(packageRoot,anchorRoot,locator)=>{const envelope=localEnvelope(packageRoot);writeFileSync(resolve(packageRoot,'MANIFEST.json'),envelope.manifestBytes,{mode:0o644});writeFileSync(resolve(packageRoot,'SHA256SUMS'),envelope.sumsBytes,{mode:0o644});const root=strictJson(readFileSync(resolve(packageRoot,rootLocator)),'sealed fixture root'),anchor=localAnchor({root,validatorRawSha256:sha256(readFileSync(resolve(packageRoot,validatorLocator))),envelope}),anchorBytes=Buffer.from(`${canonicalJson(anchor)}\n`);writeFileSync(resolve(anchorRoot,locator),anchorBytes,{mode:0o644});return {anchor,anchorBytes,envelope,pin:{reviewAnchorRoot:anchorRoot,reviewAnchorLocator:locator,reviewAnchorBytes:anchorBytes.length,reviewAnchorRawSha256:sha256(anchorBytes)}};};
const validateSealedA1=({packageRoot,anchorRoot,locator,fixture,id})=>{const tree=walk(packageRoot),files=tree.filter(row=>row.kind==='file').map(row=>row.locator).sort(),dirs=['.',...tree.filter(row=>row.kind==='directory').map(row=>row.locator)].sort();assert.deepEqual(files,[...AUTHORED_FILES,'MANIFEST.json','SHA256SUMS'].sort(),`${id}: sealed A1 closure`);assert.deepEqual(dirs,['.','schemas','test'],`${id}: sealed A1 dirs`);for(const dir of dirs){const stat=lstatSync(resolve(packageRoot,dir));assert.equal(stat.isDirectory()&&!stat.isSymbolicLink()&&(stat.mode&0o777)===0o755,true,`${id}: sealed directory ${dir}`);}for(const file of files){const stat=lstatSync(resolve(packageRoot,file));assert.equal(stat.isFile()&&!stat.isSymbolicLink()&&stat.nlink===1&&(stat.mode&0o777)===0o644,true,`${id}: sealed file ${file}`);}const anchorStat=lstatSync(resolve(anchorRoot,locator));assert.equal(anchorStat.isFile()&&!anchorStat.isSymbolicLink()&&anchorStat.nlink===1&&(anchorStat.mode&0o777)===0o644,true,`${id}: outside anchor metadata`);const independent=localEnvelope(packageRoot);assert.equal(readFileSync(resolve(packageRoot,'MANIFEST.json')).equals(independent.manifestBytes),true,`${id}: A1 manifest`);assert.equal(readFileSync(resolve(packageRoot,'SHA256SUMS')).equals(independent.sumsBytes),true,`${id}: A1 sums`);const anchorBytes=readFileSync(resolve(anchorRoot,locator)),anchor=strictJson(anchorBytes,`${id}: A1 anchor`),root=strictJson(readFileSync(resolve(packageRoot,rootLocator)),`${id}: A1 sealed root`),expected=localAnchor({root,validatorRawSha256:sha256(readFileSync(resolve(packageRoot,validatorLocator))),envelope:independent});assert.deepEqual(Object.keys(anchor),[...anchorKeys].sort(),`${id}: exact canonical anchor key roster`);assert.deepEqual(anchor,expected,`${id}: exact A1 anchor`);assert.equal(anchorBytes.length,fixture.pin.reviewAnchorBytes,`${id}: A1 anchor bytes pin`);assert.equal(sha256(anchorBytes),fixture.pin.reviewAnchorRawSha256,`${id}: A1 anchor raw pin`);return true;};
const validateLocalA1=({packageRoot,id,rootRawSha256,validatorBytes,h1Schema,a0SchemaBindings,a0Root,primaryRoot,primaryPaths,h1FilePins})=>{
  const tree=walk(packageRoot),files=tree.filter(row=>row.kind==='file').map(row=>row.locator).sort(),dirs=['.',...tree.filter(row=>row.kind==='directory').map(row=>row.locator)].sort();
  assert.equal(tree.every(row=>row.kind==='file'||row.kind==='directory'),true,`${id}: local A1 regular closure`);
  assert.deepEqual(files,[...AUTHORED_FILES].sort(),`${id}: local A1 file closure`);
  assert.deepEqual(dirs,['.','schemas','test'],`${id}: local A1 directory closure`);
  for(const dir of dirs){const stat=lstatSync(resolve(packageRoot,dir));assert.equal(stat.isDirectory()&&!stat.isSymbolicLink()&&(stat.mode&0o777)===0o755,true,`${id}: local A1 directory metadata ${dir}`);}
  for(const locator of files){const stat=lstatSync(resolve(packageRoot,locator));assert.equal(stat.isFile()&&!stat.isSymbolicLink()&&stat.nlink===1,true,`${id}: local A1 regular nlink1 ${locator}`);assert.equal(stat.mode&0o777,0o644,`${id}: local A1 file mode ${locator}`);}
  const rootBytes=readFileSync(resolve(packageRoot,rootLocator)),root=strictJson(rootBytes,`${id}: root`);
  assert.equal(sha256(rootBytes),rootRawSha256,`${id}: local A1 root raw pin`);
  const validatorRaw=readFileSync(resolve(packageRoot,validatorLocator)),expectedSource=`${exportWord} const A1_CASE_ID=${JSON.stringify(id)};\n${exportWord} const A1_ROOT_BYTES=${rootBytes.length};\n${exportWord} const A1_ROOT_RAW_SHA256=${JSON.stringify(rootRawSha256)};\n${exportWord} const A1_ROOT_SCHEMA=${JSON.stringify(h1Schema)};\n`;
  assert.equal(validatorRaw.equals(validatorBytes)&&validatorRaw.equals(Buffer.from(expectedSource)),true,`${id}: exact inert replacement validator`);
  const h1Pattern=new RegExp(String.raw`^${exportWord} const A1_CASE_ID=.*;\n${exportWord} const A1_ROOT_BYTES=[1-9][0-9]*;\n${exportWord} const A1_ROOT_RAW_SHA256="[0-9a-f]{64}";\n${exportWord} const A1_ROOT_SCHEMA=\{.*\};\n$`,'u');
  assert.match(expectedSource,h1Pattern,`${id}: replacement validator template`);
  const actualChanged=AUTHORED_FILES.filter(locator=>sha256(readFileSync(resolve(packageRoot,locator)))!==expectedA0Raw[locator]).map(locator=>{const bytes=readFileSync(resolve(packageRoot,locator));return {bytes:bytes.length,locator,rawSha256:sha256(bytes)};});
  assert.deepEqual(actualChanged,h1FilePins,`${id}: exact H1 changed-file pins`);
  assert.deepEqual(actualChanged.map(row=>row.locator),[rootLocator,validatorLocator],`${id}: root and replacement validator only`);
  const schemas=[];
  assert.deepEqual(a0SchemaBindings.map(binding=>binding.locator),AUTHORED_FILES.filter(locator=>locator.startsWith('schemas/')),`${id}: schema binding locator roster`);
  for(const [index,binding] of a0SchemaBindings.entries()){const bytes=readFileSync(resolve(packageRoot,binding.locator)),schema=strictJson(bytes,`${id}: ${binding.locator}`);assert.equal(schema.$id,`${schemaPrefix}${binding.locator.slice(8)}`,`${id}: schema id ${binding.locator}`);assert.equal(schema.$id,binding.schemaId,`${id}: binding schema id ${binding.locator}`);assert.equal(sha256(bytes),binding.rawSha256,`${id}: schema raw ${binding.locator}`);assert.deepEqual(binding.rootJsonPointers,bindingPointers[index],`${id}: schema pointers ${binding.locator}`);schemas.push(schema);}
  assertSchemaGraph(schemas,id);
  const ajv=new Ajv2020({strict:true}),validate=ajv.compile(h1Schema);
  assert.equal(validate(root),true,`${id}: H1 const schema positive`);
  assert.deepEqual(primaryDiffPaths(a0Root,primaryRoot),primaryPaths,`${id}: stable primary mutation path`);
  assert.equal(primaryPaths.length,1,`${id}: exactly one primary semantic mutation`);
  assert.equal(canonicalJson(stripMechanicalDigests(root)),canonicalJson(stripMechanicalDigests(primaryRoot)),`${id}: only mechanical digest repairs`);
  for(const row of root.authorityPolicyGroups??[])redigestCheck(row,`${PREFIX}/authority-policy-group/${row.policyGroupId}`,id);for(const row of root.supplementalPolicies??[])redigestCheck(row,`${PREFIX}/supplemental-policy/${row.policyId}`,id);for(const row of root.requirementAuthorityMap??[])redigestCheck(row,`${PREFIX}/requirement-authority-map/${row.requirementId}`,id);for(const row of root.sourceCollisions?.entries??[])redigestCheck(row,`${PREFIX}/source-collision/${row.collisionId}`,id);if(root.sourceCollisions?.contentDigest)redigestCheck(root.sourceCollisions,`${PREFIX}/source-collisions`,id);if(root.creationTransitionPolicy?.contentDigest)redigestCheck(root.creationTransitionPolicy,`${PREFIX}/creation-transition-policy`,id);if(root.componentDigests)assert.deepEqual(root.componentDigests,componentDomains.filter(([component])=>Object.hasOwn(root,component)).map(([component,suffix])=>({component,digest:digestRecord(`${PREFIX}/${suffix}`,root[component])})),`${id}: component digests`);if(root.contentDigest){const value={...root};delete value.contentDigest;assert.deepEqual(root.contentDigest,digestRecord(`${PREFIX}/root`,value),`${id}: root digest`);}
  return {caseId:id,rootRawSha256,changedFiles:h1FilePins};
};
const redigestCheck=(row,domain,id)=>{const value={...row};delete value.contentDigest;assert.deepEqual(row.contentDigest,digestRecord(domain,value),`${id}: ${domain}`);};
const expectedMessage=spec=>spec.token==='NONAUTHORITY'?`EAPP_NONAUTHORITY:governanceBoundary`:spec.token==='DEPENDENCY_SEMANTIC'?`EAPP_DEPENDENCY_SEMANTIC:literal`:`EAPP_${spec.token}`;
const exactError=spec=>error=>error instanceof Error&&error.message===expectedMessage(spec);

const runCase=spec=>{const packageRoot=clonePackage();try{
  for(const locator of AUTHORED_FILES)assert.equal(sha256(readFileSync(resolve(packageRoot,locator))),expectedA0Raw[locator],`${spec.id}: A0 ${locator}`);
  const a0RootBytesActual=readFileSync(resolve(packageRoot,rootLocator));
  assert.equal(a0RootBytesActual.length,a0RootBytes,`${spec.id}: literal H0 root bytes`);
  assert.equal(sha256(a0RootBytesActual),a0RootRaw,`${spec.id}: literal H0 root raw`);
  assert.equal(expectedA0Raw[validatorLocator],a0ValidatorRaw,`${spec.id}: literal H0 validator raw`);
  const root=strictJson(a0RootBytesActual,`${spec.id}: A0 root`),a0=structuredClone(root),a0SchemaBindings=structuredClone(root.schemaBindings);
  spec.mutate(root);
  const primaryRoot=structuredClone(root),primaryPaths=primaryDiffPaths(a0,primaryRoot);
  assert.equal(primaryPaths.length,1,`${spec.id}: one declared primary mutation`);
  writeRoot(packageRoot,root);
  const rootBytesActual=readFileSync(resolve(packageRoot,rootLocator)),rootRawSha256=sha256(rootBytesActual),replacement=installLocalValidator(packageRoot,spec.id,rootRawSha256,root);
  const h1FilePins=AUTHORED_FILES.filter(locator=>sha256(readFileSync(resolve(packageRoot,locator)))!==expectedA0Raw[locator]).map(locator=>{const bytes=readFileSync(resolve(packageRoot,locator));return {bytes:bytes.length,locator,rawSha256:sha256(bytes)};});
  const local=validateLocalA1({packageRoot,id:spec.id,rootRawSha256,validatorBytes:replacement.bytes,h1Schema:replacement.h1Schema,a0SchemaBindings,a0Root:a0,primaryRoot,primaryPaths,h1FilePins});
  assert.equal(local.caseId,spec.id,`${spec.id}: H1 local A1 positive`);
  assert.deepEqual(local.changedFiles,h1FilePins,`${spec.id}: H1 file-pin result`);
  for(const locator of AUTHORED_FILES.filter(locator=>locator!==rootLocator&&locator!==validatorLocator))assert.equal(sha256(readFileSync(resolve(packageRoot,locator))),expectedA0Raw[locator],`${spec.id}: unchanged ${locator}`);
  assert.throws(()=>validateStatic({packageRoot,mode:'unsealed'}),exactError(spec),spec.id);
}finally{rmSync(packageRoot,{recursive:true,force:true});}};

test('exact 128 full-clone causal mutations',()=>{assert.deepEqual(Object.fromEntries(Object.entries(partitions).map(([key,value])=>[key,value.length])),{rootAndGovernance:32,dependency:20,policy:24,requirements:30,collision:10,transitionBindingFutureRuntime:12});assert.equal(cases.length,128);assert.equal(new Set(cases.map(spec=>spec.id)).size,128);assert.deepEqual(Object.fromEntries([...new Set(cases.map(spec=>spec.token))].map(token=>[token,cases.filter(spec=>spec.token===token).length])),{ROOT_SCHEMA:83,NONAUTHORITY:4,DEPENDENCY_SEMANTIC:20,GROUP_SLOT:10,SUPPLEMENTAL:2,COLLISION_COUNTS:4,COLLISION_SELECTION:3,BINDING_POLICY:1,RUNTIME_BOUNDARY:1});for(const spec of cases)runCase(spec);});
test('exact 72 structural endpoint negatives',()=>{assert.equal(structuralEndpointCases.length,72);assert.equal(new Set(structuralEndpointCases.map(spec=>spec.id)).size,72);for(const spec of structuralEndpointCases)runCase(spec);});
test('sealed coordinated replacement retains external H0 anchor pin',()=>{
  const packageRoot=clonePackage(),anchorRoot=mkdtempSync(resolve(gateRoot,'.eapp-mutation-anchor-')),locator='review-anchor.json';
  chmodSync(anchorRoot,0o755);
  try{
    const h0=installSealedFixture(packageRoot,anchorRoot,locator);
    assert.equal(validateSealedA1({packageRoot,anchorRoot,locator,fixture:h0,id:'coordinated/H0'}),true,'genuine sealed H0 positive control');
    assert.deepEqual(validateStatic({packageRoot,repositoryRoot:resolve(here,'../../../../..'),mode:'sealed',reviewAnchorPin:h0.pin}),{files:23,directories:3,rootDigest:strictJson(readFileSync(resolve(packageRoot,rootLocator)),'production H0 root').contentDigest.value,sourceContracts:10,unsealed:false},'production validator sealed H0 positive control');
    rmSync(resolve(packageRoot,'MANIFEST.json'));
    rmSync(resolve(packageRoot,'SHA256SUMS'));
    const root=strictJson(readFileSync(resolve(packageRoot,rootLocator)),'coordinated A0 root'),a0=structuredClone(root),a0SchemaBindings=structuredClone(root.schemaBindings);
    root.purpose=root.purpose.endsWith('them')?`${root.purpose.slice(0,-4)}this`:`${root.purpose}x`;
    let primaryRoot=structuredClone(root),primaryPaths=primaryDiffPaths(a0,primaryRoot);
    writeRoot(packageRoot,root);
    assert.equal(readFileSync(resolve(packageRoot,rootLocator)).length,a0RootBytes,'same-width coordinated root');
    const productionValidatorBytes=readFileSync(resolve(packageRoot,validatorLocator)).length;
    assert.equal(String(productionValidatorBytes).length,6,'production validator byte count has six decimal digits');
    assert.equal(String(SAME_WIDTH_REPLACEMENT_BYTES).length,6,'replacement validator byte count has six decimal digits');
    const rootRawSha256=sha256(readFileSync(resolve(packageRoot,rootLocator))),replacement=installLocalValidator(packageRoot,'coordinated/replacement',rootRawSha256,root,{targetBytes:SAME_WIDTH_REPLACEMENT_BYTES}),h1FilePins=AUTHORED_FILES.filter(file=>sha256(readFileSync(resolve(packageRoot,file)))!==expectedA0Raw[file]).map(file=>{const bytes=readFileSync(resolve(packageRoot,file));return {bytes:bytes.length,locator:file,rawSha256:sha256(bytes)};});
    validateLocalA1({packageRoot,id:'coordinated/replacement',rootRawSha256,validatorBytes:replacement.bytes,h1Schema:replacement.h1Schema,a0SchemaBindings,a0Root:a0,primaryRoot,primaryPaths,h1FilePins});
    const a1=installSealedFixture(packageRoot,anchorRoot,locator);
    assert.equal(validateSealedA1({packageRoot,anchorRoot,locator,fixture:a1,id:'coordinated/A1'}),true,'coherent sealed A1 independent positive');
    const finalRoot=strictJson(readFileSync(resolve(packageRoot,rootLocator)),'coordinated final A1 root');
    primaryRoot=structuredClone(finalRoot);for(const row of primaryRoot.authorityPolicyGroups??[])delete row.contentDigest;for(const row of primaryRoot.supplementalPolicies??[])delete row.contentDigest;for(const row of primaryRoot.requirementAuthorityMap??[])delete row.contentDigest;if(primaryRoot.sourceCollisions){delete primaryRoot.sourceCollisions.contentDigest;for(const row of primaryRoot.sourceCollisions.entries??[])delete row.contentDigest;}if(primaryRoot.creationTransitionPolicy)delete primaryRoot.creationTransitionPolicy.contentDigest;delete primaryRoot.componentDigests;delete primaryRoot.contentDigest;
    const normalizedA0=structuredClone(a0);for(const row of normalizedA0.authorityPolicyGroups??[])delete row.contentDigest;for(const row of normalizedA0.supplementalPolicies??[])delete row.contentDigest;for(const row of normalizedA0.requirementAuthorityMap??[])delete row.contentDigest;delete normalizedA0.sourceCollisions.contentDigest;for(const row of normalizedA0.sourceCollisions.entries)delete row.contentDigest;delete normalizedA0.creationTransitionPolicy.contentDigest;delete normalizedA0.componentDigests;delete normalizedA0.contentDigest;
    primaryPaths=primaryDiffPaths(normalizedA0,primaryRoot);assert.deepEqual(primaryPaths,['/purpose'],'coordinated final A1 has one semantic field mutation');
    assert.equal(a1.anchorBytes.length,h0.anchorBytes.length,'same-length A0/A1 anchor');
    assert.notEqual(a1.pin.reviewAnchorRawSha256,h0.pin.reviewAnchorRawSha256,'A0/A1 anchor raw differs');
    assert.throws(()=>validateStatic({packageRoot,mode:'sealed',reviewAnchorPin:h0.pin}),error=>error instanceof Error&&error.message==='EAPP_ANCHOR_RAW','retained true H0 literal rejects installed A1');
  }finally{rmSync(packageRoot,{recursive:true,force:true});rmSync(anchorRoot,{recursive:true,force:true});}
});
