import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmodSync, copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { AUTHORED_FILES, assertRootSemantics, validateStatic } from '../validate-static.mjs';

const here=new URL('..',import.meta.url).pathname,repositoryRoot=resolve(here,'../../../../..');
const sourcePins=JSON.parse(readFileSync(new URL('../external-authority-prerequisite-policy-root.v1.json',import.meta.url))).dependencyBinding.sourceAuthorities;
const validateLiveUnsealed=()=>{const pairedEnvelope=existsSync(resolve(here,'MANIFEST.json'))&&existsSync(resolve(here,'SHA256SUMS'));if(!pairedEnvelope)return validateStatic({mode:'unsealed',repositoryRoot});const gateRoot=resolve(here,'..'),clone=mkdtempSync(resolve(gateRoot,'.eapp-source-only-'));chmodSync(clone,0o755);mkdirSync(resolve(clone,'schemas'),{mode:0o755});mkdirSync(resolve(clone,'test'),{mode:0o755});try{for(const locator of AUTHORED_FILES){copyFileSync(new URL(`../${locator}`,import.meta.url),resolve(clone,locator));chmodSync(resolve(clone,locator),0o644);}return validateStatic({packageRoot:clone,repositoryRoot,mode:'unsealed'});}finally{rmSync(clone,{recursive:true,force:true});}};
const withScannerClone=(gateRoot,label,payload,positive=false)=>{const clone=mkdtempSync(resolve(gateRoot,'.eapp-module-boundary-'));chmodSync(clone,0o755);mkdirSync(resolve(clone,'schemas'),{mode:0o755});mkdirSync(resolve(clone,'test'),{mode:0o755});try{for(const locator of AUTHORED_FILES){copyFileSync(new URL(`../${locator}`,import.meta.url),resolve(clone,locator));chmodSync(resolve(clone,locator),0o644);}assert.match(readFileSync(resolve(clone,'test/mutation.test.mjs'),'utf8'),/\['from','to'\]/u);if(payload)writeFileSync(resolve(clone,'test/static.test.mjs'),`${readFileSync(resolve(clone,'test/static.test.mjs'),'utf8')}\n${payload}\n`,{mode:0o644});if(positive)assert.equal(validateStatic({packageRoot:clone,repositoryRoot,mode:'unsealed'}).unsealed,true);else assert.throws(()=>validateStatic({packageRoot:clone,repositoryRoot,mode:'unsealed'}),error=>error instanceof Error&&error.message==='EAPP_IMPORT_BOUNDARY:test/static.test.mjs',label);}finally{rmSync(clone,{recursive:true,force:true});}};
const assertImportScannerCausal=()=>{const gateRoot=resolve(here,'..'),keyword=['im','port'].join(''),outWord=['ex','port'].join(''),childModule=['node:child_','pro','cess'].join(''),payloads=[['from-to-inert',null,true],['extra-allowed-declaration',`${keyword} { basename } from 'node:path';`,false],['side-effect-child-module',`${keyword} ${JSON.stringify(childModule)};`,false],['direct-dynamic',`const load=${keyword}('node:path');`,false],['comment-dynamic',`const load=${keyword}/*comment*/('node:path');`,false],['line-start-output',`${outWord} { basename } from 'node:path';`,false],['same-line-static-declaration',`const q=0; ${keyword} * as cp from ${JSON.stringify(childModule)};`,false],['same-line-output',`const q=0; ${outWord} { basename } from 'node:path';`,false],['comment-prefix-output',`/*x*/ ${outWord} { basename } from 'node:path';`,false]];assert.equal(payloads.length,9);assert.equal(new Set(payloads.map(([label])=>label)).size,9);for(const [label,payload,positive] of payloads)withScannerClone(gateRoot,label,payload,positive);};
const assertActivationScannerCausal=()=>{const gateRoot=resolve(here,'..'),part=(...items)=>items.join(''),proc=part('pro','cess'),getBuiltin=part('getBuiltin','Module'),childModule=part('node:child_','pro','cess'),opA=part('ex','ec','Sync'),opB=part('ex','ecFile','Sync'),opC=part('sp','awn','Sync'),payloads=[[`activation-01`,`${opC}('x')`],[`activation-02`,`cp.${opC}('x')`],[`activation-03`,`cp.${opA}('x')`],[`activation-04`,`cp.${opB}('x')`],[`activation-05`,`cp[${JSON.stringify(opA)}]('x')`],[`activation-06`,`${proc}.${getBuiltin}('node:fs')`],[`activation-07`,`${proc}.${part('bind','ing')}('fs')`],[`activation-08`,`new ${part('Work','er')}('x')`],[`activation-09`,`${part('Func','tion')}('return 0')`],[`activation-10`,`const g=${proc}.${getBuiltin};const cp=g(${JSON.stringify(childModule)});`],[`activation-11`,`const h=cp.${opA};h('x');`],[`activation-12`,`const h=cp[${JSON.stringify(opA)}];h('x');`],[`activation-13`,`const {${opB}:h}=cp;h('x');`]];assert.equal(payloads.length,13);assert.equal(new Set(payloads.map(([label])=>label)).size,13);for(const [label,payload] of payloads)withScannerClone(gateRoot,label,payload,false);};
const assertDocumentClaimsCausal=()=>{const gateRoot=resolve(here,'..'),word=['im','port'].join(''),cases=[['README.md',`Direct package-local Node invocations are nonauthorizing diagnostic self-checks only; they cannot authenticate any authored bytes they ${word} or execute.`],['COMMAND.txt','COMMAND.txt, validate-static.mjs, MANIFEST.json, SHA256SUMS, a package-derived hash, and a locally generated review anchor are not independent bootstrap trust roots and grant no authority.']];for(const [locator,sentence] of cases){const clone=mkdtempSync(resolve(gateRoot,'.eapp-document-boundary-'));chmodSync(clone,0o755);mkdirSync(resolve(clone,'schemas'),{mode:0o755});mkdirSync(resolve(clone,'test'),{mode:0o755});try{for(const file of AUTHORED_FILES){copyFileSync(new URL(`../${file}`,import.meta.url),resolve(clone,file));chmodSync(resolve(clone,file),0o644);}const path=resolve(clone,locator),source=readFileSync(path,'utf8');assert.equal(source.split(sentence).length,2);writeFileSync(path,source.replace(sentence,''),{mode:0o644});assert.throws(()=>validateStatic({packageRoot:clone,repositoryRoot,mode:'unsealed'}),error=>error instanceof Error&&error.message===`EAPP_STATUS:${locator}`);}finally{rmSync(clone,{recursive:true,force:true});}}};

test('unsealed positive', () => {assert.equal(validateLiveUnsealed().unsealed, true);assertImportScannerCausal();assertActivationScannerCausal();assertDocumentClaimsCausal();});
test('direct root semantics', () => assert.deepEqual(assertRootSemantics(), {dependencyJoined:true,nonAuthority:true}));
test('direct dependency and source joins', () => {const result=validateLiveUnsealed();assert.equal(result.sourceContracts,10);for(const pin of sourcePins){const bytes=readFileSync(resolve(repositoryRoot,pin.locator));assert.equal(bytes.length,pin.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),pin.rawSha256);assert.equal(JSON.parse(bytes).contentDigest.value,pin.contentDigest);}});
test('direct zero and false boundary', () => assert.equal(assertRootSemantics().nonAuthority, true));
